<script setup lang="ts">
import { computed, ref } from 'vue'
import AppHeader from '../components/AppHeader.vue'
import RuleSurfaceScope from '../components/RuleSurfaceScope.vue'
import { allRulePages, findRulePage, quickReferencePages, ruleCategories, type RuleCategoryDefinition } from '../data/ruleCatalog'
import { loadRecentRuleSlugs } from '../services/ruleRecent'

const query=ref('')
const recentSlugs=ref(loadRecentRuleSlugs())
const defaultRecentSlugs=['attributes-skills','core-rules','character-creation','to-strike']
const recentPages=computed(()=>Array.from(new Set([...recentSlugs.value,...defaultRecentSlugs])).map(slug=>findRulePage(slug)).filter(Boolean).slice(0,4))
const searchResults=computed(()=>{const q=query.value.trim().toLowerCase();if(!q)return[];return allRulePages.filter(page=>`${page.title} ${page.summary} ${(page.keywords||[]).join(' ')}`.toLowerCase().includes(q))})
function clearSearch(){query.value=''}
function visibleCategoryPages(category:RuleCategoryDefinition){return category.id==='fundamentals'?category.pages:[category.landing,...category.pages]}
</script>

<template><main class="page rules-page rules-index-page"><AppHeader /><RuleSurfaceScope><div class="page-title-block rules-title-block"><h1>Rules</h1></div>
<label class="search-bar rules-primary-search" aria-label="Search rules"><svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="11" cy="11" r="6"/><path d="m16 16 4 4"/></svg><input v-model="query" type="search" placeholder="Search rules…" autocomplete="off" /><button v-if="query" type="button" class="search-clear" aria-label="Clear search" @click="clearSearch">×</button></label>
<section v-if="query" class="rules-index-panel card-surface"><header class="rules-index-heading"><span>Search Results</span><small>{{ searchResults.length }} found</small></header><div class="rules-index-list"><RouterLink v-for="result in searchResults" :key="result.slug" class="rules-index-row" :to="`/rules/read/${result.slug}`"><span><strong>{{ result.title }}</strong><small>{{ result.summary }}</small></span><svg viewBox="0 0 24 24"><path d="m9 5 7 7-7 7"/></svg></RouterLink><div v-if="!searchResults.length" class="empty-inline">No matching rules.</div></div></section>
<template v-else><section class="rules-index-panel card-surface rules-recent-panel"><header class="rules-index-heading"><span>Recent</span></header><div class="rules-recent-grid"><RouterLink v-for="recent in recentPages" :key="recent!.slug" class="recent-rule-box" :to="`/rules/read/${recent!.slug}`"><strong>{{ recent!.title }}</strong><small>{{ recent!.summary }}</small></RouterLink></div></section>
<section class="rules-index-panel card-surface"><header class="rules-index-heading"><span>References</span></header><div class="rules-index-list"><RouterLink v-for="entry in quickReferencePages" :key="entry.slug" class="rules-index-row" :to="`/rules/read/${entry.slug}`"><span><strong>{{ entry.title }}</strong><small>{{ entry.summary }}</small></span><svg viewBox="0 0 24 24"><path d="m9 5 7 7-7 7"/></svg></RouterLink></div></section>
<section class="rules-chapter-stack"><template v-for="category in ruleCategories" :key="category.id"><details class="rules-index-panel rules-chapter card-surface"><summary class="rules-index-heading rules-chapter-heading"><span><strong>{{ category.title }}</strong><small>{{ category.summary }}</small></span><svg viewBox="0 0 24 24"><path d="m6 9 6 6 6-6"/></svg></summary><div class="rules-index-list"><RouterLink v-for="entry in visibleCategoryPages(category)" :key="entry.slug" class="rules-index-row" :to="`/rules/read/${entry.slug}`"><span><strong>{{ entry.title }}</strong><small>{{ entry.summary }}</small></span><svg viewBox="0 0 24 24"><path d="m9 5 7 7-7 7"/></svg></RouterLink></div></details>
</template></section></template></RuleSurfaceScope></main></template>

<style scoped>
.rules-primary-search{width:100%;margin:0 0 14px}.rules-index-panel{overflow:hidden;margin-bottom:12px;border-radius:13px}.rules-index-heading{min-height:48px;display:flex;align-items:center;justify-content:space-between;gap:12px;padding:11px 14px;border-bottom:1px solid var(--line);background:var(--paper-2);font-weight:900}.rules-index-heading>small{color:var(--ink-soft);font-weight:650}.rules-index-list{display:grid}.rules-chapter .rules-index-list{padding-left:14px}.rules-index-row{min-height:58px;display:grid;grid-template-columns:minmax(0,1fr) 20px;align-items:center;gap:12px;padding:11px 14px;border-bottom:1px solid var(--line);background:var(--paper);color:var(--ink);text-decoration:none}.rules-index-row:last-child{border-bottom:0}.rules-index-row:hover{background:var(--paper-2)}.rules-index-row>span{display:grid;gap:3px;min-width:0}.rules-index-row strong{font-family:Georgia,'Times New Roman',serif;font-size:calc(15px + var(--font-offset))}.rules-index-row small{color:var(--ink-soft);line-height:1.35}.rules-index-row svg,.rules-chapter-heading>svg{width:18px;height:18px;fill:none;stroke:var(--ink-soft);stroke-width:2;stroke-linecap:round;stroke-linejoin:round}.rules-recent-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px;padding:10px}.recent-rule-box{--recent-tone:var(--accent);display:grid;grid-template-rows:auto auto;align-content:start;gap:4px;min-width:0;min-height:76px;padding:10px 12px;border:1px solid var(--surface-line);border-top:5px solid var(--recent-tone);border-radius:9px;background:var(--surface-front);color:var(--ink);text-decoration:none}.recent-rule-box:nth-child(4n+1){--recent-tone:var(--detail-trait-heritage)}.recent-rule-box:nth-child(4n+2){--recent-tone:var(--detail-trait-culture)}.recent-rule-box:nth-child(4n+3){--recent-tone:var(--detail-equipment)}.recent-rule-box:nth-child(4n){--recent-tone:var(--detail-spark)}.recent-rule-box:hover{background:var(--surface-title)}.recent-rule-box strong{font-family:Georgia,'Times New Roman',serif}.recent-rule-box small{display:block;color:var(--ink-soft);line-height:1.35}.rules-chapter-stack{display:grid;gap:10px}.rules-chapter{margin:0}.rules-chapter-heading{list-style:none;cursor:pointer;border-bottom:0}.rules-chapter-heading::-webkit-details-marker{display:none}.rules-chapter-heading>span{display:grid;gap:3px}.rules-chapter-heading>span>small{color:var(--ink-soft);font-weight:600}.rules-chapter[open] .rules-chapter-heading{border-bottom:1px solid var(--line)}.rules-chapter[open] .rules-chapter-heading>svg{transform:rotate(180deg)}@media(max-width:620px){.rules-recent-grid{grid-template-columns:1fr}.rules-index-heading{align-items:flex-start}}
</style>
