import { ref, watch } from 'vue'
import { readLocalStorage, SETTINGS_STORE, writeLocalStorage } from '../services/storage'
import { defaultBackgroundOption } from '../data/backgroundCatalog'
import { DEFAULT_MEASUREMENT, type MeasurementOption } from '../rules/measurements'
export type FontSize='smallest'|'small'|'normal'|'large'|'largest'
export type LogoSize='smallest'|'small'|'normal'|'large'|'largest'
export type RoleTheme='default'|'warrior'|'healer'|'ranger'|'thief'
type SettingsShape={darkMode:boolean;compactRows:boolean;fontSize:FontSize;logoSize:LogoSize;boldText:boolean;roleTheme:RoleTheme;backgroundImage:string;backgroundGrayscale:boolean;bootAudio:boolean;creationTips:boolean;measurement:MeasurementOption}
const defaults:SettingsShape={darkMode:false,compactRows:false,fontSize:'normal',logoSize:'largest',boldText:false,roleTheme:'default',backgroundImage:defaultBackgroundOption,backgroundGrayscale:false,bootAudio:true,creationTips:true,measurement:DEFAULT_MEASUREMENT}
const measurementOptions=new Set<MeasurementOption>(['squares','yards','feet','meters'])
function normalizeFontSize(value:unknown):FontSize{return value==='smallest'||value==='small'||value==='large'||value==='largest'?value:'normal'}
function normalizeLogoSize(value:unknown):LogoSize{return value==='smallest'||value==='small'||value==='normal'||value==='large'||value==='largest'?value:'largest'}
function normalizeRoleTheme(value:unknown):RoleTheme{return value==='warrior'||value==='healer'||value==='ranger'||value==='thief'?value:'default'}
function loadSettings():SettingsShape{try{const parsed=JSON.parse(readLocalStorage(SETTINGS_STORE)||'{}') as Partial<SettingsShape>;return{darkMode:Boolean(parsed.darkMode),compactRows:Boolean(parsed.compactRows),fontSize:normalizeFontSize(parsed.fontSize),logoSize:normalizeLogoSize(parsed.logoSize),boldText:Boolean(parsed.boldText),roleTheme:normalizeRoleTheme(parsed.roleTheme),backgroundImage:typeof parsed.backgroundImage==='string'&&parsed.backgroundImage.trim()?parsed.backgroundImage:defaults.backgroundImage,backgroundGrayscale:Boolean(parsed.backgroundGrayscale),bootAudio:parsed.bootAudio===undefined?defaults.bootAudio:Boolean(parsed.bootAudio),creationTips:parsed.creationTips===undefined?defaults.creationTips:Boolean(parsed.creationTips),measurement:measurementOptions.has(parsed.measurement as MeasurementOption)?parsed.measurement as MeasurementOption:DEFAULT_MEASUREMENT}}catch{return defaults}}
const stored=loadSettings()
const darkMode=ref(stored.darkMode),compactRows=ref(stored.compactRows),fontSize=ref<FontSize>(stored.fontSize),logoSize=ref<LogoSize>(stored.logoSize),boldText=ref(stored.boldText),roleTheme=ref<RoleTheme>(stored.roleTheme),backgroundImage=ref(stored.backgroundImage),backgroundGrayscale=ref(stored.backgroundGrayscale),bootAudio=ref(stored.bootAudio),creationTips=ref(stored.creationTips),measurement=ref<MeasurementOption>(stored.measurement)
function apply(){document.body.classList.toggle('theme-dark',darkMode.value);document.body.classList.toggle('compact-rows',compactRows.value);document.body.classList.toggle('bold-text',boldText.value);document.documentElement.dataset.fontSize=fontSize.value;document.documentElement.dataset.logoSize=logoSize.value;document.documentElement.dataset.roleTheme=roleTheme.value;document.documentElement.dataset.backgroundImage=backgroundImage.value;document.documentElement.dataset.backgroundGrayscale=backgroundGrayscale.value?'true':'false';document.documentElement.dataset.measurement=measurement.value}
watch([darkMode,compactRows,fontSize,logoSize,boldText,roleTheme,backgroundImage,backgroundGrayscale,bootAudio,creationTips,measurement],()=>{apply();writeLocalStorage(SETTINGS_STORE,JSON.stringify({darkMode:darkMode.value,compactRows:compactRows.value,fontSize:fontSize.value,logoSize:logoSize.value,boldText:boldText.value,roleTheme:roleTheme.value,backgroundImage:backgroundImage.value,backgroundGrayscale:backgroundGrayscale.value,bootAudio:bootAudio.value,creationTips:creationTips.value,measurement:measurement.value}))},{immediate:true})
export function useSettings(){function toggleTheme(){darkMode.value=!darkMode.value}function reset(){darkMode.value=defaults.darkMode;compactRows.value=defaults.compactRows;fontSize.value=defaults.fontSize;logoSize.value=defaults.logoSize;boldText.value=defaults.boldText;roleTheme.value=defaults.roleTheme;backgroundImage.value=defaults.backgroundImage;backgroundGrayscale.value=defaults.backgroundGrayscale;bootAudio.value=defaults.bootAudio;creationTips.value=defaults.creationTips;measurement.value=defaults.measurement}return{darkMode,compactRows,fontSize,logoSize,boldText,roleTheme,backgroundImage,backgroundGrayscale,bootAudio,creationTips,measurement,toggleTheme,reset}}
