import assert from 'node:assert/strict'
import { rhythmResult, opposedResult, effectiveGuts, damageResult, healthPenalty, advancementCost } from './rules-engine.js'

assert.equal(rhythmResult([4,5,6],'normal',2,1).total,18)
assert.deepEqual(rhythmResult([2,4,7,9],'edged',0,0).kept,[4,7,9])
assert.deepEqual(rhythmResult([2,4,7,9],'weighted',0,0).kept,[2,4,7])
assert.equal(opposedResult([5,5,5],0,0,[5,5,5],0,0).hit,false, 'Ward ties defend')
assert.equal(effectiveGuts('standard',3,2,1),6)
assert.equal(effectiveGuts('direct',3,2,1),4, 'ceil(5/2)=3 plus 1 condition')
assert.equal(effectiveGuts('lethal',3,2,1),1, 'Lethal bypasses base and equipment, not conditions')
assert.equal(damageResult(8,'direct',3,2,1).suffered,4)
assert.equal(healthPenalty(30),0)
assert.equal(healthPenalty(5),-1)
assert.equal(healthPenalty(3),-2)
assert.equal(healthPenalty(1),-3)
assert.equal(healthPenalty(0),null)
assert.equal(advancementCost('attribute',1),4)
assert.equal(advancementCost('skill',1),4)
assert.equal(advancementCost('new-skill',1),6)
assert.equal(advancementCost('talent',1),10)
assert.equal(advancementCost('magic',1),14)
console.log('Bramble Heart v0.01 rules-engine tests: PASS')
