<script setup lang="ts">
import { computed, ref, watch } from 'vue'
import { useRoute } from 'vue-router'
import GameUpdateList from '../components/GameUpdateList.vue'
import RulePageLayout from '../components/RulePageLayout.vue'
import CoreActionCard from '../components/CoreActionCard.vue'
import RuleFeatureCard from '../components/RuleFeatureCard.vue'
import ThreadpieceExchange from '../components/ThreadpieceExchange.vue'
import SpeciesRuleSheet from '../components/SpeciesRuleSheet.vue'
import { canonicalRuleSlug, findRuleCategory, findRulePage, findRuleParentPage, loreNavigation, quickFaq, quickReferencePages, resolveSourceSections, ruleCategories, rulePageNavigation } from '../data/ruleCatalog'
import { rankModifier, structuredRule, visibleRuleFields } from '../rules/rulesEngine'
import { speciesData } from '../data/speciesData'
import { deeds, deedRewardLabel } from '../data/deeds'
import { attributes, faiths, homelands, oaths, sparks, type AttributeId } from '../data/bramble'
import { coreActions } from '../data/coreAbilities'
import { startingPathOptions } from '../data/creationRules'
import { STARTING_WEALTH_WP } from '../rules/economy'
import { WP_PER_SP } from '../rules/threadpieces'
import { loreElementalResistance, loreSpells } from '../data/magicOptions'
import { loreDescriptions, spellDetails } from '../data/magicDetails'
import { gearShopItems as catalogGearShopItems, sparkDetails } from '../data/characterOptions'
import targetingLineImage from '../assets/rules/aoe-line.png'
import targetingConeImage from '../assets/rules/aoe-cone.png'
import targetingOrbImage from '../assets/rules/aoe-orb.png'
import targetingBlockedImage from '../assets/rules/aoe-blocked.png'
import { externalMonsters, findExternalMonster, monsterCategories, monsterSlug, WOODLANDS_MONSTERS_URL } from '../data/externalMonsters'
import { recordRecentRule } from '../services/ruleRecent'
import { ruleSourceDocuments, SPELL_HEART_DAMAGE_RULE, type RuleSourceBlock, type RuleSourceSection } from '../data/rulesCurrent'
import { TALENT_CATEGORIES, canonicalTalentName, classifyTalent, talentNameMatches } from '../data/talentCategories'
import { SIGNATURE_SPELLS, spellCostLabel } from '../rules/magicRules'
import { formatMeasurementText } from '../rules/measurements'
import { useSettings } from '../state/settings'
import { ABILITY_TYPE_KEYWORDS, abilityFeaturePillClass, abilityFeaturePillKeywords, abilityFeaturePillLabel, abilityTypeClass, activeAbilityKeywords, canonicalAbilityType } from '../rules/abilityPresentation'

const route=useRoute()
const {measurement}=useSettings()
const slug=computed(()=>String(route.params.slug||''))
const page=computed(()=>findRulePage(slug.value))
const canonicalSlug=computed(()=>canonicalRuleSlug(slug.value))
const rawSourceSections=computed(()=>page.value?resolveSourceSections(page.value):[])
const ruleNavigation=computed(()=>rulePageNavigation(canonicalSlug.value))
const loreAttunedPreview=ref(false)
watch(slug,value=>{loreAttunedPreview.value=false;if(value)recordRecentRule(value)},{immediate:true})

type CreationAttributeRanks=Record<AttributeId,number>
function freshCreationAttributeRanks(){return Object.fromEntries(attributes.map(attribute=>[attribute.id,1])) as CreationAttributeRanks}
const creationAttributeRanks=ref<CreationAttributeRanks>(freshCreationAttributeRanks())
const creationAttributePointsRemaining=computed(()=>5-attributes.reduce((spent,attribute)=>spent+(creationAttributeRanks.value[attribute.id]-1),0))
function adjustCreationAttribute(id:AttributeId,amount:number){
  const current=creationAttributeRanks.value[id]
  if(amount>0&&(current>=3||creationAttributePointsRemaining.value<=0))return
  if(amount<0&&current<=1)return
  creationAttributeRanks.value={...creationAttributeRanks.value,[id]:current+amount}
}
function creationAttributeModifier(id:AttributeId){return rankModifier(creationAttributeRanks.value[id])}
function creationAttributeSecondary(id:AttributeId){
  const rank=creationAttributeRanks.value[id],modifier=rankModifier(rank)
  if(id==='agility')return[{label:'Accuracy',value:String(rank)},{label:'Aim',value:String(modifier)},{label:'Speed',value:`2 + ${modifier} = ${modifier+2}`}]
  if(id==='might')return[{label:'Fury',value:String(rank)},{label:'Brawl',value:String(modifier)}]
  if(id==='hide')return[{label:'Guts',value:String(rank)},{label:'Ward',value:String(modifier)}]
  if(id==='lore')return[{label:'Power',value:String(rank)},{label:'Control',value:String(modifier)}]
  return[{label:'Heart',value:String(rank)},{label:'Spirit',value:String(modifier)}]
}
watch(slug,(value,previous)=>{if(value==='character-creation'||previous==='character-creation')creationAttributeRanks.value=freshCreationAttributeRanks()})

const bannerModules=import.meta.glob('../assets/rule-banners/*.{png,PNG,jpg,JPG,jpeg,JPEG,webp,WEBP}',{eager:true,query:'?url',import:'default'}) as Record<string,string>
function bannerKey(value:string){const key=value.replace(/[^a-z0-9]+/gi,'').toLowerCase();return key==='athromundas'?'anthromundas':key}
function bannerStem(path:string){return (path.split('/').pop()||'').replace(/\.[^.]+$/,'').replace(/^banner[-_ ]*/i,'')}
const currentBanner=computed(()=>{
  if(!page.value)return''
  const wanted=Array.from(new Set([page.value.title,page.value.slug,page.value.title.replace(/^Lore of /i,''),page.value.slug.replace(/^lore[-_]?/i,'')].map(bannerKey).filter(Boolean)))
  const entry=Object.entries(bannerModules).find(([path])=>{
    const stem=bannerKey(bannerStem(path));return wanted.some(key=>stem===key||stem.endsWith(key)||key.endsWith(stem))
  })
  return entry?.[1]||''
})
function abilityTypes(values:string[]){return Array.from(new Set(traitKeywords(values).map(canonicalAbilityType).filter(value=>ABILITY_TYPE_KEYWORDS.has(value))))}
function manaCostFromRule(text:string){const match=text.match(/\bCOST:\s*\[?([0-9]+)\]?\s*mana/i);return match?Number(match[1]):null}

function displayText(value:string){return formatMeasurementText(value.replace(/\bProwess\b/g,'Agility').replace(/\bprowess\b/g,'agility'),measurement.value)}
function isDialogue(value:string){return /\b(?:Watcher|Player|Selu):/.test(value)}
function dialogueParts(value:string){
  const parts:Array<{actor:string;text:string}>=[]
  const rx=/(Watcher|Player|Selu):\s*[“"]?([^”"]+)[”"]?/g
  let match:RegExpExecArray|null
  while((match=rx.exec(value)))parts.push({actor:match[1],text:match[2].trim()})
  return parts
}
function keywordParts(value:string){if(!/^KEYWORDS?:/i.test(value.trim()))return[];return value.split(':',2)[1].split('|').map(item=>item.trim()).filter(Boolean)}
function keywordPartsForBlock(block:RuleSourceBlock){return block.type==='paragraph'?keywordParts(block.text):[]}
function isExampleHeading(value:string){return /example/i.test(value)}

const sourceSections=computed(()=>{
  const entries=rawSourceSections.value
  if(page.value?.loreHeading){
    const entry=entries[0];if(!entry)return[]
    const headings=new Set(loreNavigation.map(item=>item.heading))
    const blocks=entry.section.blocks
    const start=blocks.findIndex(block=>block.type==='paragraph'&&block.text.trim()===page.value?.loreHeading)
    if(start<0)return[]
    let end=blocks.length
    for(let index=start+1;index<blocks.length;index++){const block=blocks[index];if(block.type==='paragraph'&&headings.has(block.text.trim())){end=index;break}}
    const section:RuleSourceSection={heading:page.value.loreHeading,blocks:blocks.slice(start+1,end)}
    return[{...entry,section}]
  }
  if(canonicalSlug.value==='to-damage')return entries.filter(entry=>!/^DAMAGE\s*[–-]\s*GUTS\s*=\s*TOTAL DAMAGE$/i.test(displayText(entry.section.heading).trim()))
  return entries
})

const loreIndex=computed(()=>loreNavigation.findIndex(item=>item.slug===canonicalSlug.value))
const breadcrumbSection=computed(()=>{
  if(loreIndex.value>=0||quickReferencePages.some(item=>item.slug===canonicalSlug.value))return'References'
  if(findExternalMonster(canonicalSlug.value))return'The Watcher'
  return findRuleCategory(canonicalSlug.value)?.title||'Rules'
})
const breadcrumbParent=computed(()=>findRuleParentPage(canonicalSlug.value)||null)
const layoutParent=computed(()=>{
  if(breadcrumbSection.value==='References')return{label:'References',path:'/rules'}
  return breadcrumbParent.value&&breadcrumbParent.value.slug!==page.value?.slug?{label:breadcrumbSection.value,path:`/rules/read/${breadcrumbParent.value.slug}`}:null
})
const currentCategoryLanding=computed(()=>ruleCategories.find(category=>category.landing.slug===canonicalSlug.value)||null)
const landingEntries=computed(()=>currentCategoryLanding.value?.pages||[])
function labeledParagraph(value:string){const text=displayText(value).trim();const match=text.match(/^([^:]{2,45}):\s+(.+)$/);return match?{label:match[1],body:match[2]}:{label:'',body:text}}
function bulletParts(value:string){const parts=displayText(value).split(/\s*•\s*/).map(part=>part.trim()).filter(Boolean);return parts.length>1?parts:[]}
function optionalTextParts(value:string){const match=value.match(/^(.*?)(\s*\(optional\))(.*)$/i);return match?[{text:match[1],optional:false},{text:match[2],optional:true},{text:match[3],optional:false}]:[{text:value,optional:false}]}
function singleCellText(block:RuleSourceBlock){return block.type==='table'&&block.rows.length===1&&block.rows[0].length===1?displayText(block.rows[0][0]).trim():''}

const currentSpecies=computed(()=>canonicalSlug.value.startsWith('species-')?speciesData.find(item=>`species-${item.name.toLowerCase()}`===canonicalSlug.value)||null:null)
const currentMonster=computed(()=>findExternalMonster(canonicalSlug.value)||null)
const monsterGroups=computed(()=>monsterCategories.map(category=>{
  const monsters=externalMonsters.filter(monster=>monster.category===category.name)
  const parents=monsters.filter(monster=>!monster.group)
  const families=parents.map(parent=>({parent,children:monsters.filter(monster=>monster.group===parent.name)}))
  const groupedNames=new Set(families.flatMap(family=>[family.parent.name,...family.children.map(child=>child.name)]))
  for(const orphan of monsters.filter(monster=>!groupedNames.has(monster.name)))families.push({parent:orphan,children:[]})
  return{category,monsters,families}
}))
const talentSections=ruleSourceDocuments.talents.sections.filter(section=>section.heading!=='Overview'&&section.heading!=='TALENTS'&&!section.heading.startsWith('KEYWORDS'))
function talentRuleText(name:string){const section=talentSections.find(item=>talentNameMatches(item.heading,name));return section?.blocks.filter(block=>block.type==='paragraph').map(block=>block.type==='paragraph'?block.text:'').join(' ')||''}
function talentRuleKeywords(name:string){const match=talentRuleText(name).match(/\bKEYWORDS?:\s*(.+)$/i);return activeAbilityKeywords(match?[match[1]]:[])}
function talentCategory(name:string){return classifyTalent(name,talentRuleText(name),talentRuleKeywords(name))}
const talentRuleGroups=computed(()=>TALENT_CATEGORIES.map(category=>({category,talents:talentSections.map(section=>canonicalTalentName(section.heading)).filter(name=>talentCategory(name)===category)})).filter(group=>group.talents.length))
const spellLoreBySlug:Record<string,string>={'lore-invocation':'Invocation','lore-flames':'Flames','lore-frost':'Frost','lore-hallows':'Hallows','lore-harmony':'Harmony','lore-life':'Life','lore-oath':'Oath','lore-wilds':'Wilds'}
const currentSpellLore=computed(()=>spellLoreBySlug[canonicalSlug.value]||'')
const currentLoreSpells=computed(()=>currentSpellLore.value?(loreSpells[currentSpellLore.value]||[]):[])
function spellRuleDetail(name:string){return spellDetails[name]}
const canPreviewLoreAttunement=computed(()=>Boolean(currentSpellLore.value&&currentSpellLore.value!=='Invocation'))
function displayedLoreCost(name:string){const detail=spellRuleDetail(name);if(!detail)return'Variable';return spellCostLabel({name,lore:detail.lore,baseCost:detail.manaCost,attunedLore:loreAttunedPreview.value&&canPreviewLoreAttunement.value?currentSpellLore.value:''})}
function spellLoreClass(name:string){return `spell-lore-${String(spellDetails[name]?.lore||'invocation').toLowerCase()}`}
function isSignatureSpell(name:string){return SIGNATURE_SPELLS.has(name)}
const currentLoreResistance=computed(()=>currentSpellLore.value&&currentSpellLore.value!=='Invocation'?loreElementalResistance[currentSpellLore.value as keyof typeof loreElementalResistance]||'':'')
const spellKeywordCards=computed(()=>{const blocks=sectionByHeading('winds-of-magic','SPELL KEYWORDS')?.blocks||[];return blocks.flatMap(block=>{if(block.type!=='paragraph')return[];const text=displayText(block.text);const names=['AREA OF EFFECT','SIGNATURE','CANTRIP','ENHANCE','SUMMON','MAGIC','HEX'];const title=names.find(name=>text.toUpperCase().startsWith(name))||'SPELL';return[{title,text}]})})
const signatureExampleName='Immolation'
const signatureExample=computed(()=>spellDetails[signatureExampleName])
const targetingRules=[
  {title:'Line',keyword:'LINE[n]',image:targetingLineImage,text:'A Line ability creates a straight path that never bends and affects every square it touches. The user chooses the direction; the Line continues from the user until it reaches its listed maximum length or an obstacle the ability cannot pass through.',example:'LINE[10] traces a straight line exactly ten squares long in the chosen direction. Every valid character, object, or terrain feature whose square lies along that path is affected.'},
  {title:'Cone',keyword:'CONE[n]',image:targetingConeImage,text:'A Cone ability begins adjacent to the user and extends outward in a triangular pattern on the grid. Its width grows as it advances, matching the listed area size.',example:'CONE[6] starts in the square directly in front of the user and expands to a roughly triangular shape six squares long and six squares wide at its farthest edge.'},
  {title:'Orb',keyword:'ORB[n]',image:targetingOrbImage,text:'For an Orb ability, choose a valid point within the Ability’s range. The Orb expands from that square as a square-shaped area whose size is determined by the Orb number. It ignores the user’s facing.',example:'ORB[7] creates a 7×7 block of squares from the chosen point. Every valid target whose square lies inside that area, including the edges, is affected.'},
]
const combatAttackCoreActions=coreActions.filter(action=>['MELEE STRIKE','RANGE STRIKE','ARCANE COMMAND'].includes(action.name))
const instinctCoreActions=coreActions.filter(action=>action.keywords.map(canonicalAbilityType).includes('Instinct'))
const instinctTraitExamples=computed(()=>speciesData.flatMap(species=>[...species.speciesTraits,...species.cultureTraits].map(trait=>({species:species.name,trait}))).filter(item=>traitKeywords(item.trait.keywords).map(canonicalAbilityType).includes('Instinct')).slice(0,2))
const combatEncounterSection=computed(()=>sectionByHeading('battle','COMBAT ENCOUNTER'))
const determiningPositionsSection=computed(()=>sectionByHeading('battle','DETERMINING POSITIONS'))
const squaresMeasurementsSection=computed(()=>sectionByHeading('battle','SQUARES & MEASUREMENTS'))
const initiativeSection=computed(()=>sectionByHeading('battle','INITIATIVE ORDER'))
const roundsTurnsSection=computed(()=>sectionByHeading('battle','ROUNDS & TURNS'))
const takingTurnSection=computed(()=>sectionByHeading('battle','TAKING YOUR TURN'))
const manaSection=computed(()=>sectionByHeading('battle','MANA'))
const renewTheHeartAction=coreActions.find(action=>action.name==='RENEW THE HEART')!
function traitKeywords(values:string[]){return activeAbilityKeywords(values)}
function skillTreeName(block:RuleSourceBlock){if(block.type!=='table'||block.rows.length<2)return'';const row=block.rows[1];return row.length===1&&/Skill Tree$/i.test(row[0])?displayText(row[0]):''}
function skillTreeRows(block:RuleSourceBlock){return block.type==='table'?block.rows.slice(2):[]}
function skillTreeTone(name:string){return name.toLowerCase().split(' ')[0]||'skill'}
function isBuildingSeluTable(block:RuleSourceBlock){const text=singleCellText(block);return /^Selu(?:’s| of )/i.test(text)}
function bracketParts(value:string){const text=displayText(value);const parts:Array<{text:string;bold:boolean}>=[];const rx=/(\[[+-]?\d+(?:\.\d+)?\])/g;let last=0,match:RegExpExecArray|null;while((match=rx.exec(text))){if(match.index>last)parts.push({text:text.slice(last,match.index),bold:false});parts.push({text:match[0],bold:true});last=match.index+match[0].length}if(last<text.length)parts.push({text:text.slice(last),bold:false});return parts.length?parts:[{text,bold:false}]}
function isLongNarrativeHeading(value:string){const t=displayText(value).trim();return t.startsWith('Packs, Herds, & Kinships (Optional Rule)')||t.startsWith('WATCHER’S NOTE')}
function narrativeParts(value:string){const t=displayText(value).trim();if(t.startsWith('WATCHER’S NOTE'))return{title:'WATCHER’S NOTE',body:t.replace(/^WATCHER’S NOTE\s*/,'')};const title='Packs, Herds, & Kinships (Optional Rule)';return{title,body:t.replace(title,'').trim()}}
function equipmentTableRows(block:RuleSourceBlock){if(canonicalSlug.value!=='adventuring-gear'||block.type!=='table'||block.rows.length<2||block.rows[0].length<2)return[];const headers=block.rows[0].map(displayText);return block.rows.slice(1).filter(row=>row.some(cell=>String(cell).trim())).map(row=>({name:displayText(row[0]||'Item'),fields:row.slice(1).map((cell,index)=>({label:headers[index+1]||`Value ${index+1}`,value:displayText(cell||'—')}))}))}
function characterCreationStepParts(section:RuleSourceSection){const match=section.heading.match(/^(\d+)\.\s*(.+)$/);return match?{number:match[1],title:displayText(match[2])}:null}
function isCharacterCreationStep(section:RuleSourceSection){return canonicalSlug.value==='character-creation'&&Boolean(characterCreationStepParts(section))}
function isCharacterCreationAttributeTable(section:RuleSourceSection,block:RuleSourceBlock){return canonicalSlug.value==='character-creation'&&/^5\.\s*ATTRIBUTES DISTRIBUTION$/i.test(section.heading)&&block.type==='table'&&/^Attribute$/i.test(block.rows[0]?.[0]||'')}
function characterCreationStepNumber(section:RuleSourceSection){return Number(characterCreationStepParts(section)?.number||0)}
function creationGraphicStep(section:RuleSourceSection,step:number){return canonicalSlug.value==='character-creation'&&characterCreationStepNumber(section)===step}
const creationHomelandExample=homelands.find(item=>item.name==='Willowstead')||homelands[0]
const creationFaithExample='The Dreamtide'
const creationOathExample=oaths.find(item=>item[0]==='Balance')||oaths[0]
const creationStartingWealthSp=STARTING_WEALTH_WP/WP_PER_SP
type DeedEntry={name:string;flavor:string;objective:string;reward:string;keywords:string[];rollRange?:string}
const sparkRuleSections=computed(()=>ruleSourceDocuments.sparks.sections.filter(section=>section.heading!=='Overview'&&section.blocks.length))
const sparkWhatSections=computed(()=>sparkRuleSections.value.filter(section=>['WHAT IS A SPARK?','KEYWORD LIBRARY'].includes(section.heading)))
const premadeSparkCards=computed(()=>sparks.map(([name,keywords])=>({name,keywords:keywords.split(',').map(value=>value.trim()).filter(Boolean),description:sparkDetails[name]?.description||''})).sort((a,b)=>a.name.localeCompare(b.name)))
const deedIntro=computed(()=>ruleSourceDocuments.deeds.sections.filter(section=>section.heading==='DEEDS'&&section.blocks.length).flatMap(section=>section.blocks.filter(block=>block.type==='paragraph').map(block=>block.type==='paragraph'?block.text:'')))
const deedEntries=computed<DeedEntry[]>(()=>deeds.map(deed=>({name:deed.name,flavor:deed.flavor,objective:deed.objective,reward:deedRewardLabel(deed),keywords:[...deed.keywords]})))
const deedEntriesSorted=computed(()=>{const sorted=[...deedEntries.value].sort((a,b)=>a.name.localeCompare(b.name));const n=sorted.length;return sorted.map((deed,index)=>{const start=Math.floor(index*100/n)+1,end=Math.floor((index+1)*100/n);const format=(value:number)=>String(value).padStart(2,'0');return{...deed,rollRange:`${format(start)}–${format(end)}`}})})
const sparkExamples=computed(()=>premadeSparkCards.value.filter(item=>['Courageous','Scholar'].includes(item.name)))
const creationSparkExample=computed(()=>premadeSparkCards.value.find(item=>item.name==='Healer')||premadeSparkCards.value[0])
const creationDeedExample=computed(()=>deedEntries.value.find(item=>item.name==='Gentle Guardian')||deedEntries.value[0])
function headingKey(value:string){return displayText(value).trim().toLowerCase().replace(/[’']/g,"'")}
function sectionByHeading(documentKey:string,heading:string){return ruleSourceDocuments[documentKey]?.sections.find(section=>headingKey(section.heading)===headingKey(heading))||null}
function isToDamageSection(section:RuleSourceSection){return canonicalSlug.value==='to-damage'&&section.heading==='TO DAMAGE'}
function isDamageCategorySection(section:RuleSourceSection){return canonicalSlug.value==='to-damage'&&section.heading==='DAMAGE CATEGORY'}
function isToSoakSection(section:RuleSourceSection){return canonicalSlug.value==='to-damage'&&section.heading==='TO SOAK'}
function isResistanceSection(section:RuleSourceSection){return canonicalSlug.value==='to-damage'&&section.heading==='RESISTANCES & WEAKNESS'}
function commonSections(documentKey:string,names:readonly string[]){return names.map(name=>sectionByHeading(documentKey,name)).filter((section):section is RuleSourceSection=>Boolean(section))}
const commonHomelandSections=computed(()=>commonSections('homeland',homelands.map(item=>item.name)).sort((a,b)=>a.heading.localeCompare(b.heading)))
const commonOathSections=computed(()=>commonSections('oath',oaths.map(item=>item[0])).sort((a,b)=>a.heading.localeCompare(b.heading)))
const commonFaithSections=computed(()=>commonSections('faith',faiths).sort((a,b)=>a.heading.localeCompare(b.heading)))
const commonHeadingSets={homeland:new Set(homelands.map(item=>headingKey(item.name))),oath:new Set(oaths.map(item=>headingKey(item[0]))),faith:new Set(faiths.map(item=>headingKey(item)))}
function generalNarrativeSections(documentKey:string){if(documentKey!=='homeland'&&documentKey!=='oath'&&documentKey!=='faith')return[];const excluded=commonHeadingSets[documentKey];return (ruleSourceDocuments[documentKey]?.sections||[]).filter(section=>section.heading!=='Overview'&&!excluded.has(headingKey(section.heading)))}
function visibleNarrativeBlocks(section:RuleSourceSection){return section.blocks.filter(block=>!(block.type==='table'&&singleCellText(block).startsWith('WATCHER’S NOTE')))}
const faithWatcherNote=computed(()=>{for(const section of ruleSourceDocuments.faith.sections){for(const block of section.blocks){const text=singleCellText(block);if(text.startsWith('WATCHER’S NOTE'))return narrativeParts(text).body}}return''})
const oathWatcherNote='If a campaign expects a stronger or more specific personal vow, work with the Watcher to choose or create one. Adventurer is the flexible default Oath when no narrower promise fits the character or campaign yet.'
function narrativeCreatingSection(documentKey:string){const target=documentKey==='homeland'?'CREATING A HOMELAND':documentKey==='oath'?'CREATING AN OATH':'CREATING A FAITH';return sectionByHeading(documentKey,target)}
function narrativeIntroSections(documentKey:string){return generalNarrativeSections(documentKey).filter(section=>!/^CREATING A /i.test(section.heading))}
const weaponQualitySections=computed(()=>ruleSourceDocuments.weapons.sections.map(section=>({...section,blocks:section.blocks.filter(block=>block.type==='table'&&block.rows.some(row=>row.some(cell=>/Quality/i.test(cell))))})).filter(section=>section.blocks.length))
const currentGearItems=computed(()=>catalogGearShopItems)
const shieldNames=new Set(['Sapguard','Sapguard*','Vinegrip','Ironwood Bulwark','IronwoodBulwark'])
function equipmentItemsFor(group:string){return currentGearItems.value.filter(item=>group==='Weapons'?item.category==='Weapon':group==='Armor'?item.category==='Armor & Shield'&&!shieldNames.has(item.name):group==='Shields'?item.category==='Armor & Shield'&&shieldNames.has(item.name):item.shopGroup===group).sort((a,b)=>a.name.localeCompare(b.name))}
const equipmentGroups=['Traveler’s Gear','Field Kits','Consumables','Trinkets','Tools'] as const
function gearCardFields(item:typeof currentGearItems.value[number]){const fields:Array<{label:string;value:string}>=[];if(item.detail&&item.detail!=='—')fields.push({label:'PROFILE',value:item.detail});if(item.effect)fields.push({label:'EFFECT',value:item.effect});return fields}
function sectionParagraphs(section:RuleSourceSection|null){return section?.blocks.flatMap(block=>block.type==='paragraph'?[block.text]:[])||[]}
const makeshiftWeaponsSection=computed(()=>sectionByHeading('weapons','MAKESHIFT WEAPONS'))
const buildingSeluText=computed(()=>{for(const section of ruleSourceDocuments.weapons.sections){for(const block of section.blocks){const text=singleCellText(block);if(/^Selu(?:’s| of )/i.test(text))return text}}return''})
const armorPenaltySection=computed(()=>sectionByHeading('armor-shields','ARMOR PENALTY'))
const breakValueSection=computed(()=>sectionByHeading('weapons','BREAK VALUE'))
const threadpieceSections=computed(()=>['THREADPIECES','TYPES OF THREADPIECES','WASHER PIECES (WP)','NUT PIECES (NP)','SCREW PIECES (SP)','BOLT PIECES (BP)','Standard Exchange Rate','SELLING TREASURE','RESALE & MARKET VALUE'].map(heading=>sectionByHeading('adventuring-gear',heading)).filter((section):section is RuleSourceSection=>Boolean(section)))
const beyondIntroSection=computed(()=>sectionByHeading('beyond-creation','BEYOND CHARACTER CREATION'))
const beyondSpendingSection=computed(()=>sectionByHeading('beyond-creation','SPENDING EXPERIENCE'))
const xpMethodLabels=['Deeds Completed','Spark Alignment','Encounters or Milestones','Watcher Awards']
const xpMethods=computed(()=>sectionParagraphs(beyondIntroSection.value).filter(text=>xpMethodLabels.some(label=>text.toLowerCase().startsWith(label.toLowerCase()+':'))).map(text=>labeledParagraph(text)))
const xpAverageLine=computed(()=>sectionParagraphs(beyondIntroSection.value).find(text=>/Average XP per session/i.test(text))||'')
function spellKeywordBody(text:string,title:string){return text.replace(new RegExp(`^${title.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}\\s*`, 'i'),'').trim()}
function isHealthSection(section:RuleSourceSection,heading:string){return canonicalSlug.value==='health'&&section.heading===heading}
</script>

<template>
  <RulePageLayout
    v-if="page"
    :title="page.title"
    :section="breadcrumbSection"
    :summary="page.summary"
    :parent="layoutParent"
    back-to="/rules"
    back-label="Back to Rules"
    prefer-back-to
    skip-back-prefix="/rules/read/"
    :navigation="ruleNavigation"
  >

        <template v-if="currentCategoryLanding">
          <section class="rule-page-section chapter-landing-page">
            <h2>Contents</h2>
            <div class="chapter-landing-list"><RouterLink v-for="entry in landingEntries" :key="entry.slug" class="chapter-landing-link" :to="`/rules/read/${entry.slug}`"><span><strong>{{ entry.title }}</strong><small>{{ entry.summary }}</small></span><span aria-hidden="true">›</span></RouterLink></div>
          </section>
        </template>

        <template v-else-if="page.slug==='playable-species'">
          <section class="rule-page-section playable-species-reader">
            <h2>Woodlands</h2>
            <p>Choose a Species to open its current lore, Heritage Traits, Cultural Traits, and language.</p>
            <div class="playable-species-link-list"><RouterLink v-for="species in speciesData" :key="species.name" class="list-row" :to="`/rules/read/species-${species.name.toLowerCase()}`"><span class="list-row-copy"><span class="list-row-title">{{ species.name }}</span></span><svg class="row-chevron" viewBox="0 0 24 24" aria-hidden="true"><path d="m9 5 7 7-7 7"/></svg></RouterLink></div>
          </section>
        </template>

        <template v-else-if="currentSpecies">
          <SpeciesRuleSheet :species="currentSpecies" />
        </template>

        <template v-else-if="page.slug==='talents'">
          <section class="rule-page-section-stack talent-rule-page">
            <details v-for="group in talentRuleGroups" :key="group.category" class="organized-rule-category talent-category-panel card-surface">
              <summary><span><h2>{{ group.category }}</h2><small>{{ group.talents.length }} {{ group.talents.length===1?'Talent':'Talents' }}</small></span><span aria-hidden="true">⌄</span></summary>
              <div class="organized-rule-category-body review-box-list">
                <article v-for="talent in group.talents" :key="talent" class="talent-detail-card full-rule-entry" :class="abilityTypes(talentRuleKeywords(talent)).map(abilityTypeClass)">
                  <div class="talent-detail-head"><div><h2>{{ talent }}</h2></div><div class="talent-head-actions"><span v-if="manaCostFromRule(talentRuleText(talent))!==null" class="mana-badge">{{ manaCostFromRule(talentRuleText(talent)) }} Mana</span></div></div>
                  <p v-if="structuredRule(talentRuleText(talent)).intro" class="rule-flavor"><em>{{ structuredRule(talentRuleText(talent)).intro }}</em></p>
                  <div v-if="visibleRuleFields(talentRuleText(talent)).length" class="rule-breakdown-grid"><div v-for="field in visibleRuleFields(talentRuleText(talent))" :key="field.label"><small>{{ field.label }}</small><span>{{ field.value }}</span></div></div>
                  <div class="keyword-pill-row"><span v-for="keyword in abilityFeaturePillKeywords(talentRuleKeywords(talent))" :key="keyword" :class="abilityFeaturePillClass(keyword)">{{ abilityFeaturePillLabel(keyword) }}</span></div>
                </article>
              </div>
            </details>
          </section>
        </template>

        <template v-else-if="currentSpellLore">
          <section class="rule-page-section lore-reader-section">
            <h2>{{ currentSpellLore==='Invocation'?'Invocation Spells':`Lore of ${currentSpellLore}` }}</h2>
            <div class="lore-reader-meta">
              <strong v-if="currentLoreResistance" class="lore-elemental-resistance">Elemental Resistance: {{ currentLoreResistance }}</strong>
              <label v-if="canPreviewLoreAttunement" class="lore-attunement-preview-toggle"><span>Attuned</span><span class="switch"><input v-model="loreAttunedPreview" type="checkbox" /><span></span></span></label>
              <small>{{ currentLoreSpells.length }} spells</small>
            </div>
            <p v-if="loreDescriptions[currentSpellLore]" class="lore-reader-description">{{ loreDescriptions[currentSpellLore] }}</p>
            <div class="review-spell-column">
              <article v-for="spell in currentLoreSpells.filter(isSignatureSpell)" :key="spell" class="spell-detail-card full-rule-entry" :class="spellLoreClass(spell)"><div class="spell-detail-head"><div><h2>{{ spell }}</h2></div><span class="mana-badge">{{ displayedLoreCost(spell) }}</span></div><p v-if="spellRuleDetail(spell)?.flavor" class="rule-flavor"><em>{{ spellRuleDetail(spell)?.flavor }}</em></p><div v-if="visibleRuleFields(spellRuleDetail(spell)?.rules||'').length" class="rule-breakdown-grid"><div v-for="field in visibleRuleFields(spellRuleDetail(spell)?.rules||'')" :key="field.label"><small>{{ field.label }}</small><span>{{ field.value }}</span></div></div><div v-if="spellRuleDetail(spell)?.keywords?.length" class="keyword-pill-row"><span v-for="keyword in abilityFeaturePillKeywords(spellRuleDetail(spell)?.keywords)" :key="keyword" :class="abilityFeaturePillClass(keyword)">{{ abilityFeaturePillLabel(keyword) }}</span></div></article>
              <details v-for="spell in currentLoreSpells.filter(spell=>!isSignatureSpell(spell))" :key="spell" class="organized-rule-category spell-collapsible card-surface" :class="spellLoreClass(spell)"><summary><span><h2>{{ spell }}</h2><small>{{ displayedLoreCost(spell) }}</small></span><span aria-hidden="true">⌄</span></summary><div class="organized-rule-category-body"><p v-if="spellRuleDetail(spell)?.flavor" class="rule-flavor"><em>{{ spellRuleDetail(spell)?.flavor }}</em></p><div v-if="visibleRuleFields(spellRuleDetail(spell)?.rules||'').length" class="rule-breakdown-grid"><div v-for="field in visibleRuleFields(spellRuleDetail(spell)?.rules||'')" :key="field.label"><small>{{ field.label }}</small><span>{{ field.value }}</span></div></div><div v-if="spellRuleDetail(spell)?.keywords?.length" class="keyword-pill-row"><span v-for="keyword in abilityFeaturePillKeywords(spellRuleDetail(spell)?.keywords)" :key="keyword" :class="abilityFeaturePillClass(keyword)">{{ abilityFeaturePillLabel(keyword) }}</span></div></div></details>
            </div>
          </section>
        </template>

        <template v-else-if="page.slug==='combat-abilities-targeting'">
          <section class="combat-targeting-page organized-rule-stack">
            <section class="rule-page-section targeting-intro-card"><h2>Combat Range</h2><p>Abilities and weapons use their listed range to determine which targets or points can be chosen. Any weapon that does not express a range is always considered <strong>Touch</strong>. Touch uses the weapon’s legal reach and otherwise defaults to [1] square.</p><div class="keyword-pill-row targeting-bottom-pills"><span class="keyword-pill">TOUCH</span></div></section>
            <section class="rule-page-section targeting-rule-card"><h2>Range/Thrown</h2><div class="targeting-rule-layout compact"><div><p>A Range/Thrown ability affects a chosen target or point within its listed range rather than creating an area. Use the weapon or Ability’s stated range, line-of-sight, and target restrictions. Thrown weapons use this same targeting structure.</p><div class="keyword-pill-row targeting-bottom-pills"><span class="keyword-pill">RANGE / THROWN</span></div></div></div></section>
            <section v-for="rule in targetingRules" :key="rule.title" class="rule-page-section targeting-rule-card"><h2>{{ rule.title }}</h2><div class="targeting-rule-layout"><div><p>{{ rule.text }}</p><p class="rule-example-copy"><strong>Example:</strong> {{ rule.example }}</p><div class="keyword-pill-row targeting-bottom-pills"><span class="keyword-pill">{{ rule.keyword }}</span></div></div><img :src="rule.image" :alt="`${rule.title} Ability targeting diagram`" /></div></section>
            <section class="rule-page-section targeting-rule-card"><h2>Impassable Collision</h2><div class="targeting-rule-layout compact"><div><p>Impassable terrain stops an Ability’s area unless that Ability explicitly says it can pass through the obstacle. In the diagram, the shaded area shows the portion of the effect that remains legal before the wall; squares behind the blocking terrain are not affected even though they would otherwise fall inside the shape.</p></div><img :src="targetingBlockedImage" alt="Cone Ability area blocked by impassable terrain" /></div></section>
          </section>
        </template>

        <template v-else-if="page.slug==='attacking-defending'">
          <section class="organized-rule-stack attack-defense-page">
            <section class="rule-page-section strike-intro-card"><h2>Attacking &amp; Defending</h2><p>When an attack calls for an opposed Strike, the attacker builds the roll from the Stat named by the action and the defender answers with Ward. Melee Strike uses Brawl, Range Strike uses Aim, and a Magic Strike uses Control. The defender rolls Ward, which is the Hide modifier.</p><p>Roll both sides, apply Conditions and other modifiers, then compare the totals. The attack succeeds only when the attacker finishes higher. A Ward total that equals or exceeds the attack total successfully defends.</p><div class="attack-defense-graphic" role="img" aria-label="Attack total is compared against Ward total. The higher total wins and the defender wins ties."><div class="attack-node"><small>ATTACKER</small><strong>3d10 + Brawl, Aim, or Control</strong><span>+ condition(s)</span></div><b>VS</b><div class="defense-node"><small>DEFENDER</small><strong>3d10 + Ward</strong><span>+ condition(s)</span></div><div class="resolution-node"><small>RESOLUTION</small><strong>Higher attack total hits</strong><span>Ward that ties or beats the attack defends.</span></div></div><RuleFeatureCard title="Tie Goes to the Defender" subtitle="RESOLUTION" tone-class="detail-tone-spark"><p>An attacker finishes with a total of <strong>21</strong>. The defender’s Ward roll also totals <strong>21</strong>. The defender successfully defends because Ward wins the tie.</p></RuleFeatureCard></section>
            <section class="core-attack-reference rule-page-section"><h2>Core Attack Actions</h2><p>These three shared Core Combat Actions use the same canonical cards as the Core Actions rules.</p><div class="core-attack-grid core-attack-list"><CoreActionCard v-for="action in combatAttackCoreActions" :key="action.name" :action="action" /></div></section>
          </section>
        </template>

        <template v-else-if="page.slug==='encounter-rounds'">
          <section class="encounter-rounds-page organized-rule-stack">
            <section v-if="combatEncounterSection" class="rule-page-section encounter-rule-section"><h2>Combat Encounter</h2><p v-for="line in sectionParagraphs(combatEncounterSection)" :key="line">{{ displayText(line) }}</p><div class="encounter-round-flow" role="img" aria-label="Encounter flow from positions through repeating rounds."><span><small>1</small><strong>Set Positions</strong></span><b>→</b><span><small>2</small><strong>Roll Initiative</strong></span><b>→</b><span><small>3</small><strong>Start of Round</strong></span><b>→</b><span><small>4</small><strong>Turns in Order</strong></span><b>→</b><span><small>5</small><strong>End of Round</strong></span></div><div class="square-measurement-graphic" role="img" aria-label="One combat square is approximately one yard, three feet, or one meter."><span><small>GRID</small><strong>1 Square</strong></span><b>=</b><span><small>TABLETOP DISTANCE</small><strong>1 Yard</strong></span><b>≈</b><span><strong>3 Feet</strong></span><b>≈</b><span><strong>1 Meter</strong></span></div></section>
            <section v-if="determiningPositionsSection" class="rule-page-section encounter-rule-section"><h2>Determining Positions</h2><p v-for="line in sectionParagraphs(determiningPositionsSection)" :key="line">{{ displayText(line) }}</p><details v-if="squaresMeasurementsSection" class="organized-rule-category nested-rule-panel card-surface"><summary><span><h3>Squares &amp; Measurements</h3><small>Grid distance and positioning</small></span><span aria-hidden="true">⌄</span></summary><div class="organized-rule-category-body"><p v-for="line in sectionParagraphs(squaresMeasurementsSection)" :key="line">{{ displayText(line) }}</p></div></details></section>
            <section v-if="initiativeSection" class="rule-page-section encounter-rule-section"><h2>Initiative Order</h2><p v-for="line in sectionParagraphs(initiativeSection)" :key="line">{{ displayText(line) }}</p><div class="initiative-roll-graphic"><span><small>ROLL</small><strong>3d10 + Speed + condition(s)</strong></span><b>→</b><span><small>ORDER</small><strong>Highest result acts first</strong></span></div><div class="initiative-order-example"><strong>Example Initiative</strong><ol><li><b>Selu</b><span>27</span></li><li><b>Blight Warrior</b><span>23</span></li><li><b>Nessa</b><span>19</span></li><li class="watcher-position"><b>Watcher Event</b><span>16</span></li><li><b>Brann</b><span>13</span></li></ol></div></section>
            <section v-if="roundsTurnsSection" class="rule-page-section encounter-rule-section"><h2>Rounds &amp; Turns</h2><p v-for="line in sectionParagraphs(roundsTurnsSection)" :key="line">{{ displayText(line) }}</p><details v-if="manaSection" class="organized-rule-category nested-rule-panel card-surface"><summary><span><h3>Mana</h3><small>Start-of-round recovery</small></span><span aria-hidden="true">⌄</span></summary><div class="organized-rule-category-body"><p v-for="line in sectionParagraphs(manaSection)" :key="line">{{ displayText(line) }}</p><p>Before Magic Regen is restored, each character may resolve one eligible <strong>Instinct Core Action</strong> during Start of Round.</p><div class="core-action-grid instinct-action-grid"><CoreActionCard v-for="action in instinctCoreActions" :key="action.name" :action="action" /></div></div></details></section>
            <section v-if="takingTurnSection" class="rule-page-section encounter-rule-section"><h2>Taking Your Turn</h2><p v-for="line in sectionParagraphs(takingTurnSection)" :key="line">{{ displayText(line) }}</p><div class="rule-link-buttons"><RouterLink class="secondary-button" to="/rules/read/abilities">Core Actions</RouterLink><RouterLink class="secondary-button" to="/rules/read/attacking-defending">Attacking &amp; Defending</RouterLink></div></section>
            <section class="rule-page-section encounter-rule-section"><h2>End of Round</h2><p>After every character has completed their turn, resolve effects that explicitly occur at the end of the round in Initiative Order. Species Traits with an end-of-round Instinct Trigger can resolve here when their requirements are met.</p><div class="instinct-trait-example-grid"><RuleFeatureCard v-for="item in instinctTraitExamples" :key="`${item.species}-${item.trait.name}`" :title="item.trait.name" :subtitle="`${item.species} · INSTINCT`" tone-class="type-instinct"><p>{{ structuredRule(item.trait.text).intro }}</p><div v-for="field in visibleRuleFields(item.trait.text)" :key="field.label" class="mini-rule-field"><small>{{ field.label }}</small><span>{{ field.value }}</span></div></RuleFeatureCard></div></section>
          </section>
        </template>

        <template v-else-if="page.slug==='encounters-threat-level'">
          <section class="external-rule-page rule-page-section-stack"><section class="rule-page-section"><h2>Threat Level</h2><p>Threat Level is Brambleheart’s current framework for comparing the danger of creatures, groups, and encounters. Brambleheart uses five Attributes. Older Encounter Rating guidance based on six Attributes is deprecated and should not be used.</p></section><section class="rule-page-section"><h2>Current Guidance</h2><p>Use Threat Level as a comparative encounter-design value for now. The exact calculation, party scaling, encounter bands, and Watcher-facing balancing procedure will be finalized when The Watcher section receives its dedicated rules pass.</p></section><section class="rule-page-section"><h2>Design Status</h2><p>This page intentionally provides only the current framework. It does not invent a replacement formula before the full Watcher encounter system is defined.</p></section></section>
        </template>

        <template v-else-if="page.slug==='monsters' || page.slug==='critters'">
          <section class="monster-index-stack rule-page-section-stack"><section class="rule-page-section monster-source-intro"><h2>{{ page.slug==='critters'?'Critters & Companions':'Monsters of Anthro Mundas' }}</h2><p>The creature reference is organized first by parent category and then, for monsters with variants, by their monster type.</p></section><template v-for="group in monsterGroups" :key="group.category.name"><section v-if="group.monsters.length && (page.slug==='monsters'?group.category.name!=='Companions':group.category.name==='Companions')" class="rule-page-section monster-category-section"><h2>{{ group.category.name }}</h2><p>{{ group.category.summary }}</p><div class="monster-family-stack"><template v-for="family in group.families" :key="family.parent.name"><details v-if="family.children.length" class="monster-family-box"><summary><span><strong>{{ family.parent.name }}</strong><small>{{ family.children.length }} {{ family.children.length===1?'variant':'variants' }}</small></span><span aria-hidden="true">⌄</span></summary><div class="monster-link-grid"><RouterLink :to="`/rules/read/${monsterSlug(family.parent.name)}`"><strong>{{ family.parent.name }}</strong></RouterLink><RouterLink v-for="monster in family.children" :key="monster.name" :to="`/rules/read/${monsterSlug(monster.name)}`"><strong>{{ monster.name }}</strong></RouterLink></div></details><RouterLink v-else class="monster-family-link" :to="`/rules/read/${monsterSlug(family.parent.name)}`"><strong>{{ family.parent.name }}</strong></RouterLink></template></div></section></template><section class="rule-page-section source-link-section"><h2>Source Reference</h2><a class="secondary-button external-source-link" :href="WOODLANDS_MONSTERS_URL" target="_blank" rel="noopener noreferrer">Open Source Monster Reference</a></section></section>
        </template>

        <template v-else-if="currentMonster">
          <section class="external-monster-page"><section class="rule-page-section monster-profile-section"><h2>{{ currentMonster.name }}</h2><p class="rule-section-count">{{ currentMonster.category }}<template v-if="currentMonster.group"> · {{ currentMonster.group }}</template></p><p>{{ currentMonster.summary }}</p><p class="source-status-note">This creature is listed as an individual entry in the external Woodlands monster reference. The current crawl exposes its index placement but not a reliable complete stat block, so Brambleheart does not invent missing statistics.</p><a class="secondary-button external-source-link" :href="WOODLANDS_MONSTERS_URL" target="_blank" rel="noopener noreferrer">Open Source Monster Reference</a></section></section>
        </template>

        <template v-else-if="page.slug==='sparks-deeds'">
          <section class="deeds-rule-page organized-rule-stack">
            <section class="rule-page-section spark-rule-card"><h2>What is a Spark?</h2><template v-for="section in sparkWhatSections.filter(item=>item.heading==='WHAT IS A SPARK?')" :key="section.heading"><p v-for="(block,index) in section.blocks" :key="index"><template v-if="block.type==='paragraph'"><strong v-if="labeledParagraph(block.text).label" class="rule-inline-label">{{ labeledParagraph(block.text).label }}:</strong> {{ labeledParagraph(block.text).body }}</template></p></template><template v-for="section in sparkWhatSections.filter(item=>item.heading==='KEYWORD LIBRARY')" :key="section.heading"><p v-for="(block,index) in section.blocks.filter(block=>block.type==='paragraph'&&!/^Creating Your Own Spark|^If none|^Follow this quick|^Name your Spark|^Choose two|^Write a short credo|^“|^Share your spark|^Deed Interaction:/i.test(block.type==='paragraph'?block.text:''))" :key="index"><template v-if="block.type==='paragraph'"><strong v-if="/^Keywords:/i.test(block.text)">Keywords:</strong><span>{{ displayText(block.text).replace(/^Keywords:\s*/i,'') }}</span></template></p></template></section>
            <details class="organized-rule-category card-surface premade-sparks-menu"><summary><span><h2>Premade Sparks</h2><small>{{ premadeSparkCards.length }} Sparks · A–Z</small></span><span aria-hidden="true">⌄</span></summary><div class="organized-rule-category-body narrative-card-grid premade-spark-grid"><RuleFeatureCard v-for="spark in premadeSparkCards" :key="spark.name" :title="spark.name" subtitle="SPARK" tone-class="detail-tone-spark"><p v-if="spark.description">{{ spark.description }}</p><template #footer><div class="keyword-pill-row"><span v-for="keyword in spark.keywords" :key="keyword" class="keyword-pill">{{ keyword }}</span></div></template></RuleFeatureCard></div></details>
            <p class="spark-deed-interaction"><strong>Deed Interaction:</strong> All Sparks — premade or custom — trigger their XP bonus when a completed Deed aligns with one or both of their keywords.</p>
            <div class="spark-example-text-list"><p v-for="spark in sparkExamples" :key="spark.name"><strong>{{ spark.name }}:</strong> {{ spark.description }} <span><strong>Keywords:</strong> {{ spark.keywords.join(', ') }}</span></p></div>
            <section class="rule-page-section spark-create-section"><h2>Creating Your Own Spark</h2><div class="rule-subsection-panel"><h3>Build a Custom Spark</h3><ol><li>Name your Spark with a short title that captures the personality.</li><li>Choose two keywords from the current Keyword Library.</li><li>Write a short credo that describes how the character tends to approach the world.</li><li>Share it with the Watcher so the keywords clearly interact with Deeds.</li></ol></div></section>
            <section class="rule-page-section deed-intro-box"><h2>Deeds</h2><div class="deed-structure-copy"><p v-for="line in deedIntro" :key="line"><strong v-if="labeledParagraph(line).label" class="rule-inline-label">{{ labeledParagraph(line).label }}:</strong>{{ labeledParagraph(line).body }}</p></div></section>
            <details class="organized-rule-category card-surface deed-cards-menu"><summary><span><h2>All Deeds</h2><small>{{ deedEntriesSorted.length }} Deeds · d100</small></span><span aria-hidden="true">⌄</span></summary><div class="organized-rule-category-body deed-rule-list"><RuleFeatureCard v-for="deed in deedEntriesSorted" :key="deed.name" :title="deed.name" subtitle="DEED" :badge="deed.reward" tone-class="detail-tone-deed" :fields="[{label:'OBJECTIVE',value:deed.objective}]"><p v-if="deed.flavor">{{ deed.flavor }}</p><template #footer><div class="deed-card-footer"><div class="keyword-pill-row"><span v-for="keyword in deed.keywords" :key="keyword" class="keyword-pill">{{ keyword }}</span></div><span class="deed-roll-result" :aria-label="`d100 result ${deed.rollRange}`">{{ deed.rollRange }}</span></div></template></RuleFeatureCard></div></details>
          </section>
        </template>

        <template v-else-if="page.slug==='homeland'||page.slug==='oath'||page.slug==='faith'">
          <section class="rule-page-section-stack narrative-rule-page">
            <section v-for="(section,sectionIndex) in narrativeIntroSections(page.slug)" :key="section.heading" class="rule-page-section narrative-rule-section"><h2>{{ displayText(section.heading) }}</h2><template v-for="(block,index) in visibleNarrativeBlocks(section)" :key="index"><p v-if="block.type==='paragraph'"><strong v-if="labeledParagraph(block.text).label" class="rule-inline-label">{{ labeledParagraph(block.text).label }}:</strong> {{ labeledParagraph(block.text).body }}</p><div v-else class="rule-table-wrap"><table class="rule-source-table"><tbody><tr v-for="(row,rowIndex) in block.rows" :key="rowIndex"><td v-for="(cell,cellIndex) in row" :key="cellIndex">{{ displayText(cell) }}</td></tr></tbody></table></div></template><div v-if="sectionIndex===0&&narrativeCreatingSection(page.slug)" class="rule-subsection-panel narrative-creating-panel"><h3>{{ narrativeCreatingSection(page.slug)?.heading }}</h3><template v-for="(block,index) in visibleNarrativeBlocks(narrativeCreatingSection(page.slug)!)" :key="index"><p v-if="block.type==='paragraph'">{{ displayText(block.text) }}</p><div v-else class="rule-table-wrap"><table class="rule-source-table"><tbody><tr v-for="(row,rowIndex) in block.rows" :key="rowIndex"><td v-for="(cell,cellIndex) in row" :key="cellIndex">{{ displayText(cell) }}</td></tr></tbody></table></div></template></div></section>
            <details class="organized-rule-category card-surface common-narrative-section"><summary><span><h2>{{ page.slug==='homeland'?'Common Homelands':page.slug==='oath'?'Common Oaths':'Common Faiths' }}</h2><small>{{ page.slug==='homeland'?commonHomelandSections.length:page.slug==='oath'?commonOathSections.length:commonFaithSections.length }} entries · A–Z</small></span><span aria-hidden="true">⌄</span></summary><div class="organized-rule-category-body narrative-card-grid" :class="{'two-column-oaths':page.slug==='oath'}"><RuleFeatureCard v-for="section in (page.slug==='homeland'?commonHomelandSections:page.slug==='oath'?commonOathSections:commonFaithSections)" :key="section.heading" :title="displayText(section.heading)" :tone-class="`detail-tone-${page.slug}`"><template v-for="(block,index) in visibleNarrativeBlocks(section)" :key="index"><p v-if="block.type==='paragraph'"><strong v-if="labeledParagraph(block.text).label" class="rule-inline-label">{{ labeledParagraph(block.text).label }}:</strong> {{ labeledParagraph(block.text).body }}</p><div v-else class="rule-table-wrap"><table class="rule-source-table"><tbody><tr v-for="(row,rowIndex) in block.rows" :key="rowIndex"><td v-for="(cell,cellIndex) in row" :key="cellIndex">{{ displayText(cell) }}</td></tr></tbody></table></div></template></RuleFeatureCard></div></details>
            <aside v-if="page.slug==='faith'&&faithWatcherNote" class="rule-narrative-note watcher-note-panel"><strong>WATCHER’S NOTE</strong><p>{{ faithWatcherNote }}</p></aside>
            <aside v-if="page.slug==='oath'" class="rule-narrative-note watcher-note-panel"><strong>WATCHER’S NOTE</strong><p>{{ oathWatcherNote }}</p></aside>
          </section>
        </template>

        <template v-else-if="page.slug==='adventuring-gear'">
          <section class="rule-page-section-stack equipment-rules-organized">
            <section class="rule-page-section equipment-rule-section"><h2>Weapons</h2><div class="equipment-item-grid"><RuleFeatureCard v-for="item in equipmentItemsFor('Weapons')" :key="item.name" :title="item.name" :badge="item.costText" tone-class="detail-tone-equipment" :fields="gearCardFields(item)"><p v-if="item.description">{{ item.description }}</p></RuleFeatureCard></div><details v-if="makeshiftWeaponsSection" class="organized-rule-category nested-rule-panel card-surface"><summary><span><h3>Makeshift Weapons</h3><small>Improvised weapon rules</small></span><span aria-hidden="true">⌄</span></summary><div class="organized-rule-category-body"><p v-for="line in sectionParagraphs(makeshiftWeaponsSection)" :key="line">{{ displayText(line) }}</p></div></details><RuleFeatureCard v-if="buildingSeluText" title="Building Selu" subtitle="WORKED EXAMPLE" tone-class="detail-tone-equipment"><p>{{ buildingSeluText.replace(/^Selu(?:’s| of the Wandering Reeds)?\s*/i,'Selu ') }}</p></RuleFeatureCard></section>
            <section class="rule-page-section equipment-rule-section"><h2>Weapon Qualities</h2><div class="equipment-source-stack"><section v-for="section in weaponQualitySections" :key="section.heading" class="equipment-source-section"><template v-for="(block,index) in section.blocks" :key="index"><div v-if="block.type==='table'" class="rule-table-wrap"><table class="rule-source-table"><tbody><tr v-for="(row,rowIndex) in block.rows" :key="rowIndex"><td v-for="(cell,cellIndex) in row" :key="cellIndex">{{ displayText(cell) }}</td></tr></tbody></table></div></template></section></div></section>
            <section class="rule-page-section equipment-rule-section"><h2>Armor &amp; Shields</h2><details class="organized-rule-category card-surface equipment-category-panel"><summary><span><h3>Armor</h3><small>{{ equipmentItemsFor('Armor').length }} items</small></span><span aria-hidden="true">⌄</span></summary><div class="organized-rule-category-body equipment-item-grid"><RuleFeatureCard v-for="item in equipmentItemsFor('Armor')" :key="item.name" :title="item.name" :badge="item.costText" tone-class="detail-tone-equipment" :fields="gearCardFields(item)" /></div></details><details class="organized-rule-category card-surface equipment-category-panel"><summary><span><h3>Shields</h3><small>{{ equipmentItemsFor('Shields').length }} items</small></span><span aria-hidden="true">⌄</span></summary><div class="organized-rule-category-body equipment-item-grid"><RuleFeatureCard v-for="item in equipmentItemsFor('Shields')" :key="item.name" :title="item.name" :badge="item.costText" tone-class="detail-tone-equipment" :fields="gearCardFields(item)" /></div></details><details v-if="armorPenaltySection" class="organized-rule-category nested-rule-panel card-surface"><summary><span><h3>Armor Penalty</h3><small>Movement and casting restrictions</small></span><span aria-hidden="true">⌄</span></summary><div class="organized-rule-category-body"><p v-for="line in sectionParagraphs(armorPenaltySection)" :key="line">{{ displayText(line) }}</p></div></details><details v-if="breakValueSection" class="organized-rule-category nested-rule-panel card-surface"><summary><span><h3>Break Value</h3><small>Equipment damage</small></span><span aria-hidden="true">⌄</span></summary><div class="organized-rule-category-body"><p v-for="line in sectionParagraphs(breakValueSection)" :key="line">{{ displayText(line) }}</p></div></details></section>
            <section class="rule-page-section equipment-rule-section"><h2>Threadpieces</h2><template v-for="section in threadpieceSections" :key="section.heading"><h3 v-if="!['THREADPIECES','Standard Exchange Rate'].includes(section.heading)">{{ displayText(section.heading) }}</h3><template v-for="(block,index) in section.blocks" :key="index"><p v-if="block.type==='paragraph'"><strong v-if="/^Types of Threadpeices:/i.test(block.text)">Types of Threadpeices:</strong> {{ displayText(block.text).replace(/^Types of Threadpeices:\s*/i,'') }}</p><div v-else class="rule-table-wrap"><table class="rule-source-table"><tbody><tr v-for="(row,rowIndex) in block.rows" :key="rowIndex"><td v-for="(cell,cellIndex) in row" :key="cellIndex">{{ displayText(cell) }}</td></tr></tbody></table></div></template><ThreadpieceExchange v-if="section.heading==='Standard Exchange Rate'" :start-sp="30" /></template></section>
            <details v-for="group in equipmentGroups" :key="group" class="organized-rule-category card-surface equipment-category-panel"><summary><span><h2>{{ group }}</h2><small>{{ equipmentItemsFor(group).length }} items</small></span><span aria-hidden="true">⌄</span></summary><div class="organized-rule-category-body equipment-item-grid"><RuleFeatureCard v-for="item in equipmentItemsFor(group)" :key="item.name" :title="item.name" :badge="item.costText" tone-class="detail-tone-equipment" :fields="gearCardFields(item)"><p v-if="item.description">{{ item.description }}</p></RuleFeatureCard></div></details>
          </section>
        </template>

        <template v-else-if="page.slug==='beyond-character-creation'">
          <section class="rule-page-section-stack beyond-creation-page"><section class="rule-page-section"><h2>Beyond Character Creation</h2><p v-for="line in sectionParagraphs(beyondIntroSection).filter(line=>!xpMethods.some(item=>line===`${item.label}: ${item.body}`)&&line!==xpAverageLine)" :key="line">{{ displayText(line) }}</p><div class="xp-method-grid"><RuleFeatureCard v-for="method in xpMethods" :key="method.label" :title="method.label" subtitle="EARNING EXPERIENCE" tone-class="detail-tone-spark"><p>{{ method.body }}</p></RuleFeatureCard></div><p v-if="xpAverageLine" class="xp-average-line">{{ displayText(xpAverageLine) }}</p></section><section v-if="beyondSpendingSection" class="rule-page-section"><h2>Spending Experience</h2><template v-for="(block,index) in beyondSpendingSection.blocks" :key="index"><p v-if="block.type==='paragraph'"><strong v-if="/^(Attribute Rank Increase|Skill Rank Increase|Magic Level Increase):/i.test(block.text)">{{ block.text.split(':')[0] }}:</strong><span>{{ /^(Attribute Rank Increase|Skill Rank Increase|Magic Level Increase):/i.test(block.text)?block.text.slice(block.text.indexOf(':')+1):displayText(block.text) }}</span></p></template><details class="organized-rule-category nested-rule-panel card-surface"><summary><span><h3>Advancement Cost Examples</h3><small>Sample tables</small></span><span aria-hidden="true">⌄</span></summary><div class="organized-rule-category-body"><template v-for="(block,index) in beyondSpendingSection.blocks" :key="index"><div v-if="block.type==='table'" class="rule-table-wrap"><table class="rule-source-table"><tbody><tr v-for="(row,rowIndex) in block.rows" :key="rowIndex"><td v-for="(cell,cellIndex) in row" :key="cellIndex">{{ displayText(cell) }}</td></tr></tbody></table></div></template></div></details></section></section>
        </template>

        <template v-else-if="page.slug==='faq'"><section class="rule-page-section-stack faq-reader"><article v-for="item in quickFaq" :key="item.q" class="rule-page-section faq-row"><h2>{{ item.q }}</h2><p>{{ item.a }}</p></article></section></template>
        <template v-else-if="page.slug==='changes-updates'"><section class="changes-reader rule-page-section-stack"><article class="rule-page-section changes-reader-intro"><h2>Changes &amp; Updates</h2><p>Game Updates record changes to Brambleheart rules. The newest update is expanded; earlier updates remain available below in reverse chronological order.</p></article><GameUpdateList /></section></template>

        <template v-else>
          <section v-if="page.note" class="rule-page-section rule-source-note"><h2>Source Note</h2><p>{{ displayText(page.note) }}</p></section>
          <section v-if="sourceSections.length" class="rule-page-section-stack">
            <article v-for="(entry,index) in sourceSections" :key="`${entry.document}-${entry.section.heading}-${index}`" class="rule-page-section source-rule-section" :class="{'example-source-card':isExampleHeading(entry.section.heading),'creation-step-section':isCharacterCreationStep(entry.section),'creation-path-step':creationGraphicStep(entry.section,6)}">
              <header v-if="isCharacterCreationStep(entry.section)" class="creation-step-heading"><span>{{ characterCreationStepParts(entry.section)?.number }}</span><div><h2>{{ characterCreationStepParts(entry.section)?.title }}</h2></div></header>
              <h2 v-else-if="entry.section.heading!=='Overview'">{{ displayText(entry.section.heading) }}</h2>
              <div v-if="loreIndex>=0&&index===0" class="rule-page-banner-placeholder anthro-rule-banner" :class="{empty:!currentBanner}" :style="currentBanner?{backgroundImage:`url(${currentBanner})`}:undefined" aria-hidden="true"></div>
              <template v-for="(block,blockIndex) in entry.section.blocks" :key="blockIndex">
                <div v-if="keywordPartsForBlock(block).length" class="keyword-pill-row"><span v-for="keyword in keywordPartsForBlock(block)" :key="keyword" class="keyword-pill">{{ displayText(keyword) }}</span></div>
                <template v-else-if="block.type==='paragraph'&&!(page.slug==='spell-types-targeting'&&entry.section.heading==='SPELL KEYWORDS')"><div v-if="isDialogue(block.text)" class="dialogue-example-box"><p v-for="part in dialogueParts(block.text)" :key="`${part.actor}-${part.text}`"><strong>{{ part.actor }}:</strong> <span>{{ displayText(part.text) }}</span></p></div><div v-else-if="bulletParts(block.text).length" class="rule-bullet-block"><p>{{ bulletParts(block.text)[0] }}</p><ul><li v-for="part in bulletParts(block.text).slice(1)" :key="part"><template v-for="(segment,segmentIndex) in optionalTextParts(part)" :key="segmentIndex"><em v-if="segment.optional">{{ segment.text }}</em><span v-else>{{ segment.text }}</span></template></li></ul></div><p v-else :class="{'example-copy':isExampleHeading(entry.section.heading)}"><strong v-if="labeledParagraph(block.text).label" class="rule-inline-label">{{ labeledParagraph(block.text).label }}:</strong><template v-for="(part,partIndex) in bracketParts(labeledParagraph(block.text).body)" :key="partIndex"><strong v-if="part.bold" class="bracket-number">{{ part.text }}</strong><span v-else>{{ part.text }}</span></template></p></template>
                <section v-else-if="isCharacterCreationAttributeTable(entry.section,block)" class="creation-attribute-demo"><header><strong>Spend 5 Points</strong><span>{{ creationAttributePointsRemaining }} points remaining</span></header><div class="creation-attribute-list"><article v-for="attribute in attributes" :key="attribute.id" class="creation-attribute-row" :class="`attribute-${attribute.id}`"><div class="creation-attribute-copy"><h3>{{ attribute.name }}</h3><p>{{ attribute.description }}</p><div class="creation-secondary-stats"><span v-for="secondary in creationAttributeSecondary(attribute.id)" :key="secondary.label"><small>{{ secondary.label }}</small><strong>{{ secondary.value }}</strong></span></div></div><div class="creation-attribute-controls"><div class="creation-rank-summary"><span><small>Rank</small><strong>{{ creationAttributeRanks[attribute.id] }}</strong></span><span><small>Modifier</small><strong>+{{ creationAttributeModifier(attribute.id) }}</strong></span></div><div class="creation-rank-stepper"><button type="button" :disabled="creationAttributeRanks[attribute.id]<=1" :aria-label="`Decrease ${attribute.name}`" @click="adjustCreationAttribute(attribute.id,-1)">−</button><strong>{{ creationAttributeRanks[attribute.id] }}</strong><button type="button" :disabled="creationAttributeRanks[attribute.id]>=3||creationAttributePointsRemaining<=0" :aria-label="`Increase ${attribute.name}`" @click="adjustCreationAttribute(attribute.id,1)">+</button></div></div></article></div><small class="creation-demo-note">Rules-reader example only. These values reset when you leave this page or reload.</small></section>
                <div v-else-if="block.type==='table'&&block.rows.length===1&&block.rows[0].length===1&&isDialogue(block.rows[0][0])" class="dialogue-example-box"><p v-for="part in dialogueParts(block.rows[0][0])" :key="`${part.actor}-${part.text}`"><strong>{{ part.actor }}:</strong> <span>{{ displayText(part.text) }}</span></p></div>
                <article v-else-if="isBuildingSeluTable(block)" class="creation-example rule-selu-example"><strong>Building Selu:</strong> <span>{{ singleCellText(block).replace(/^Selu(?:’s| of the Wandering Reeds)?\s*/i,'Selu ') }}</span></article>
                <article v-else-if="skillTreeName(block)" class="skill-tree-card" :class="`skill-tree-${skillTreeTone(skillTreeName(block))}`"><header><h3>{{ skillTreeName(block).replace(/\s+Skill Tree$/i,' - Skill Tree') }}</h3><div class="skill-tree-column-headings"><small>Skill</small><small>Description</small><small>Example</small></div></header><div class="skill-tree-list"><div v-for="(row,rowIndex) in skillTreeRows(block)" :key="rowIndex"><strong>{{ displayText(row[0]||'') }}</strong><span>{{ displayText(row[1]||'') }}</span><small>{{ displayText(row[2]||'') }}</small></div></div></article>
                <article v-else-if="singleCellText(block)&&isLongNarrativeHeading(singleCellText(block))" class="rule-narrative-note"><strong>{{ narrativeParts(singleCellText(block)).title }}</strong><p>{{ narrativeParts(singleCellText(block)).body }}</p></article>
                <h3 v-else-if="singleCellText(block)" class="source-table-title">{{ singleCellText(block) }}</h3>
                <div v-else-if="equipmentTableRows(block).length" class="equipment-rule-card-grid"><article v-for="item in equipmentTableRows(block)" :key="`${item.name}-${blockIndex}`" class="equipment-rule-card detail-tone-equipment"><header><strong>{{ item.name }}</strong></header><div><span v-for="field in item.fields" :key="field.label"><small>{{ field.label }}</small><template v-for="(part,partIndex) in bracketParts(field.value)" :key="partIndex"><strong v-if="part.bold" class="bracket-number">{{ part.text }}</strong><b v-else>{{ part.text }}</b></template></span></div></article></div>
                <div v-else-if="block.type==='table'" class="rule-table-wrap"><table class="rule-source-table"><tbody><tr v-for="(row,rowIndex) in block.rows" :key="rowIndex"><td v-for="(cell,cellIndex) in row" :key="cellIndex"><template v-for="(part,partIndex) in bracketParts(cell)" :key="partIndex"><strong v-if="part.bold" class="bracket-number">{{ part.text }}</strong><span v-else>{{ part.text }}</span></template></td></tr></tbody></table></div>
              </template>
              <div v-if="page.slug==='spell-types-targeting'&&entry.section.heading==='SPELL KEYWORDS'" class="spell-keyword-card-grid"><RuleFeatureCard v-for="item in spellKeywordCards" :key="item.title" :title="item.title" subtitle="SPELL KEYWORD" tone-class="type-magic"><p>{{ spellKeywordBody(item.text,item.title) }}</p></RuleFeatureCard></div>
              <template v-if="page.slug==='spell-types-targeting'&&entry.section.heading==='CASTING SPELLS'"><RuleFeatureCard title="Range Spell" subtitle="MAGIC STRIKE" tone-class="type-magic" :fields="[{label:'TO HIT',value:'(3d10) + Control + condition(s) vs. (3d10) + Ward + condition(s)'},{label:'RESULT',value:'On a successful Strike, resolve the Spell’s printed damage and effects.'}]" /><CoreActionCard class="renew-heart-reference" :action="renewTheHeartAction" /></template>
              <aside v-if="page.slug==='spell-types-targeting'&&entry.section.heading==='SPELL RANGE'" class="rule-cross-reference spell-range-targeting-reference"><strong>Targeting</strong><p>For battlefield areas and shaped effects, use the shared Combat Targeting rules.</p><RouterLink class="secondary-button compact-action" to="/rules/read/combat-abilities-targeting">Targeting</RouterLink></aside>
              <RuleFeatureCard v-if="page.slug==='spell-types-targeting'&&entry.section.heading==='SPELL RANGE'" title="Reading Range & Area" subtitle="WORKED SPELL EXAMPLE" tone-class="type-magic" :fields="[{label:'CASTING RANGE',value:'Choose a point within [8] squares.'},{label:'AREA',value:'ORB[5] covers a 5 × 5 area from that chosen point.'}]"><p>The casting range tells you how far away the origin point may be. The area tells you how much battlefield space the Spell covers from that point.</p></RuleFeatureCard>
              <div v-if="page.slug==='magical-levels'&&entry.section.heading==='MAGIC POWER'" class="magic-resource-grid"><RuleFeatureCard title="Mana Pool" subtitle="MAXIMUM MANA" tone-class="type-magic" :fields="[{label:'FORMULA',value:'Magic Level + Spirit'}]"><p>Your Mana Pool is the most Mana you can normally hold.</p></RuleFeatureCard><RuleFeatureCard title="Magic Regen" subtitle="START OF ROUND" tone-class="type-instinct" :fields="[{label:'FORMULA',value:'Heart'}]"><p>Restore this much Mana during the Start of Round sequence, after applicable modifiers.</p></RuleFeatureCard></div>
              <details v-if="page.slug==='magical-levels'&&entry.section.heading==='LORE ATTUNEMENT'" class="organized-rule-category nested-rule-panel card-surface" open><summary><span><h3>Signature</h3><small>Attunement spell</small></span><span aria-hidden="true">⌄</span></summary><div class="organized-rule-category-body"><p v-for="line in sectionParagraphs(sectionByHeading('winds-of-magic','SIGNATURE'))" :key="line">{{ displayText(line) }}</p><article v-if="signatureExample" class="spell-detail-card full-rule-entry spell-lore-flames"><div class="spell-detail-head"><div><h3>{{ signatureExampleName }}</h3></div><span class="mana-badge">SIGNATURE</span></div><p v-if="signatureExample.flavor" class="rule-flavor"><em>{{ signatureExample.flavor }}</em></p><div class="rule-breakdown-grid"><div v-for="field in visibleRuleFields(signatureExample.rules)" :key="field.label"><small>{{ field.label }}</small><span>{{ field.value }}</span></div></div></article></div></details>
              <div v-if="creationGraphicStep(entry.section,1)" class="creation-reference-graphic creation-trait-graphic"><RuleFeatureCard title="Heritage Traits" subtitle="INHERITED" tone-class="detail-tone-heritage"><p>Innate features of your chosen Species.</p></RuleFeatureCard><RuleFeatureCard title="Cultural Traits" subtitle="LEARNED" tone-class="detail-tone-culture"><p>Learned traditions that may be exchanged during Character Creation.</p></RuleFeatureCard></div>
              <div v-if="creationGraphicStep(entry.section,2)" class="creation-reference-graphic creation-example-pair"><RuleFeatureCard v-if="creationSparkExample" :title="creationSparkExample.name" subtitle="SPARK" tone-class="detail-tone-spark"><p>{{ creationSparkExample.description }}</p><template #footer><div class="keyword-pill-row"><span v-for="keyword in creationSparkExample.keywords" :key="keyword" class="keyword-pill">{{ keyword }}</span></div></template></RuleFeatureCard><RuleFeatureCard v-if="creationDeedExample" :title="creationDeedExample.name" subtitle="DEED" tone-class="detail-tone-deed" :fields="[{label:'OBJECTIVE',value:creationDeedExample.objective},{label:'REWARD',value:creationDeedExample.reward}]"><template #footer><div class="keyword-pill-row"><span v-for="keyword in creationDeedExample.keywords" :key="keyword" class="keyword-pill">{{ keyword }}</span></div></template></RuleFeatureCard></div>
              <div v-if="creationGraphicStep(entry.section,3)" class="creation-reference-graphic creation-single-example"><RuleFeatureCard :title="creationHomelandExample.name" subtitle="HOMELAND" tone-class="detail-tone-homeland"><p>Begins with two Skills at Rank 1.</p><template #footer><div class="keyword-pill-row"><span v-for="skill in creationHomelandExample.skills" :key="skill" class="keyword-pill">{{ skill }} · Rank 1</span></div></template></RuleFeatureCard></div>
              <div v-if="creationGraphicStep(entry.section,4)" class="creation-reference-graphic creation-example-pair"><RuleFeatureCard :title="creationFaithExample" subtitle="FAITH" tone-class="detail-tone-faith"><p>A belief tradition that frames meaning, ritual, and belonging.</p></RuleFeatureCard><RuleFeatureCard :title="creationOathExample[0]" subtitle="OATH" tone-class="detail-tone-oath"><p>{{ creationOathExample[1] }}</p></RuleFeatureCard></div>
              <div v-if="creationGraphicStep(entry.section,6)" class="creation-path-reference"><div class="path-choice-grid"><article v-for="path in startingPathOptions" :key="path.id" class="path-choice-card creation-path-card" :class="`path-${path.id}`" aria-disabled="true"><span class="path-choice-kicker">{{ path.kicker }}</span><strong class="path-choice-title">{{ path.title }}</strong><p>{{ path.description }}</p></article></div></div>
              <div v-if="creationGraphicStep(entry.section,7)" class="creation-equipment-graphic"><RouterLink class="secondary-button equipment-reference-link" to="/rules/read/adventuring-gear">Equipment &amp; Gear</RouterLink><ThreadpieceExchange :start-sp="creationStartingWealthSp" /></div>
              <aside v-if="creationGraphicStep(entry.section,8)" class="rule-narrative-note watcher-note-panel"><strong>WATCHER’S NOTE</strong><p>Some campaigns may require character details that are optional in the core rules, or may ask for additional information that ties a hero to the campaign. Always check with your Watcher before play to confirm which character details are required at your table.</p></aside>
              <div v-if="isToDamageSection(entry.section)" class="damage-stat-grid"><RuleFeatureCard title="Melee Damage" subtitle="SECONDARY STAT" tone-class="type-touch" :fields="[{label:'ADDITION',value:'Fury (Might Rank)'}]" /><RuleFeatureCard title="Range Damage" subtitle="SECONDARY STAT" tone-class="type-shoot" :fields="[{label:'ADDITION',value:'Accuracy (Agility Rank)'}]" /><RuleFeatureCard title="Spell Damage" subtitle="SECONDARY STAT" tone-class="type-magic" :fields="[{label:'ADDITION',value:'Heart (Bravery Rank)'}]" /></div>
              <template v-if="isDamageCategorySection(entry.section)"><div class="damage-category-graphic" role="img" aria-label="Standard, Direct, and Lethal damage categories, plus the On-Going recurring-damage qualifier."><article><small>STANDARD</small><strong>Damage − Full Guts</strong><span>Use all applicable Guts.</span></article><article><small>DIRECT</small><strong>Damage − Half Guts</strong><span>Round Guts up; minimum [1].</span></article><article><small>LETHAL</small><strong>Damage − 0 Guts</strong><span>Lethal bypasses Guts.</span></article><article><small>ON-GOING</small><strong>Recurring Qualifier</strong><span>Keeps its stated category and gains no normal damage additions.</span></article></div><aside class="damage-heart-callout"><strong>SPELL HEART DAMAGE</strong><p>{{ SPELL_HEART_DAMAGE_RULE }}</p></aside></template>
              <div v-if="isToSoakSection(entry.section)" class="damage-formula-graphic accented-soak" role="img" aria-label="Damage minus Guts equals Total Damage. Example: 8 Standard damage minus Selu's 1 Guts equals 7 Total Damage."><div class="damage-formula-row"><span><small>Incoming</small><strong>Damage</strong><b>8</b></span><span class="formula-operator">−</span><span><small>Selu’s Defense</small><strong>Guts</strong><b>1</b></span><span class="formula-operator">=</span><span class="damage-formula-result"><small>Health Lost</small><strong>Total Damage</strong><b>7</b></span></div><p class="damage-formula-caption"><strong>Example:</strong> Selu has Guts [1]. Against [8] Standard damage, Selu loses [7] Health after Guts is applied.</p></div>
              <div v-if="isResistanceSection(entry.section)" class="resistance-graphic"><span><small>DIRECT FIRE</small><strong>Guts 6 → 3</strong></span><b>+</b><span><small>FIRE RESISTANCE +3</small><strong>3 → 6 Guts</strong></span><b>→</b><span><small>FINAL SOAK</small><strong>6 Guts</strong></span></div>
              <div v-if="isHealthSection(entry.section,'HEALTH')" class="health-state-graphic"><RuleFeatureCard title="Healthy" subtitle="6–30 HEALTH" tone-class="detail-tone-heritage"><p>No low-Health penalty.</p></RuleFeatureCard><RuleFeatureCard title="Wounded" subtitle="5–4 HEALTH" tone-class="detail-tone-equipment"><p>Condition [-1] to all dice rolls.</p></RuleFeatureCard><RuleFeatureCard title="Critical" subtitle="3–2 HEALTH" tone-class="detail-tone-oath"><p>Condition [-2] to all dice rolls.</p></RuleFeatureCard><RuleFeatureCard title="Last Breath" subtitle="1 HEALTH" tone-class="detail-tone-deed"><p>Condition [-3] to all dice rolls.</p></RuleFeatureCard></div>
              <div v-if="isHealthSection(entry.section,'HEALING')" class="healing-graphic"><span><small>CURRENT HEALTH</small><strong>12</strong></span><b>+</b><span><small>RESTORE HEALTH</small><strong>[+4]</strong></span><b>=</b><span><small>NEW HEALTH</small><strong>16</strong></span></div>
              <div v-if="isHealthSection(entry.section,'DEFEATED')" class="defeated-graphic"><span><small>0 HEALTH</small><strong>Defeated</strong></span><b>→</b><span><small>ON TURN</small><strong>Hallows Save · 1d10</strong></span><b>→</b><span><small>FAIL 1–5</small><strong>+1 Fate Mark</strong></span><b>→</b><span><small>3 MARKS</small><strong>Death</strong></span></div>
              <div v-if="isHealthSection(entry.section,'ENCOUNTER ENDS')" class="rule-link-buttons encounter-end-links"><RouterLink class="secondary-button" to="/rules/read/monsters">See Monsters &amp; Characters</RouterLink><RouterLink class="secondary-button" to="/rules/read/beyond-character-creation">See Beyond Character Creation</RouterLink></div>
            </article>
          </section>
          <section v-else-if="!page.note" class="empty-state card-surface compact-empty"><h2>Rule Text Unavailable</h2><p>This page is organized in the reader but has no supplied source text in the current rules package.</p></section>
        </template>

  </RulePageLayout>
  <RulePageLayout v-else title="Rule Not Found" section="Rules" summary="The requested rule page is not available." back-to="/rules" back-label="Back to Rules" prefer-back-to>
    <section class="empty-state compact-empty"><h2>Rule Not Found</h2><p>The requested rule page is not available.</p><RouterLink class="primary-button" to="/rules">Back to Rules</RouterLink></section>
  </RulePageLayout>
</template>

<style scoped>
.rule-inline-label{margin-right:.35em;color:var(--ink);font-weight:900}
.rule-bullet-block{margin:11px 0 12px;line-height:1.55}.rule-bullet-block>p{margin:0 0 6px}.rule-bullet-block ul{margin:0;padding-left:20px}.rule-bullet-block li+li{margin-top:4px}
.source-table-title{margin:13px 0 7px;font-family:Georgia,"Times New Roman",serif;font-size:calc(14px + var(--font-offset));font-weight:900;color:var(--ink)}
.rule-section-count{margin:-2px 0 10px;color:var(--ink-soft);font-size:calc(10px + var(--font-offset))}
.playable-species-link-list{padding:0}.playable-species-link-list .list-row:last-child{border-bottom:0}
.species-rule-art-frame{display:grid;place-items:center;width:100%;height:100%;min-height:0;overflow:hidden;border:2px solid #000;border-radius:0 12px 0 0}.species-rule-art-frame img{display:block;width:100%;height:100%;max-height:270px;object-fit:contain}
.review-box-list,.review-spell-column{display:grid;gap:8px}
.lore-reader-meta{display:flex;align-items:center;justify-content:flex-end;gap:10px;margin:-3px 0 10px;color:var(--ink-soft)}.lore-reader-description{margin:0 0 12px}.lore-attunement-preview-toggle{display:inline-flex;align-items:center;gap:7px;color:var(--ink);font-size:calc(9px + var(--font-offset));font-weight:850;white-space:nowrap;cursor:pointer}.lore-attunement-preview-toggle>.switch{flex:0 0 auto}
.targeting-touch-pill-row{margin:8px 0 0}.targeting-rule-layout{display:grid;grid-template-columns:minmax(0,1fr) minmax(210px,38%);align-items:center;gap:14px;margin:12px 0 0}.targeting-rule-layout.compact{grid-template-columns:minmax(0,1fr) 150px}.targeting-rule-layout p{margin:0 0 9px;line-height:1.55}.targeting-rule-layout img{display:block;width:100%;max-height:360px;object-fit:contain;border:1px solid var(--line);border-radius:8px;background:#fff}.targeting-rule-layout.compact img{max-height:220px}.rule-example-copy{color:var(--ink-soft)}
.attack-defense-graphic{display:grid;grid-template-columns:minmax(0,1fr) auto minmax(0,1fr) minmax(180px,.75fr);align-items:stretch;gap:9px;padding:12px;border:1px solid var(--line);border-radius:10px;background:var(--paper-2)}.attack-node,.defense-node,.resolution-node{display:grid;align-content:center;gap:4px;padding:10px;border:1px solid var(--line);border-top:5px solid var(--accent);border-radius:9px;background:var(--paper);text-align:center}.defense-node{border-top-color:var(--detail-trait-heritage)}.resolution-node{border-top-color:var(--detail-spark)}.attack-defense-graphic>b{align-self:center;font-size:20px}.attack-defense-graphic small{font-weight:900;letter-spacing:.08em;color:var(--ink-soft)}
.core-attack-reference{display:grid;gap:9px}.core-attack-grid{display:grid;grid-template-columns:1fr;gap:9px}
.rule-feature-grid,.spell-keyword-card-grid,.magic-resource-grid,.equipment-item-grid,.instinct-action-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:9px}
.xp-method-grid,.damage-stat-grid,.healing-graphic,.defeated-graphic,.instinct-trait-example-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:9px;margin:10px 0}
.health-state-graphic{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:8px;margin:10px 0}.resistance-graphic{display:grid;grid-template-columns:minmax(0,1fr) auto minmax(0,1fr) auto minmax(0,1fr);align-items:center;gap:8px;margin:10px 0;padding:11px;border:1px solid var(--line);border-radius:10px;background:var(--paper-2)}.resistance-graphic>span{display:grid;gap:3px;padding:9px;border:1px solid var(--line);border-top:5px solid var(--detail-equipment,var(--accent));border-radius:8px;background:var(--paper);text-align:center}.resistance-graphic small{color:var(--ink-soft);font-size:8px;font-weight:900;letter-spacing:.06em}.resistance-graphic>b{color:var(--accent-dark);font-size:20px;text-align:center}
.rule-link-buttons,.encounter-end-links{display:flex;flex-wrap:wrap;gap:8px;margin-top:10px}.lore-elemental-resistance{margin-right:auto;color:var(--ink);font-size:calc(9px + var(--font-offset));font-weight:850}
.initiative-roll-graphic{display:grid;grid-template-columns:minmax(0,1fr) auto minmax(0,1fr);align-items:center;gap:9px;margin:10px 0;padding:11px;border:1px solid var(--line);border-radius:10px;background:var(--paper-2)}.initiative-roll-graphic>span{display:grid;gap:3px;padding:9px 10px;border:1px solid var(--line);border-top:5px solid var(--accent);border-radius:8px;background:var(--paper);text-align:center}.initiative-roll-graphic small{color:var(--ink-soft);font-size:8px;font-weight:900;letter-spacing:.08em}.initiative-roll-graphic>b{color:var(--accent-dark);font-size:20px;text-align:center}
.initiative-order-example{margin-top:10px;padding:11px;border:1px solid var(--line);border-radius:10px;background:var(--paper-2)}.initiative-order-example>strong{display:block;margin-bottom:7px;font-family:Georgia,"Times New Roman",serif}.initiative-order-example ol{display:grid;gap:5px;margin:0;padding:0;list-style:none}.initiative-order-example li{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:7px 9px;border-left:5px solid var(--accent);border-radius:6px;background:var(--paper)}.initiative-order-example li.watcher-position{border-left-color:var(--detail-spark,var(--accent))}.initiative-order-example li span{font-weight:900}
.encounter-round-flow{display:grid;grid-template-columns:repeat(9,auto);align-items:center;justify-content:center;gap:7px;padding:12px;border:1px solid var(--line);border-radius:10px;background:var(--paper-2)}.encounter-round-flow>span{display:grid;justify-items:center;gap:3px;min-width:110px;padding:9px;border:1px solid var(--line);border-top:5px solid var(--accent);border-radius:9px;background:var(--paper);text-align:center}.encounter-round-flow small{display:grid;place-items:center;width:24px;height:24px;border-radius:999px;background:var(--accent);color:#fff;font-weight:900}.encounter-round-flow>b{font-size:20px;color:var(--accent-dark)}.square-measurement-graphic{display:grid;grid-template-columns:minmax(110px,1fr) auto minmax(110px,1fr) auto minmax(90px,1fr) auto minmax(90px,1fr);align-items:center;gap:8px;margin-top:10px;padding:11px;border:1px solid var(--line);border-radius:10px;background:var(--paper-2)}.square-measurement-graphic>span{display:grid;gap:2px;justify-items:center;padding:8px;border:1px solid var(--line);border-top:5px solid var(--detail-equipment,var(--accent));border-radius:8px;background:var(--paper);text-align:center}.square-measurement-graphic small{color:var(--ink-soft);font-size:8px;font-weight:900;letter-spacing:.06em}.square-measurement-graphic>b{text-align:center;color:var(--accent-dark);font-size:20px}
.equipment-rule-card-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:7px;margin:9px 0 13px}.equipment-rule-card{overflow:hidden;border:1px solid var(--line);border-top:5px solid var(--accent);border-radius:8px;background:var(--paper)}.equipment-rule-card header{padding:7px 9px;border-bottom:1px solid var(--line);background:var(--paper-2)}.equipment-rule-card>div{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:5px;padding:8px}.equipment-rule-card span{display:grid;gap:1px;min-width:0}.equipment-rule-card small{color:var(--ink-soft);font-size:8px;font-weight:850}.equipment-rule-card b{font-weight:650;overflow-wrap:anywhere}.equipment-rule-card .bracket-number{font-weight:900}
.equipment-source-stack{display:grid;gap:14px}.equipment-source-section+.equipment-source-section{padding-top:14px;border-top:1px solid var(--line)}.equipment-source-section>h3{margin:0 0 8px;font-family:Georgia,"Times New Roman",serif;font-size:calc(16px + var(--font-offset))}.equipment-source-section>p{line-height:1.6}
.deed-rule-list{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:9px}.deed-cards-menu .deed-rule-list{padding:10px}.deed-card-footer{display:flex;align-items:flex-end;justify-content:space-between;gap:8px}.deed-card-footer .keyword-pill-row{flex:1 1 auto}.deed-roll-result{display:inline-flex;align-items:center;justify-content:center;flex:0 0 auto;min-width:42px;min-height:26px;padding:3px 7px;border:1px solid color-mix(in srgb,var(--rule-tone,var(--accent)) 72%,var(--line));border-radius:999px;background:color-mix(in srgb,var(--rule-tone,var(--accent)) 12%,var(--paper-2));color:var(--ink);font-size:calc(9px + var(--font-offset));font-weight:900;line-height:1;white-space:nowrap}
.rule-narrative-note{margin:10px 0;padding:10px 12px;border:1px solid var(--line);border-left:5px solid var(--accent);border-radius:7px;background:var(--paper-2);font-family:inherit;font-size:calc(12px + var(--font-offset));font-weight:400;line-height:1.55}.rule-narrative-note>strong{display:block;margin-bottom:5px;font-family:Georgia,"Times New Roman",serif;font-size:calc(13px + var(--font-offset))}.rule-narrative-note p{margin:0;font:inherit}.bracket-number{font-weight:900;color:var(--ink)}
.organized-rule-category{overflow:hidden}.organized-rule-category>summary{display:flex;align-items:center;justify-content:space-between;gap:12px;list-style:none;cursor:pointer;padding:10px 12px;border-bottom:1px solid transparent;background:var(--paper-2)}.organized-rule-category>summary::-webkit-details-marker{display:none}.organized-rule-category>summary>span:first-child{display:flex;align-items:baseline;justify-content:space-between;gap:16px;min-width:0;flex:1}.organized-rule-category>summary>span:first-child small{margin-left:auto;text-align:right}.organized-rule-category>summary h2{margin:0;font-family:Georgia,"Times New Roman",serif;font-size:calc(17px + var(--font-offset))}.organized-rule-category>summary small{color:var(--ink-soft);font-weight:650;line-height:1.35}.organized-rule-category>summary>span:last-child{font-size:20px;color:var(--ink-soft);transition:transform .15s ease}.organized-rule-category[open]>summary{border-bottom-color:var(--line)}.organized-rule-category[open]>summary>span:last-child{transform:rotate(180deg)}.organized-rule-category-body{padding:10px}.organized-rule-category-body.rule-box-grid{margin:0}
.rule-cross-reference{display:flex;align-items:center;gap:10px;flex-wrap:wrap;margin-bottom:10px;padding:10px 12px;border:1px solid var(--line);border-radius:9px;background:var(--paper-2)}.rule-cross-reference>p{flex:1 1 360px;margin:0;color:var(--ink-soft);line-height:1.45}
.monster-family-stack{display:grid;gap:8px;margin-top:10px}.monster-family-box{overflow:hidden;border:1px solid var(--line);border-radius:8px}.monster-family-box>summary{display:flex;justify-content:space-between;align-items:center;gap:10px;list-style:none;cursor:pointer;padding:8px 10px;background:var(--paper-2)}.monster-family-box>summary::-webkit-details-marker{display:none}.monster-family-box>summary>span:first-child{display:grid;gap:2px}.monster-family-box>summary small{color:var(--ink-soft)}.monster-family-box .monster-link-grid{padding:8px}
.narrative-card-grid{display:grid;gap:9px}.premade-spark-grid,.two-column-oaths{grid-template-columns:repeat(2,minmax(0,1fr))}.spark-deed-interaction{margin:12px 0 8px}.spark-example-text-list{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:9px;margin:8px 0 12px}.spark-example-text-list>p{margin:0;padding:9px 10px;border-left:4px solid var(--detail-spark,var(--accent));background:var(--paper-2);line-height:1.5}.spark-example-text-list>p>span{display:block;margin-top:4px;color:var(--ink-soft)}.watcher-note-panel{margin-top:0}
.creation-step-section{--section-tone:var(--accent)}
.creation-attribute-demo{margin:10px 0 14px}.creation-attribute-demo>header{display:flex;justify-content:space-between;gap:10px;margin-bottom:8px;font-weight:900}.creation-attribute-demo>header span{color:var(--accent-dark)}.creation-attribute-list{display:grid;gap:8px}.creation-attribute-row{--attribute-tone:#a06b2c;display:grid;grid-template-columns:minmax(0,1fr) minmax(230px,.72fr);gap:12px;padding:10px 11px;border:1px solid var(--line);border-radius:9px;background:var(--paper)}.creation-attribute-row.attribute-agility{--attribute-tone:#46779a}.creation-attribute-row.attribute-might{--attribute-tone:#9b543e}.creation-attribute-row.attribute-hide{--attribute-tone:#527934}.creation-attribute-row.attribute-lore{--attribute-tone:#6d5293}.creation-attribute-row.attribute-bravery{--attribute-tone:#a06b2c}.creation-attribute-copy h3{margin:0;font-family:Georgia,"Times New Roman",serif;font-size:calc(16px + var(--font-offset))}.creation-attribute-copy>p{margin:3px 0 8px;color:var(--ink-soft)}.creation-secondary-stats{display:flex;gap:6px;flex-wrap:wrap}.creation-secondary-stats>span,.creation-rank-summary>span{display:grid;gap:2px;min-width:92px;padding:7px 9px;border:1px solid var(--line);border-left:4px solid var(--attribute-tone);border-radius:7px;background:var(--paper-2)}.creation-secondary-stats small,.creation-rank-summary small{font-size:8px;font-weight:850}.creation-secondary-stats strong{justify-self:end}.creation-attribute-controls{display:grid;align-content:center;gap:8px}.creation-rank-summary{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:7px}.creation-rank-summary>span{justify-items:center}.creation-rank-summary strong{font-size:calc(13px + var(--font-offset))}.creation-rank-stepper{display:grid;grid-template-columns:38px 44px 38px;align-items:center;justify-content:center}.creation-rank-stepper button,.creation-rank-stepper>strong{display:grid;place-items:center;height:38px;border:1px solid var(--line-dark);background:var(--paper);font:inherit;font-weight:900}.creation-rank-stepper button{cursor:pointer}.creation-rank-stepper button:first-child{border-radius:8px 0 0 8px}.creation-rank-stepper button:last-child{border-radius:0 8px 8px 0}.creation-rank-stepper>strong{border-left:0;border-right:0}.creation-rank-stepper button:disabled{cursor:not-allowed;opacity:.38}.creation-rank-stepper button:not(:disabled):hover{background:var(--accent-wash)}.creation-demo-note{display:block;margin-top:8px;color:var(--ink-soft);line-height:1.4}
.spark-structure-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:9px;margin:12px 0}.deed-structure-copy{margin:2px 0}.deed-example-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:9px;margin:12px 0}.species-rule-lore-placeholder{margin-top:10px}.species-lore-placeholder-body{min-height:34px}.creation-trait-graphic,.creation-example-pair{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.creation-single-example{display:flex;justify-content:center}.creation-single-example>article{width:min(520px,100%)}.creation-path-card{cursor:default}.creation-path-card:hover{transform:none}.creation-equipment-budget{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:8px;padding-top:10px}.creation-equipment-budget>span{display:grid;gap:3px;padding:9px;border:1px solid var(--line);border-radius:8px;background:var(--paper);text-align:center}.creation-equipment-budget small{color:var(--ink-soft);font-size:8px;font-weight:900;letter-spacing:.06em}.creation-equipment-budget strong{font-size:calc(17px + var(--font-offset))}.creation-equipment-budget b{color:var(--ink-soft);font-size:calc(10px + var(--font-offset))}
.damage-category-graphic{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:8px;margin:12px 0}.damage-category-graphic>article{display:grid;gap:4px;padding:10px;border:1px solid var(--line);border-top:5px solid var(--accent);border-radius:9px;background:var(--paper-2);text-align:center}.damage-category-graphic>article:nth-child(2){border-top-color:var(--detail-equipment)}.damage-category-graphic>article:nth-child(3){border-top-color:var(--detail-trait-culture)}.damage-category-graphic>article:nth-child(4){border-top-color:var(--detail-talent,var(--accent))}.damage-category-graphic small{font-size:8px;font-weight:900;letter-spacing:.08em;color:var(--ink-soft)}.damage-category-graphic span{color:var(--ink-soft);line-height:1.4}.damage-heart-callout{display:grid;gap:5px;margin:10px 0 14px;padding:11px 12px;border:1px solid var(--line);border-left:6px solid var(--detail-talent,var(--accent));border-radius:9px;background:color-mix(in srgb,var(--detail-talent,var(--accent)) 10%,var(--paper-2))}.damage-heart-callout>strong{font-family:Georgia,"Times New Roman",serif}.damage-heart-callout p{margin:0;line-height:1.55}.damage-formula-graphic{display:grid;gap:9px;margin:12px 0 14px;padding:12px;border:1px solid var(--line-dark);border-radius:10px;background:linear-gradient(135deg,var(--paper-2),var(--paper))}.damage-formula-row{display:grid;grid-template-columns:minmax(100px,1fr) auto minmax(100px,1fr) auto minmax(130px,1.2fr);align-items:center;gap:9px}.damage-formula-row>span:not(.formula-operator){display:grid;gap:3px;padding:9px 10px;border:1px solid var(--line);border-radius:8px;background:var(--paper);text-align:center}.damage-formula-row small{color:var(--ink-soft);font-size:8px;font-weight:850;text-transform:uppercase}.damage-formula-row b{font-size:calc(16px + var(--font-offset))}.formula-operator{font-size:22px;font-weight:900;text-align:center}.damage-formula-result{border-color:var(--accent);background:var(--accent-wash)}.damage-formula-caption{margin:0;padding-top:9px;border-top:1px solid var(--line);line-height:1.5}
.creation-reference-graphic,.creation-path-reference,.creation-equipment-graphic{margin:12px 0 15px}.creation-reference-graphic>article{min-width:0}.creation-path-step>p+p{margin-top:18px}.renew-heart-reference,.spell-range-targeting-reference{margin:12px 0}.creation-step-heading>span{display:grid;place-items:center;flex:0 0 34px;width:34px;height:34px;border-radius:999px;background:var(--section-tone);color:#fff;font-family:Georgia,"Times New Roman",serif;font-size:18px;font-weight:900}.creation-step-heading>div{min-width:0}
@media(max-width:900px){.encounter-round-flow{grid-template-columns:1fr;justify-content:stretch}.encounter-round-flow>b{transform:rotate(90deg);text-align:center}.square-measurement-graphic{grid-template-columns:1fr auto 1fr}.square-measurement-graphic>span:nth-of-type(3),.square-measurement-graphic>span:nth-of-type(4){grid-column:auto}.attack-defense-graphic{grid-template-columns:1fr auto 1fr}.resolution-node{grid-column:1/-1}}
@media(max-width:760px){.rule-feature-grid,.spell-keyword-card-grid,.magic-resource-grid,.equipment-item-grid,.instinct-action-grid,.xp-method-grid,.damage-stat-grid,.healing-graphic,.defeated-graphic,.instinct-trait-example-grid,.health-state-graphic,.premade-spark-grid,.two-column-oaths,.spark-example-text-list{grid-template-columns:1fr}.creation-attribute-row{grid-template-columns:1fr}.creation-attribute-controls{grid-template-columns:minmax(0,1fr) auto;align-items:center}.creation-rank-stepper{justify-content:end}.damage-category-graphic{grid-template-columns:1fr}.damage-formula-row{grid-template-columns:1fr auto 1fr}.damage-formula-result{grid-column:1/-1}.damage-formula-row>.formula-operator:nth-child(4){display:none}.spark-structure-grid,.deed-example-grid,.creation-trait-graphic,.creation-example-pair{grid-template-columns:1fr}.creation-equipment-budget{grid-template-columns:1fr}}
@media(max-width:680px){.organized-rule-category>summary>span:first-child{align-items:flex-start}.organized-rule-category>summary>span:first-child small{max-width:48%}.targeting-rule-layout,.targeting-rule-layout.compact{grid-template-columns:1fr}.targeting-rule-layout img,.targeting-rule-layout.compact img{max-height:320px}.organized-rule-category>summary{align-items:flex-start}.species-rule-art-frame{border-radius:0}.lore-reader-meta{align-items:flex-start;flex-direction:column}}
@media(max-width:620px){.equipment-rule-card-grid,.deed-rule-list{grid-template-columns:1fr}}
@media(max-width:520px){.resistance-graphic{grid-template-columns:1fr}.resistance-graphic>b{transform:rotate(90deg)}.initiative-roll-graphic{grid-template-columns:1fr}.initiative-roll-graphic>b{transform:rotate(90deg)}.square-measurement-graphic{grid-template-columns:1fr}.square-measurement-graphic>b{transform:rotate(90deg)}.creation-attribute-demo>header{align-items:flex-start;flex-direction:column}.creation-attribute-controls{grid-template-columns:1fr}.creation-rank-stepper{justify-content:center}.creation-secondary-stats>span{flex:1 1 90px}.damage-formula-row{grid-template-columns:1fr}.formula-operator{display:none}.damage-formula-result{grid-column:auto}.attack-defense-graphic{grid-template-columns:1fr}.attack-defense-graphic>b{transform:rotate(90deg);text-align:center}.resolution-node{grid-column:auto}}
</style>
