<script setup lang="ts">
import { computed, reactive, ref, watch } from 'vue'
import AppHeader from '../components/AppHeader.vue'
import CharacterAttributePanel from '../components/CharacterAttributePanel.vue'
import { attributes, passiveTargets } from '../data/bramble'
import { skillDefinitions } from '../data/characterOptions'
import { loreSpells } from '../data/magicOptions'
import { loreDescriptions, spellDetails } from '../data/magicDetails'
import { ruleSourceDocuments } from '../data/rulesCurrent'
import { canonicalTalentName, talentNameMatches } from '../data/talentCategories'
import { characterSheetArmorProfile, characterSheetWeaponProfile, derivedStats, equippedProtectiveGear, equipmentControlBonus, equipmentGutsBonus, equipmentMagicRegenBonus, equipmentManaSyphon, equipmentRenewHeartConditionBonus, equipmentSpellManaReduction, magicResources, normalizeSkillName, rankModifier, rhythmResult, structuredRule, visibleRuleFields, equipmentArmorPenalty, equipmentSpeedPenalty, speciesMinimumSpeed } from '../rules/rulesEngine'
import { resolveSpellManaCost, spellCostLabel } from '../rules/magicRules'
import { canonicalGearCostWp } from '../rules/economy'
import { formatThreadpieceWp } from '../rules/threadpieces'
import { characterStatus, loadCharacters, type CharacterRecord } from '../services/characters'
import { readLocalStorage, RHYTHM_STORE, writeLocalStorage } from '../services/storage'
import { loadCustomData, type CustomSpeciesItem, type CustomSpellItem, type CustomTalentItem } from '../services/customData'
import { adventureKitEquipment } from '../data/equipment'
import { abilityFeaturePillClass, abilityFeaturePillKeywords, abilityFeaturePillLabel, abilityTypeClass, abilityTypeKeywords, activeAbilityKeywords } from '../rules/abilityPresentation'
import { characterThreatLevel } from '../rules/threatLevel'
import { externalMonsters } from '../data/externalMonsters'
import { deleteEncounter, loadEncounters, upsertEncounter, type EncounterRecord } from '../services/encounters'

type RhythmMode='normal'|'edged'|'weighted'
type TargetMode='none'|'passive'|'active'
type RhythmResultValue=ReturnType<typeof rhythmResult>
interface RhythmHistoryEntry{id:string;createdAt:string;rollType:string;mode:RhythmMode;stat:number;skillName:string;skillBonus:number;conditions:number;target:number|null;targetLabel:string;result:RhythmResultValue;fortunes:number;misfortunes:number}
const sheet=ref<'attribute'|'character'|'encounter'>('attribute')
const characters=ref<CharacterRecord[]>(loadCharacters().filter(character=>characterStatus(character)!=='incomplete'))
const selectedCharacterId=ref(characters.value[0]?.id||'')
const selectedCharacter=computed(()=>selectedCharacterId.value?characters.value.find(character=>character.id===selectedCharacterId.value)||null:null)
const customData=loadCustomData()
const customSpecies=customData.filter((item):item is CustomSpeciesItem=>item.type==='species')
const customSpells=customData.filter((item):item is CustomSpellItem=>item.type==='spell')
const customTalents=customData.filter((item):item is CustomTalentItem=>item.type==='talent')
function isCustomSpecies(name:string){return customSpecies.some(item=>item.name===name)}
function isCustomSpell(name:string){return customSpells.some(item=>item.name===name)}
function isCustomTalent(name:string){return customTalents.some(item=>item.name===name)}

function die(){const a=new Uint32Array(1);crypto.getRandomValues(a);return(a[0]%10)+1}
function dice(count:number){return Array.from({length:count},die)}
function readStore<T>(key:string,fallback:T):T{try{return JSON.parse(readLocalStorage(key)||'') as T}catch{return fallback}}
function writeStore(key:string,value:unknown){return writeLocalStorage(key,JSON.stringify(value))}
function stamp(){return new Date().toISOString()}
function formatTime(value:string){return new Date(value).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})}
function rank(c:CharacterRecord,key:'agility'|'might'|'hide'|'lore'|'bravery'){return Number(c.attributes?.[key]||0)}
const skillModifier=rankModifier

const rollTypes=['Attribute Save','Compelled','Initiative','Other','Role-Play','Skill Check','Strike','Ward'] as const
const rollType=ref<(typeof rollTypes)[number]>('Attribute Save')
const rhythmMode=ref<RhythmMode>('normal')
const rhythmStat=ref(0),rhythmSkillBonus=ref(0),rhythmConditions=ref(0)
const rhythmSkill=ref('')
const targetMode=ref<TargetMode>('none'),passiveTarget=ref(18),activeTarget=ref<number|null>(null)
const rhythmHistory=ref<RhythmHistoryEntry[]>(readStore<RhythmHistoryEntry[]>(RHYTHM_STORE,[]).slice(0,5))
const characterStatKey=ref('agility')

const allCharacterStats=computed(()=>{
  const c=selectedCharacter.value;if(!c)return[] as Array<{key:string;label:string;value:number;attribute:string}>
  const secondary=derivedStats(c.attributes,equipmentGutsBonus(c.equipment),equipmentControlBonus(c.equipment),equipmentSpeedPenalty(c.equipment,c.species==='Tordan'),speciesMinimumSpeed(c.species))
  return[
    {key:'agility',label:'Agility',value:rankModifier(rank(c,'agility')),attribute:'Agility'},
    {key:'might',label:'Might',value:rankModifier(rank(c,'might')),attribute:'Might'},
    {key:'hide',label:'Hide',value:rankModifier(rank(c,'hide')),attribute:'Hide'},
    {key:'lore',label:'Lore',value:rankModifier(rank(c,'lore')),attribute:'Lore'},
    {key:'bravery',label:'Bravery',value:rankModifier(rank(c,'bravery')),attribute:'Bravery'},
    {key:'speed',label:'Speed',value:secondary.speed,attribute:'Agility'},
    {key:'aim',label:'Aim',value:secondary.aim,attribute:'Agility'},
    {key:'accuracy',label:'Accuracy',value:secondary.accuracy,attribute:'Agility'},
    {key:'brawl',label:'Brawl',value:secondary.brawl,attribute:'Might'},
    {key:'fury',label:'Fury',value:secondary.fury,attribute:'Might'},
    {key:'ward',label:'Ward',value:secondary.ward,attribute:'Hide'},
    {key:'guts',label:'Guts',value:secondary.guts,attribute:'Hide'},
    {key:'control',label:'Control',value:secondary.control,attribute:'Lore'},
    {key:'power',label:'Power',value:secondary.power,attribute:'Lore'},
    {key:'spirit',label:'Spirit',value:secondary.spirit,attribute:'Bravery'},
    {key:'heart',label:'Heart',value:secondary.heart,attribute:'Bravery'},
  ]
})
function allowedStatKeys(type:string){
  if(type==='Initiative')return['speed']
  if(type==='Strike')return['aim','brawl','control']
  if(type==='Ward')return['ward']
  if(['Attribute Save','Compelled','Skill Check','Role-Play'].includes(type))return['agility','might','hide','lore','bravery']
  return allCharacterStats.value.map(item=>item.key)
}
const statOptions=computed(()=>{const allowed=new Set(allowedStatKeys(rollType.value));return allCharacterStats.value.filter(item=>allowed.has(item.key))})
const selectedStat=computed(()=>statOptions.value.find(item=>item.key===characterStatKey.value)||statOptions.value[0]||null)
function statOptionLabel(stat:{key:string;label:string;value:number}){
  if(stat.key==='aim')return`Aim +${stat.value} (Shooting)`
  if(stat.key==='brawl')return`Brawl +${stat.value} (Melee)`
  if(stat.key==='control')return`Control +${stat.value} (Magic)`
  return`${stat.label} +${stat.value}`
}
const rollUsesSkill=computed(()=>['Skill Check','Role-Play','Other'].includes(rollType.value))
const characterSkillOptions=computed(()=>{
  const c=selectedCharacter.value,stat=selectedStat.value;if(!c||!stat||!rollUsesSkill.value)return[] as Array<{name:string;rank:number}>
  return Object.entries(c.skillRanks||{}).map(([name,value])=>({name:normalizeSkillName(name),rank:Number(value)})).filter(entry=>{
    const def=skillDefinitions.find(item=>normalizeSkillName(item.name)===entry.name)
    return Boolean(def)&&def?.attribute===stat.attribute
  }).sort((a,b)=>a.name.localeCompare(b.name))
})
const statFieldLabel=computed(()=>rollType.value==='Strike'?'Strike Stat':rollType.value==='Ward'?'Ward Stat':rollType.value==='Initiative'?'Initiative Stat':rollType.value==='Attribute Save'?'Save Attribute':rollType.value==='Skill Check'?'Skill Attribute':'Character Stat')
const skillFieldLabel=computed(()=>selectedStat.value?`${selectedStat.value.attribute} Skill`:'Character Skill')
watch([rollType,selectedCharacterId],()=>{const first=statOptions.value[0];characterStatKey.value=first?.key||'agility';rhythmSkill.value='';if(!rollUsesSkill.value)rhythmSkillBonus.value=0},{immediate:true})
watch(characterStatKey,()=>{rhythmSkill.value='';if(selectedCharacter.value)rhythmStat.value=selectedStat.value?.value||0},{immediate:true})
watch(rhythmSkill,()=>{if(!rollUsesSkill.value){rhythmSkillBonus.value=0;return}if(selectedCharacter.value){const entry=characterSkillOptions.value.find(item=>item.name===rhythmSkill.value);rhythmSkillBonus.value=skillModifier(entry?.rank||0)}})
const effectiveRhythmStat=computed(()=>selectedCharacter.value?Number(selectedStat.value?.value||0):Number(rhythmStat.value||0))
const rhythmCombinedStat=computed(()=>effectiveRhythmStat.value+(rollUsesSkill.value?Number(rhythmSkillBonus.value||0):0))
const gearRenewHeartBonus=computed(()=>equipmentRenewHeartConditionBonus(selectedCharacter.value?.equipment))
const effectiveRhythmConditions=computed(()=>Number(rhythmConditions.value||0)+(rollType.value==='Compelled'?gearRenewHeartBonus.value:0)+(normalizeSkillName(rhythmSkill.value)==='Whisperster'?gearArmorPenalty.value:0))
const rollSummary=computed(()=>{const style=rhythmMode.value==='normal'?'Normal':rhythmMode.value==='edged'?'Edged':'Weighted';const stat=selectedStat.value?.label||statFieldLabel.value;const parts=[`${stat} (${effectiveRhythmStat.value})`];if(rollUsesSkill.value&&rhythmSkill.value)parts.push(`${rhythmSkill.value} (${Number(rhythmSkillBonus.value||0)})`);const conditions=effectiveRhythmConditions.value;if(conditions!==0)parts.push(`Conditions (${conditions})`);if(rollType.value==='Compelled'&&gearRenewHeartBonus.value)parts.push(`Votive Icon (+${gearRenewHeartBonus.value})`);return`${style} ${rollType.value} Roll: ${parts.join(' + ')} = ${rhythmCombinedStat.value+conditions}`})
const currentTarget=computed(()=>targetMode.value==='passive'?Number(passiveTarget.value):targetMode.value==='active'&&activeTarget.value!==null?Number(activeTarget.value):null)
function targetLabel(){if(targetMode.value==='active')return'Active Target';if(targetMode.value==='passive')return passiveTargets.find(([,value])=>value===Number(passiveTarget.value))?.[0]||'Passive Target';return'No Target'}
function rollAttributeCheck(){const conditions=effectiveRhythmConditions.value;const result=rhythmResult(dice(rhythmMode.value==='normal'?3:4),rhythmMode.value,rhythmCombinedStat.value,conditions);const kept=result.kept||result.rolled;const entry:RhythmHistoryEntry={id:crypto.randomUUID(),createdAt:stamp(),rollType:rollType.value,mode:rhythmMode.value,stat:effectiveRhythmStat.value,skillName:rollUsesSkill.value?rhythmSkill.value:'',skillBonus:rollUsesSkill.value?Number(rhythmSkillBonus.value||0):0,conditions,target:currentTarget.value,targetLabel:targetLabel(),result,fortunes:kept.filter(value=>value>=8).length,misfortunes:kept.filter(value=>value<=2).length};rhythmHistory.value=[entry,...rhythmHistory.value].slice(0,5);const saved=writeStore(RHYTHM_STORE,rhythmHistory.value);if(!saved.ok)alert(saved.message)}
function rollOutcome(entry:RhythmHistoryEntry){if(entry.target===null)return'';return entry.result.total>=entry.target?'SUCCESS':'FAILURE'}

const gearGutsBonus=computed(()=>equipmentGutsBonus(selectedCharacter.value?.equipment))
const gearControlBonus=computed(()=>equipmentControlBonus(selectedCharacter.value?.equipment))
const gearMagicRegenBonus=computed(()=>equipmentMagicRegenBonus(selectedCharacter.value?.equipment))
const gearArmorPenalty=computed(()=>equipmentArmorPenalty(selectedCharacter.value?.equipment))
const gearSpeedPenalty=computed(()=>equipmentSpeedPenalty(selectedCharacter.value?.equipment,selectedCharacter.value?.species==='Tordan'))
const minimumSpeed=computed(()=>speciesMinimumSpeed(selectedCharacter.value?.species))
const secondaryStats=computed(()=>selectedCharacter.value?derivedStats(selectedCharacter.value.attributes,gearGutsBonus.value,gearControlBonus.value,gearSpeedPenalty.value,minimumSpeed.value):null)
const selectedSkills=computed(()=>{const c=selectedCharacter.value;if(!c)return[];const ranks=c.skillRanks&&Object.keys(c.skillRanks).length?c.skillRanks:Object.fromEntries((c.skills||[]).map(name=>[normalizeSkillName(name),1]));return Object.entries(ranks).map(([name,value])=>({name:normalizeSkillName(name),rank:Number(value)})).sort((a,b)=>a.name.localeCompare(b.name))})
const weapons=computed(()=>selectedCharacter.value?.equipment?.filter(item=>item.category==='Weapon')||[])
const armor=computed(()=>equippedProtectiveGear(selectedCharacter.value?.equipment))
const otherGear=computed(()=>selectedCharacter.value?[...adventureKitEquipment(selectedCharacter.value.adventureKit),...(selectedCharacter.value.equipment||[]).filter(item=>!['Weapon','Armor & Shield','Trinket'].includes(item.category||''))]:[])
const weaponSlots=computed(()=>Array.from({length:Math.max(3,weapons.value.length)},(_,index)=>characterSheetWeaponProfile(weapons.value[index],selectedCharacter.value?.equipment)))
const armorSlots=computed(()=>Array.from({length:Math.max(2,armor.value.length)},(_,index)=>characterSheetArmorProfile(armor.value[index],selectedCharacter.value?.equipment)))
const equippedTrinkets=computed(()=>selectedCharacter.value?.equipment?.filter(item=>item.category==='Trinket'&&(item.equipped!==false))||[])

function spellDetail(name:string){const custom=customSpells.find(item=>item.name===name);return custom||spellDetails[name]}
const talentSections=ruleSourceDocuments.talents.sections
function talentText(name:string){const custom=customTalents.find(item=>item.name===name);if(custom)return custom.text;const section=talentSections.find(item=>talentNameMatches(item.heading,name));return section?.blocks.filter(block=>block.type==='paragraph').map(block=>block.type==='paragraph'?block.text:'').join(' ')||''}
function talentKeywords(name:string){const custom=customTalents.find(item=>item.name===name);if(custom)return activeAbilityKeywords(custom.keywords);const match=talentText(name).match(/\bKEYWORDS?:\s*(.+)$/i);return activeAbilityKeywords(match?[match[1]]:[])}
function talentAbilityTypes(name:string){return abilityTypeKeywords(talentKeywords(name))}
function talentAbilityClasses(name:string){return talentAbilityTypes(name).map(abilityTypeClass)}
function weaponPropertyPills(value:string){return value==='—'?[]:String(value||'').split(',').map(part=>part.trim()).filter(Boolean)}
function spellLoreClass(name:string){return `spell-lore-${String(spellDetail(name)?.lore||'invocation').toLowerCase()}`}
const magicLevel=computed(()=>Number(selectedCharacter.value?.magicLevel??(selectedCharacter.value?.path==='magic'?1:0)))
const resources=computed(()=>selectedCharacter.value?magicResources(selectedCharacter.value.attributes,magicLevel.value,gearMagicRegenBonus.value):{manaPool:0,magicRegen:0})
const maxMana=computed(()=>resources.value.manaPool)
const signatureSpell=computed(()=>{const c=selectedCharacter.value;if(!c?.loreAttunement)return'';return customSpells.find(item=>item.lore===c.loreAttunement&&item.signature)?.name||loreSpells[c.loreAttunement]?.[0]||''})
function spellNamesForCharacter(character:CharacterRecord|null){if(!character)return[] as string[];const level=Math.max(0,Number(character.magicLevel??(character.path==='magic'?1:0))||0);if(level<1)return[] as string[];const signature=character.loreAttunement?(customSpells.find(item=>item.lore===character.loreAttunement&&item.signature)?.name||loreSpells[character.loreAttunement]?.[0]||''):'';return Array.from(new Set([signature,...(character.spells||[]),...(character.invocationSpells||[]),...(character.invocationSpell?[character.invocationSpell]:[])].filter(Boolean) as string[]))}
const characterSpells=computed(()=>spellNamesForCharacter(selectedCharacter.value))
function effectiveMana(name:string){
  const detail=spellDetail(name);if(!detail)return null
  const custom=customSpells.find(item=>item.name===name)
  return resolveSpellManaCost({name,lore:detail.lore,baseCost:detail.manaCost,attunedLore:selectedCharacter.value?.loreAttunement,manaSyphon:equipmentManaSyphon(selectedCharacter.value?.equipment),focusReduction:equipmentSpellManaReduction(selectedCharacter.value?.equipment),signature:Boolean(custom?.signature),cantrip:Boolean(custom&&!custom.signature&&detail.lore==='Invocation'&&detail.manaCost===0)})
}
function spellCostText(name:string){
  const detail=spellDetail(name);if(!detail)return'Variable'
  const custom=customSpells.find(item=>item.name===name)
  return spellCostLabel({name,lore:detail.lore,baseCost:detail.manaCost,attunedLore:selectedCharacter.value?.loreAttunement,manaSyphon:equipmentManaSyphon(selectedCharacter.value?.equipment),focusReduction:equipmentSpellManaReduction(selectedCharacter.value?.equipment),signature:Boolean(custom?.signature),cantrip:Boolean(custom&&!custom.signature&&detail.lore==='Invocation'&&detail.manaCost===0)})
}
const loreCharacterSpells=computed(()=>characterSpells.value.filter(name=>!selectedCharacter.value?.invocationSpells?.includes(name)&&name!==selectedCharacter.value?.invocationSpell).sort((a,b)=>(effectiveMana(a)??999)-(effectiveMana(b)??999)||a.localeCompare(b)))
const invocationCharacterSpells=computed(()=>characterSpells.value.filter(name=>selectedCharacter.value?.invocationSpells?.includes(name)||name===selectedCharacter.value?.invocationSpell).sort((a,b)=>(effectiveMana(a)??999)-(effectiveMana(b)??999)||a.localeCompare(b)))
const selectedPathName=computed(()=>({magic:'Wind-Touched',talents:'Gifted Heart',skills:'Practiced Hand',attribute:'Tempered Form'} as const)[selectedCharacter.value?.path||'magic']||'Gifted Heart')
const selectedThreatLevel=computed(()=>{const character=selectedCharacter.value;if(!character)return 1;return characterThreatLevel({attributeRanks:attributes.map(attribute=>Number(character.attributes?.[attribute.id]||1)),skillRanks:Object.values(character.skillRanks||{}).map(Number),talentCount:(character.talents||[]).filter(Boolean).length,magicLevel:magicLevel.value})})

const encounterSteps=['Details','Party','Opposition','Battlefield','Review'] as const
type EncounterStep=(typeof encounterSteps)[number]
const encounterStep=ref<EncounterStep>('Details')
const encounters=ref<EncounterRecord[]>(loadEncounters())
const encounterSaveMessage=ref('')
const opponentName=ref('')
const opponentQuantity=ref(1)
function encounterId(){return typeof crypto!=='undefined'&&'randomUUID' in crypto?crypto.randomUUID():`encounter-${Date.now()}-${Math.random().toString(36).slice(2,8)}`}
function blankEncounter():EncounterRecord{const now=stamp();return{id:encounterId(),name:'',objective:'',partyCharacterIds:[],opponents:[],environment:'',notes:'',createdAt:now,updatedAt:now}}
const encounterDraft=reactive<EncounterRecord>(blankEncounter())
const encounterMonsterOptions=computed(()=>externalMonsters.filter(monster=>monster.category!=='Companions').slice().sort((a,b)=>a.category.localeCompare(b.category)||a.name.localeCompare(b.name)))
function threatForCharacter(character:CharacterRecord){return characterThreatLevel({attributeRanks:attributes.map(attribute=>Number(character.attributes?.[attribute.id]||1)),skillRanks:Object.values(character.skillRanks||{}).map(Number),talentCount:(character.talents||[]).filter(Boolean).length,magicLevel:Number(character.magicLevel||0)})}
const encounterParty=computed(()=>characters.value.filter(character=>encounterDraft.partyCharacterIds.includes(character.id)))
const encounterGroupThreat=computed(()=>encounterParty.value.reduce((sum,character)=>sum+threatForCharacter(character),0))
const encounterOpponentTotal=computed(()=>encounterDraft.opponents.reduce((sum,item)=>sum+item.quantity,0))
function setEncounterStep(step:EncounterStep){encounterStep.value=step}
function newEncounter(){Object.assign(encounterDraft,blankEncounter());encounterStep.value='Details';encounterSaveMessage.value=''}
function editEncounter(encounter:EncounterRecord){Object.assign(encounterDraft,JSON.parse(JSON.stringify(encounter)));encounterStep.value='Details';encounterSaveMessage.value=''}
function toggleEncounterParty(id:string,checked:boolean){encounterDraft.partyCharacterIds=checked?Array.from(new Set([...encounterDraft.partyCharacterIds,id])):encounterDraft.partyCharacterIds.filter(value=>value!==id)}
function addEncounterOpponent(){const name=opponentName.value.trim();if(!name)return;const quantity=Math.max(1,Math.floor(Number(opponentQuantity.value)||1));const existing=encounterDraft.opponents.find(item=>item.name===name);if(existing)existing.quantity+=quantity;else encounterDraft.opponents.push({name,quantity});opponentName.value='';opponentQuantity.value=1}
function removeEncounterOpponent(index:number){encounterDraft.opponents.splice(index,1)}
function saveEncounterDraft(){const now=stamp();if(!encounterDraft.createdAt)encounterDraft.createdAt=now;encounterDraft.updatedAt=now;const saved=upsertEncounter(encounters.value,{...encounterDraft,name:encounterDraft.name.trim()||'Untitled Encounter'});if(saved.result.ok){encounters.value=saved.encounters;encounterDraft.name=encounterDraft.name.trim()||'Untitled Encounter';encounterSaveMessage.value='Encounter saved to this device.'}else encounterSaveMessage.value=saved.result.message}
function removeSavedEncounter(id:string){if(typeof window!=='undefined'&&!window.confirm('Delete this saved encounter?'))return;const deleted=deleteEncounter(encounters.value,id);if(deleted.result.ok){encounters.value=deleted.encounters;if(encounterDraft.id===id)newEncounter();encounterSaveMessage.value='Encounter deleted.'}else encounterSaveMessage.value=deleted.result.message}

</script>

<template>
  <main class="page simulator-page rhythm-engine-page">
    <AppHeader />
    <div class="page-title-block"><h1>Rhythm Engine</h1></div>
    <div class="segment-tabs simulator-tabs rhythm-sheet-tabs"><button type="button" class="segment-tab" :class="{active:sheet==='character'}" @click="sheet='character'">Character Sheet</button><button type="button" class="segment-tab" :class="{active:sheet==='attribute'}" @click="sheet='attribute'">Dice Roller</button><button type="button" class="segment-tab" :class="{active:sheet==='encounter'}" @click="sheet='encounter'">Encounter Builder</button></div>

    <section v-if="sheet!=='encounter'" class="character-selection-panel card-surface"><label class="field-label">Character<select v-model="selectedCharacterId" class="field-control"><option value="">Manual / No Character</option><option v-for="character in characters" :key="character.id" :value="character.id">{{ character.name }} {{ character.species }}</option></select></label><div v-if="selectedCharacter" class="character-selection-summary"><strong>{{ selectedCharacter.name }}</strong><span>{{ selectedCharacter.species }} · {{ selectedCharacter.campaignName||'No Campaign' }}</span></div></section>

    <section v-if="sheet==='attribute'" class="tool-panel card-surface rhythm-tool-card">
      <div class="tool-heading"><div><p class="eyebrow">DICE ROLLER</p><h2>3d10 + Stat + Skill</h2></div></div>
      <p class="tool-explainer">Choose a Roll Type, then the valid Character Stat. Skills only turn on for roll types that use a Skill.</p>
      <aside class="fortune-tip"><strong>Fortune &amp; Misfortune</strong><span>Natural dice of 8–10 create Fortune results and natural dice of 1–2 create Misfortune results. Fortune represents an advantageous twist and may create a +1 Condition where the rule allows; Misfortune represents a complication and may create a −1 Condition.</span></aside>
      <div class="rhythm-dependent-grid"><label class="field-label">Roll Type<select v-model="rollType" class="field-control"><option v-for="option in rollTypes" :key="option">{{ option }}</option></select></label><label class="field-label">{{ statFieldLabel }}<select v-if="selectedCharacter" v-model="characterStatKey" class="field-control"><option v-for="stat in statOptions" :key="stat.key" :value="stat.key">{{ statOptionLabel(stat) }}</option></select><input v-else v-model.number="rhythmStat" class="field-control" type="number" /></label><label class="field-label" :class="{'field-off':!rollUsesSkill}">{{ rollUsesSkill?skillFieldLabel:'Skill (Off)' }}<select v-if="rollUsesSkill&&selectedCharacter" v-model="rhythmSkill" class="field-control"><option value="">No Skill</option><option v-for="skill in characterSkillOptions" :key="skill.name" :value="skill.name">{{ skill.name }} Rank {{ skill.rank }} +{{ skillModifier(skill.rank) }}</option></select><input v-else-if="rollUsesSkill" v-model.number="rhythmSkillBonus" class="field-control" type="number" placeholder="Skill Bonus" /><div v-else class="field-control disabled-readout">Off</div></label></div>
      <div class="rhythm-target-row"><label class="field-label rhythm-style-field">Roll Style<select v-model="rhythmMode" class="field-control"><option value="normal">Normal 3d10</option><option value="edged">Edged 4d10, Drop Lowest</option><option value="weighted">Weighted 4d10, Drop Highest</option></select></label><label class="field-label conditions-short-field">Conditions<input v-model.number="rhythmConditions" class="field-control" type="number" /></label><label class="field-label target-type-field">Target Type<select v-model="targetMode" class="field-control"><option value="none">No Target</option><option value="passive">Passive</option><option value="active">Active</option></select></label><label v-if="targetMode==='passive'" class="field-label target-value-field">Passive Target<select v-model.number="passiveTarget" class="field-control"><option v-for="target in passiveTargets" :key="target[0]" :value="target[1]">{{ target[0] }} {{ target[1] }}</option></select></label><label v-else-if="targetMode==='active'" class="field-label target-value-field">Active Target<input v-model.number="activeTarget" class="field-control" type="number" min="0" placeholder="Enter Target" /></label></div>
      <div class="roll-formula-summary"><strong>{{ rollSummary }}</strong></div><button class="primary-button wide" @click="rollAttributeCheck">Roll {{ rollType }}</button>
      <div class="sim-history-heading"><div><strong>Recent Rolls</strong><small>The latest five rolls are kept on this device.</small></div></div><div v-if="rhythmHistory.length" class="rhythm-history-list"><article v-for="(entry,index) in rhythmHistory" :key="entry.id" class="result-panel rhythm-history-entry" :class="{latest:index===0}"><div class="result-meta"><span>{{ formatTime(entry.createdAt) }}</span><span>{{ entry.rollType }}</span><span>{{ entry.mode }}</span><span v-if="entry.target!==null">{{ entry.targetLabel }} {{ entry.target }}</span></div><div class="dice-row"><span v-for="(value,dieIndex) in entry.result.rolled" :key="dieIndex" class="die" :class="{fortune:value>=8,misfortune:value<=2}">{{ value }}</span></div><div class="result-summary"><strong class="result-total">{{ entry.result.total }}</strong><span v-if="entry.target!==null" class="outcome" :class="entry.result.total>=entry.target?'pass':'fail'">{{ rollOutcome(entry) }}</span></div><div v-if="entry.fortunes||entry.misfortunes" class="special-result-row"><span v-if="entry.fortunes" class="special-result fortune-result">Fortune ×{{ entry.fortunes }}</span><span v-if="entry.misfortunes" class="special-result misfortune-result">Misfortune ×{{ entry.misfortunes }}</span></div><small>{{ entry.result.natural }} natural + {{ entry.stat }} Stat<template v-if="entry.skillName"> + {{ entry.skillBonus }} {{ entry.skillName }}</template> {{ entry.conditions>=0?'+':'−' }} {{ Math.abs(entry.conditions) }} Conditions</small></article></div><div v-else class="empty-inline sim-empty-inline">No rolls yet.</div>
    </section>

    <section v-else-if="sheet==='encounter'" class="encounter-builder-shell">
      <section class="encounter-builder-heading card-surface"><div><p class="eyebrow">ENCOUNTER BUILDER</p><h2>{{ encounterDraft.name||'New Encounter' }}</h2><p>Build a reusable encounter from the current character roster and Watcher creature catalog.</p></div><button type="button" class="secondary-button" @click="newEncounter">New Encounter</button></section>
      <div class="segment-tabs encounter-step-tabs" role="tablist" aria-label="Encounter creation steps"><button v-for="step in encounterSteps" :key="step" type="button" class="segment-tab" :class="{active:encounterStep===step}" @click="setEncounterStep(step)">{{ step }}</button></div>
      <section v-if="encounterStep==='Details'" class="tool-panel card-surface encounter-step-panel"><div class="tool-heading"><div><p class="eyebrow">STEP 1</p><h2>Encounter Details</h2></div></div><div class="field-grid two"><label class="field-label">Encounter Name<input v-model="encounterDraft.name" class="field-control" placeholder="Beneath the Rootbridge" /></label><label class="field-label">Objective<input v-model="encounterDraft.objective" class="field-control" placeholder="Protect the crossing, recover a relic, escape…" /></label></div><div class="encounter-step-actions"><button type="button" class="primary-button" @click="setEncounterStep('Party')">Next: Party</button></div></section>
      <section v-else-if="encounterStep==='Party'" class="tool-panel card-surface encounter-step-panel"><div class="tool-heading"><div><p class="eyebrow">STEP 2</p><h2>Party</h2></div><strong>Group Threat {{ encounterGroupThreat }}</strong></div><p>Select the saved heroes taking part in this encounter.</p><div class="encounter-choice-grid"><label v-for="character in characters" :key="character.id" class="encounter-choice-card"><input type="checkbox" :checked="encounterDraft.partyCharacterIds.includes(character.id)" @change="toggleEncounterParty(character.id,($event.target as HTMLInputElement).checked)" /><span><strong>{{ character.name }}</strong><small>{{ character.species }} · TL {{ threatForCharacter(character) }}</small></span></label></div><p v-if="!characters.length" class="muted">No complete saved characters are available yet.</p><div class="encounter-step-actions"><button type="button" class="secondary-button" @click="setEncounterStep('Details')">Back</button><button type="button" class="primary-button" @click="setEncounterStep('Opposition')">Next: Opposition</button></div></section>
      <section v-else-if="encounterStep==='Opposition'" class="tool-panel card-surface encounter-step-panel"><div class="tool-heading"><div><p class="eyebrow">STEP 3</p><h2>Opposition</h2></div><strong>{{ encounterOpponentTotal }} creatures</strong></div><div class="encounter-opponent-add"><label class="field-label">Creature<select v-model="opponentName" class="field-control"><option value="">Select Creature</option><optgroup v-for="category in Array.from(new Set(encounterMonsterOptions.map(monster=>monster.category)))" :key="category" :label="category"><option v-for="monster in encounterMonsterOptions.filter(item=>item.category===category)" :key="monster.name" :value="monster.name">{{ monster.name }}{{ monster.placeholder?' — Placeholder':'' }}</option></optgroup></select></label><label class="field-label">Quantity<input v-model.number="opponentQuantity" class="field-control" type="number" min="1" /></label><button type="button" class="primary-button" :disabled="!opponentName" @click="addEncounterOpponent">Add</button></div><div v-if="encounterDraft.opponents.length" class="encounter-opponent-list"><article v-for="(opponent,index) in encounterDraft.opponents" :key="`${opponent.name}-${index}`"><div><strong>{{ opponent.name }}</strong><small>Quantity {{ opponent.quantity }}</small></div><button type="button" class="secondary-button compact-action" @click="removeEncounterOpponent(index)">Remove</button></article></div><p v-else class="muted">No opposition selected.</p><div class="encounter-step-actions"><button type="button" class="secondary-button" @click="setEncounterStep('Party')">Back</button><button type="button" class="primary-button" @click="setEncounterStep('Battlefield')">Next: Battlefield</button></div></section>
      <section v-else-if="encounterStep==='Battlefield'" class="tool-panel card-surface encounter-step-panel"><div class="tool-heading"><div><p class="eyebrow">STEP 4</p><h2>Battlefield</h2></div></div><label class="field-label">Environment<textarea v-model="encounterDraft.environment" class="field-control encounter-textarea" rows="4" placeholder="Terrain, hazards, light, elevation, cover, starting positions…"></textarea></label><label class="field-label">Watcher Notes<textarea v-model="encounterDraft.notes" class="field-control encounter-textarea" rows="5" placeholder="Triggers, reinforcements, special rules, rewards, or reminders…"></textarea></label><div class="encounter-step-actions"><button type="button" class="secondary-button" @click="setEncounterStep('Opposition')">Back</button><button type="button" class="primary-button" @click="setEncounterStep('Review')">Next: Review</button></div></section>
      <section v-else class="tool-panel card-surface encounter-step-panel encounter-review-panel"><div class="tool-heading"><div><p class="eyebrow">STEP 5</p><h2>Review Encounter</h2></div></div><div class="review-grid review-summary-grid encounter-review-grid"><article><span>Name</span><strong>{{ encounterDraft.name||'Untitled Encounter' }}</strong><small>{{ encounterDraft.objective||'No objective recorded' }}</small></article><article><span>Party</span><strong>{{ encounterParty.length }} characters</strong><small>Group Threat {{ encounterGroupThreat }}</small></article><article><span>Opposition</span><strong>{{ encounterOpponentTotal }} creatures</strong><small>{{ encounterDraft.opponents.map(item=>`${item.quantity}× ${item.name}`).join(' · ')||'None selected' }}</small></article><article><span>Battlefield</span><strong>{{ encounterDraft.environment?'Prepared':'Open' }}</strong><small>{{ encounterDraft.environment||'No environment notes' }}</small></article></div><div class="encounter-step-actions"><button type="button" class="secondary-button" @click="setEncounterStep('Battlefield')">Back</button><button type="button" class="primary-button" @click="saveEncounterDraft">Save Encounter</button></div><p v-if="encounterSaveMessage" class="encounter-save-message">{{ encounterSaveMessage }}</p></section>
      <section class="saved-encounters card-surface"><header><div><p class="eyebrow">SAVED</p><h2>Encounter List</h2></div><span>{{ encounters.length }}</span></header><div v-if="encounters.length" class="saved-encounter-list"><article v-for="encounter in encounters" :key="encounter.id"><div><strong>{{ encounter.name }}</strong><small>{{ encounter.partyCharacterIds.length }} heroes · {{ encounter.opponents.reduce((sum,item)=>sum+item.quantity,0) }} creatures</small></div><div class="saved-encounter-actions"><button type="button" class="secondary-button compact-action" @click="editEncounter(encounter)">Edit</button><button type="button" class="secondary-button compact-action danger" @click="removeSavedEncounter(encounter.id)">Delete</button></div></article></div><p v-else class="muted">No encounters saved yet.</p></section>
    </section>

    <section v-else class="character-sheet-view">
      <section v-if="selectedCharacter" class="digital-character-sheet card-surface review-character-sheet">
        <details class="review-section review-collapsible character-detail-section" open><summary><h2>Character Detail</h2><span>Identity &amp; origin</span></summary><div class="review-collapsible-body character-detail-body"><div class="field-grid two review-identity-edit"><label class="field-label review-name-field">Character Name<div class="field-control disabled-readout">{{ selectedCharacter.name }}</div></label><label class="field-label review-name-field">Campaign<div class="field-control disabled-readout">{{ selectedCharacter.campaignName||'No Campaign' }}</div></label></div><div class="review-grid review-summary-grid"><article><span>Species</span><strong>{{ selectedCharacter.species||'Not selected' }} <small v-if="isCustomSpecies(selectedCharacter.species)" class="custom-content-badge">CUSTOM</small></strong><small>{{ selectedCharacter.languages?.[0]||'—' }}</small></article><article><span>Spark</span><strong>{{ selectedCharacter.spark||'—' }}</strong></article><article><span>Homeland</span><strong>{{ selectedCharacter.homeland||'—' }}</strong></article><article><span>Oath</span><strong>{{ selectedCharacter.oath||'—' }}</strong></article><article><span>Faith</span><strong>{{ selectedCharacter.faith||'—' }}</strong></article><article><span>Path</span><strong>{{ selectedPathName }}</strong></article><article><span>Languages</span><strong>{{ selectedCharacter.languages?.join(' · ')||'—' }}</strong></article><article><span>Threat Level</span><strong>TL {{ selectedThreatLevel }}</strong></article></div></div></details>
        <details class="review-section review-collapsible character-sheet-attributes" open><summary><h2>Attributes</h2><span>Ranks &amp; secondary stats</span></summary><div class="review-collapsible-body"><CharacterAttributePanel v-if="secondaryStats" :attributes="selectedCharacter.attributes" :magic-level="magicLevel" :guts-bonus="gearGutsBonus" :control-bonus="gearControlBonus" :magic-regen-bonus="gearMagicRegenBonus" :armor-penalty="gearSpeedPenalty" :minimum-speed="minimumSpeed" /></div></details>
        <details class="review-section review-collapsible review-weapons-section" open><summary><h2>Weapons</h2><span>{{ weapons.length }} equipped</span></summary><div class="review-collapsible-body equipment-slot-sheet"><div class="equipment-slot-header weapon-slot-grid"><span>Weapon</span><span>Damage</span><span>Range</span><span>Properties / Notes</span><span>Wt.</span></div><div v-for="(slot,index) in weaponSlots" :key="`weapon-slot-${index}`" class="equipment-slot-row weapon-slot-grid"><strong>{{ slot.name }}</strong><span>{{ slot.damage }}</span><span>{{ slot.range }}</span><span class="keyword-pill-row equipment-quality-cell"><span v-for="property in weaponPropertyPills(slot.properties)" :key="property" class="keyword-pill">{{ property }}</span><span v-if="!weaponPropertyPills(slot.properties).length">—</span></span><span>{{ slot.weight }}</span></div></div></details>
        <details class="review-section review-collapsible review-armor-section" open><summary><h2>Armor &amp; Shield</h2><span>{{ armor.length }} / 2 protective slots</span></summary><div class="review-collapsible-body"><div class="equipment-slot-sheet"><div class="equipment-slot-header armor-slot-grid"><span>Armor / Shield</span><span>Guts</span><span>Mana Syphon</span><span>Armor Penalty</span><span>Might</span><span>Wt.</span></div><div v-for="(slot,index) in armorSlots" :key="`armor-slot-${index}`" class="equipment-slot-row armor-slot-grid"><strong>{{ slot.name }}</strong><span>{{ slot.guts }}</span><span>{{ slot.mana }}</span><span>{{ slot.armorPenalty }}</span><span>{{ slot.might }}</span><span>{{ slot.weight }}</span></div></div><div class="trinket-slot-sheet"><h3>Trinkets</h3><div v-if="equippedTrinkets.length" class="trinket-slot-grid"><article v-for="(item,index) in equippedTrinkets" :key="`${item.name}-${index}`" class="trinket-slot-card"><strong>{{ item.name }}</strong><small>{{ item.effect || item.detail || 'Passive trinket effect.' }}</small></article></div><p v-else class="muted">No trinkets equipped.</p></div></div></details>
        <details class="review-section review-collapsible character-sheet-content-section"><summary><h2>Skills</h2><span>{{ selectedSkills.length }} recorded</span></summary><div class="review-collapsible-body"><div v-if="selectedSkills.length" class="review-skill-grid"><article v-for="skill in selectedSkills" :key="skill.name" class="review-skill-sheet-row"><div><strong>{{ skill.name }}</strong></div><div class="review-skill-values"><strong>Rank {{ skill.rank }}</strong><small>Modifier +{{ skillModifier(skill.rank) }}</small></div></article></div><p v-else class="muted">No Skills recorded.</p></div></details>
        <details v-if="magicLevel>0" class="review-section review-collapsible character-sheet-content-section"><summary><h2>Magic</h2><span>{{ selectedCharacter.loreAttunement||'Not selected' }} · {{ maxMana }} Mana Pool</span></summary><div class="review-collapsible-body"><article class="review-feature-box lore"><strong>Lore of {{ selectedCharacter.loreAttunement||'—' }}</strong><span>{{ loreDescriptions[selectedCharacter.loreAttunement||'']||'No Lore selected.' }}</span></article><h3 class="review-subheading">Lore Spells</h3><div class="review-spell-column"><article v-for="spell in loreCharacterSpells" :key="spell" class="review-feature-box spell full-rule-entry" :class="spellLoreClass(spell)"><header><strong>{{ spell }} <small v-if="isCustomSpell(spell)" class="custom-content-badge">CUSTOM</small></strong><small>{{ spellCostText(spell) }}</small></header><div class="keyword-pill-row"><span v-for="keyword in abilityFeaturePillKeywords(spellDetail(spell)?.keywords)" :key="keyword" :class="abilityFeaturePillClass(keyword)">{{ abilityFeaturePillLabel(keyword) }}</span></div><span>{{ spell===signatureSpell?'Signature Spell · ':'' }}{{ spellDetail(spell)?.lore }}</span><p v-if="spellDetail(spell)?.flavor" class="rule-flavor"><em>{{ spellDetail(spell)?.flavor }}</em></p><div v-if="visibleRuleFields(spellDetail(spell)?.rules||'').length" class="rule-breakdown-grid"><div v-for="field in visibleRuleFields(spellDetail(spell)?.rules||'')" :key="field.label"><small>{{ field.label }}</small><span>{{ field.value }}</span></div></div></article><p v-if="!loreCharacterSpells.length" class="muted">No Lore Spells recorded.</p></div><h3 class="review-subheading">Invocation Spells</h3><div class="review-spell-column"><article v-for="spell in invocationCharacterSpells" :key="spell" class="review-feature-box spell full-rule-entry" :class="spellLoreClass(spell)"><header><strong>{{ spell }} <small v-if="isCustomSpell(spell)" class="custom-content-badge">CUSTOM</small></strong><small>{{ spellCostText(spell) }}</small></header><div class="keyword-pill-row"><span v-for="keyword in abilityFeaturePillKeywords(spellDetail(spell)?.keywords)" :key="keyword" :class="abilityFeaturePillClass(keyword)">{{ abilityFeaturePillLabel(keyword) }}</span></div><span>{{ spellDetail(spell)?.lore }}</span><p v-if="spellDetail(spell)?.flavor" class="rule-flavor"><em>{{ spellDetail(spell)?.flavor }}</em></p><div v-if="visibleRuleFields(spellDetail(spell)?.rules||'').length" class="rule-breakdown-grid"><div v-for="field in visibleRuleFields(spellDetail(spell)?.rules||'')" :key="field.label"><small>{{ field.label }}</small><span>{{ field.value }}</span></div></div></article><p v-if="!invocationCharacterSpells.length" class="muted">No Invocation Spells recorded.</p></div></div></details>
        <details class="review-section review-collapsible character-sheet-content-section"><summary><h2>Talents</h2><span>{{ selectedCharacter.talents?.length||0 }} selected</span></summary><div class="review-collapsible-body review-box-list review-talent-column"><article v-for="talent in selectedCharacter.talents||[]" :key="talent" class="review-feature-box talent full-rule-entry" :class="talentAbilityClasses(talent)"><header><strong>{{ canonicalTalentName(talent) }} <small v-if="isCustomTalent(talent)" class="custom-content-badge">CUSTOM</small></strong></header><div class="keyword-pill-row"><span v-for="keyword in abilityFeaturePillKeywords(talentKeywords(talent))" :key="keyword" :class="abilityFeaturePillClass(keyword)">{{ abilityFeaturePillLabel(keyword) }}</span></div><p v-if="structuredRule(talentText(talent)).intro" class="rule-flavor"><em>{{ structuredRule(talentText(talent)).intro }}</em></p><div v-if="visibleRuleFields(talentText(talent)).length" class="rule-breakdown-grid"><div v-for="field in visibleRuleFields(talentText(talent))" :key="field.label"><small>{{ field.label }}</small><span>{{ field.value }}</span></div></div></article><p v-if="!selectedCharacter.talents?.length">No Talents selected.</p></div></details>
        <details class="review-section review-collapsible character-sheet-content-section"><summary><h2>Equipment &amp; Gear</h2><span>{{ otherGear.length }} items</span></summary><div class="review-collapsible-body"><div v-if="otherGear.length" class="review-equipment-grid"><article v-for="(item,index) in otherGear" :key="`${item.name}-${index}`"><strong>{{ item.name }}</strong><small><template v-if="item.category!=='Adventure Kit'">{{ item.category||'Gear' }} · </template>{{ formatThreadpieceWp(canonicalGearCostWp(item)) }}</small><p v-if="item.category!=='Adventure Kit'&&'detail' in item&&item.detail">{{ item.detail }}</p><p v-if="item.effect">{{ item.effect }}</p><small v-if="item.choice">Choice: {{ item.choice }}</small><small v-if="item.attachedTo">Attached to: {{ item.attachedTo }}</small></article></div><p v-else class="muted">No additional equipment purchased.</p></div></details>
      </section>
      <section v-else class="empty-state card-surface"><h2>Select a Character</h2><p>Choose a saved character above to open the Character Sheet.</p></section>
    </section>
  </main>
</template>

<style scoped>
.custom-content-badge{display:inline-flex;align-items:center;margin-left:5px;padding:2px 5px;border:1px solid #7b4f8d;border-radius:999px;background:#efe5f4;color:#60336f;font-size:8px;font-weight:900;letter-spacing:.06em;vertical-align:middle}.rhythm-sheet-tabs{margin-bottom:8px}.character-selection-panel{display:grid;grid-template-columns:minmax(0,1fr) auto;align-items:end;gap:12px;margin-bottom:12px;padding:10px 12px}.character-selection-summary{display:grid;gap:2px;text-align:right}.character-selection-summary span{color:var(--ink-soft);font-size:calc(9px + var(--font-offset))}.fortune-tip{display:grid;gap:4px;margin:12px 0;padding:10px 12px;border:1px solid var(--line);border-left:5px solid var(--accent);border-radius:9px;background:var(--paper-2)}.fortune-tip strong{font-family:Georgia,'Times New Roman',serif}.fortune-tip span{color:var(--ink-soft);line-height:1.5}.field-off{opacity:.68}.disabled-readout{display:flex;align-items:center;background:var(--paper-2);color:var(--ink-soft);cursor:not-allowed}.review-character-sheet{display:grid;gap:10px;padding:12px;min-width:0;max-width:100%;overflow:hidden}.review-character-sheet>*{min-width:0;max-width:100%}.review-character-sheet>.review-section{width:100%;box-sizing:border-box;min-width:0}.character-detail-body{display:grid;gap:10px}.character-detail-body .review-summary-grid{margin-top:0}.equipment-slot-sheet{display:block;max-width:100%;overflow-x:auto}.weapon-slot-grid{min-width:620px}.armor-slot-grid{min-width:720px}.rhythm-dependent-grid,.rhythm-target-row{row-gap:12px}.rhythm-target-row{margin-top:12px}.roll-formula-summary{margin-top:12px}.rhythm-tool-card .tool-explainer{margin-bottom:10px}
.character-sheet-content-section>.review-collapsible-body{padding-top:16px}
.trinket-slot-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:10px}.trinket-slot-card{display:grid;gap:4px;padding:10px;border:1px solid var(--line);border-radius:10px;background:var(--paper-2)}
.encounter-builder-shell{display:grid;gap:12px}.encounter-builder-heading{display:flex;align-items:flex-start;justify-content:space-between;gap:14px;padding:14px}.encounter-builder-heading h2{margin:0}.encounter-builder-heading p:last-child{margin:5px 0 0;color:var(--ink-soft)}.encounter-step-tabs{margin:0}.encounter-step-panel{display:grid;gap:12px}.encounter-step-actions{display:flex;justify-content:flex-end;gap:8px;flex-wrap:wrap}.encounter-choice-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:9px}.encounter-choice-card{display:flex;align-items:center;gap:9px;padding:10px;border:1px solid var(--line);border-radius:9px;background:var(--paper-2);cursor:pointer}.encounter-choice-card>span{display:grid;gap:2px}.encounter-choice-card small{color:var(--ink-soft)}.encounter-opponent-add{display:grid;grid-template-columns:minmax(0,1fr) 110px auto;align-items:end;gap:9px}.encounter-opponent-list,.saved-encounter-list{display:grid;gap:8px}.encounter-opponent-list>article,.saved-encounter-list>article{display:flex;align-items:center;justify-content:space-between;gap:10px;padding:10px;border:1px solid var(--line);border-radius:9px;background:var(--paper-2)}.encounter-opponent-list>article>div,.saved-encounter-list>article>div:first-child{display:grid;gap:2px}.encounter-opponent-list small,.saved-encounter-list small{color:var(--ink-soft)}.encounter-textarea{min-height:92px;resize:vertical}.encounter-review-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.encounter-save-message{margin:0;padding:9px 10px;border-left:4px solid var(--detail-trait-heritage);background:var(--paper-2)}.saved-encounters{padding:12px}.saved-encounters>header{display:flex;align-items:center;justify-content:space-between;gap:10px;margin-bottom:9px}.saved-encounters h2{margin:0}.saved-encounters>header>span{font-weight:900}.saved-encounter-actions{display:flex;gap:6px}.saved-encounter-actions .danger{border-color:color-mix(in srgb,var(--detail-deed) 58%,var(--line));color:var(--detail-deed)}@media(max-width:720px){.encounter-builder-heading{flex-direction:column}.encounter-choice-grid,.encounter-review-grid{grid-template-columns:1fr}.encounter-opponent-add{grid-template-columns:1fr 90px}.encounter-opponent-add>.primary-button{grid-column:1/-1}.encounter-step-tabs{overflow-x:auto;justify-content:flex-start}.saved-encounter-list>article{align-items:flex-start;flex-direction:column}.saved-encounter-actions{width:100%}.saved-encounter-actions button{flex:1}}

</style>
