import assert from 'node:assert/strict'
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..')
const read=(relative)=>fs.readFileSync(path.join(root,relative),'utf8')
const exists=(relative)=>fs.existsSync(path.join(root,relative))
const walk=(dir)=>fs.readdirSync(dir,{withFileTypes:true}).flatMap(entry=>entry.isDirectory()?walk(path.join(dir,entry.name)):[path.join(dir,entry.name)])
const sourceFiles=walk(path.join(root,'src')).filter(file=>/\.(?:ts|vue|css)$/.test(file))
const sourceText=sourceFiles.map(file=>[path.relative(root,file),fs.readFileSync(file,'utf8')])

const release=read('src/data/release.ts')
const app=release.match(/APP_RELEASE='([^']+)'/)?.[1]
const pkgRelease=release.match(/PACKAGE_RELEASE='([^']+)'/)?.[1]
const game=release.match(/GAME_UPDATES_RELEASE='([^']+)'/)?.[1]
assert.ok(app&&pkgRelease&&game,'release.ts must expose all canonical release markers')
const pkg=JSON.parse(read('package.json'))
assert.equal(pkg.version,pkgRelease,'package.json version must match PACKAGE_RELEASE')
assert.equal(pkgRelease,`${app}.0`,'package release must derive from app release')
assert.match(read('public/sw.js'),new RegExp(`brambleheart-shell-v${app.replaceAll('.','\\.')}`),'PWA cache must match app release')
assert.ok(read('CHANGELOG.md').startsWith(`# Brambleheart Beta ${app}`),'CHANGELOG current entry must match app release')
assert.match(read('README.md'),new RegExp(`Beta ${app.replaceAll('.','\\.')}`),'README current Site Update must match app release')
assert.match(read('README.md'),new RegExp(`Game Update[^\n]*v${game.replaceAll('.','\\.')}`),'README current Game Update must match game release')
assert.match(read('PATCH_NOTES.md'),new RegExp(`Beta ${app.replaceAll('.','\\.')}`),'PATCH_NOTES current Site Update must match app release')
assert.match(read('PATCH_NOTES.md'),new RegExp(`v${game.replaceAll('.','\\.')}`),'PATCH_NOTES current Game Update must match game release')
assert.match(read('public/downloads/Brambleheart-Cloud-Instructions.txt'),new RegExp(`Beta ${app.replaceAll('.','\\.')}`),'downloadable cloud instructions must match app release')
const manifest=read('public/manifest.webmanifest')
const router=read('src/router.ts')
const installSupport=read('src/state/install.ts')
const indexHtml=read('index.html')
assert.match(manifest,/"id": "\/"[\s\S]{0,80}"start_url": "\/news"/,'Installed app identity must remain stable while launching into News')
assert.match(router,/path:'\/',redirect:'\/news'/,'Root launch route must open News so existing installs using the old root start URL also land on News')
for(const asset of ['manifest.webmanifest','icon-192.png','icon-512.png','icon-maskable-512.png','apple-touch-icon.png'])assert.ok(indexHtml.includes(asset)||manifest.includes(asset),`Install asset reference missing: ${asset}`)
assert.ok(indexHtml.includes(`manifest.webmanifest?v=${app}`),'Document manifest URL must be release-versioned')
assert.ok(manifest.includes(`icon-192.png?v=${app}`)&&manifest.includes(`icon-512.png?v=${app}`),'Installed-app icons must use release-versioned URLs')
assert.match(installSupport,/window\.addEventListener\('load'[\s\S]{0,700}refreshInstallMetadata\(\)[\s\S]{0,700}registration\.update\(\)/,'Install metadata and service-worker updates must run when Brambleheart is opened')
assert.match(installSupport,/fetch\(`\$\{path\}\?v=\$\{APP_RELEASE\}`,[^)]*cache:'reload'/,'Open-app install metadata refresh must bypass stale browser cache')
assert.doesNotMatch(installSupport,/setInterval|periodicSync|sync\.register/,'Installed-app update checks must not add background polling or sync')

const changelog=read('CHANGELOG.md')
const changelogReleases=[...changelog.matchAll(/^# Brambleheart Beta ([0-9.]+)/gm)].map(match=>match[1])
assert.deepEqual(changelogReleases,['0.12','0.11','0.10'],'Site Update history must retain the condensed three-release history')
let activeCategory='';let categoryCount=0
for(const line of changelog.split(/\r?\n/)){
  if(line.startsWith('## ')){if(activeCategory)assert.ok(categoryCount<=12,`${activeCategory} exceeds the 12-log category maximum`);activeCategory=line.slice(3).trim();categoryCount=0}
  else if(line.startsWith('- ')&&activeCategory)categoryCount++
}
if(activeCategory)assert.ok(categoryCount<=12,`${activeCategory} exceeds the 12-log category maximum`)
for(const gameRuleText of ['Wounded Health range to 5–7','Sapguard [+1]','Vinegrip [+2]','Ironwood Bulwark [+3]','Driftwood Charm','Sea of Roots','7–10 XP','Tordan Steady Pace'])assert.equal(changelog.includes(gameRuleText),false,`Game-rule history must not be duplicated in Site Changelog: ${gameRuleText}`)
for(const removed of ['Rebuilds Site Update history into five categorized releases','Consolidates the historical Site Update/package/export/PWA metadata','Reworks the News social area into Discord, Share, and Creator Content actions'])assert.equal(changelog.includes(removed),false,`Retired changelog boilerplate remains: ${removed}`)
const gameUpdatesSource=read('src/data/gameUpdates.ts')
assert.match(gameUpdatesSource,/version:GAME_RULES_VERSION[\s\S]{0,180}title:'Launch Patch'/,'The single current Game Update must derive from the canonical release marker')
assert.equal((gameUpdatesSource.match(/\n    version:/g)||[]).length,1,'Game Update history must contain one canonical v0.01 Launch Patch entry')
assert.doesNotMatch(gameUpdatesSource,/version:'0\.02'|title:'Dual Wielding & Sapguard'/,'The former v0.02 entry must be consolidated into the Launch Patch')
assert.match(gameUpdatesSource,/Mana Syphon \[\+1\][\s\S]{0,700}Sapguard/,'The Launch Patch must include both approved dual-wielding and Sapguard changes')
assert.match(gameUpdatesSource,/Scriptweave Book[\s\S]{0,1000}Durtlehide/,'Launch Patch must include the bound-equipment rules')
for(const gameRuleText of ['Sea of Roots','Driftwood Charm','7–10 XP','Tordan Steady Pace','Sapguard','Vinegrip','Ironwood Bulwark','Wounded covers [5–7] Health'])assert.ok(gameUpdatesSource.includes(gameRuleText),`Launch Patch missing consolidated game rule: ${gameRuleText}`)
assert.doesNotMatch(gameUpdatesSource,/version:'0\.(?:04|06|07|10|12|13|14)'/,'archived Game Update versions must not remain as parallel entries')
assert.doesNotMatch(read('src/views/SettingsView.vue'),/archived Game Updates/,'Settings must not advertise archived Game Updates after consolidation')

assert.equal(exists('style-audit.html'),false,'Temporary style audit artifacts must not be committed')
assert.doesNotMatch(read('src/styles.css'),/semantic-collapsible/,'Superseded style-repair override must not remain')

for(const obsolete of ['src/data/equipmentNormalization.ts','src/data/rulesSource.ts','src/data/beta032Content.ts','src/styles.beta032.css'])assert.equal(exists(obsolete),false,`${obsolete} must remain removed`)
for(const obsoleteAsset of ['src/assets/backgrounds/Blightbound Horror.png','src/assets/page-headers/rules.png.png'])assert.equal(exists(obsoleteAsset),false,`${obsoleteAsset} must remain removed`)

const backgroundDir=path.join(root,'src/assets/backgrounds')
const backgroundIds=fs.readdirSync(backgroundDir).filter(name=>/\.(?:png|jpe?g|webp)$/i.test(name)).map(name=>name.replace(/\.[^.]+$/,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,''))
assert.equal(new Set(backgroundIds).size,backgroundIds.length,'background asset names must resolve to unique canonical ids')

for(const [file,text] of sourceText)assert.equal(text.includes('!important'),false,`${file} contains !important`)
for(const [file,text] of sourceText){if(file==='src/services/storage.ts')continue;assert.equal(/\blocalStorage\b/.test(text),false,`${file} bypasses the storage service`)}

const rules=read('src/data/rulesCurrent.ts')
const catalog=read('src/data/ruleCatalog.ts')
assert.equal(/['"]species-[a-z]+['"]\s*:/.test(rules),false,'rulesCurrent must not duplicate Species documents')
assert.equal(/document\s*:\s*['"]species-/.test(catalog),false,'Species catalog pages must not point at duplicate source documents')
assert.match(rules,/current categories are Standard, Direct, and Lethal/i)
assert.match(rules,/On-Going is a recurring-damage qualifier/i)
assert.doesNotMatch(rules,/current categories are Standard, Direct, Lethal, and On-Going/i)
assert.match(rules,/A Deadly weapon lists damage as X \[Y\]/)
assert.match(rules,/Mana Syphon \[\+1\][\s\S]{0,260}reducing the Dual Wielding penalty to \[-1\]/,'Dual Wielding must apply Mana Syphon [+1] in the canonical rule')
assert.doesNotMatch(rules,/\"heading\": \"WARD GUARD\"/,'Ward Guard must be retired from current Talent rules')
assert.match(rules,/BEASTGRASP[\s\S]{0,700}total condition \[-4\]/)
assert.match(rules,/TURNSTRIKE[\s\S]{0,700}rounded up, to a minimum of \[\+1\]/)
assert.match(rules,/Cumulative from Rank 1/)
assert.match(rules,/Average XP per session:/)
assert.match(rules,/one smaller upgrade/i)
assert.match(rules,/two smaller upgrades or one larger upgrade/i)
assert.doesNotMatch(rules,/divide[^\n.]{0,80}by \[?6\]?/i,'obsolete six-Attribute Encounter Rating math remains in current rules')


const advancement=read('src/rules/advancementRules.ts')
assert.match(advancement,/averagePerSession:\[7,10\]/)
assert.match(advancement,/sparkAlignmentBonus:1/)
assert.match(rules,/Spark Alignment: Gain \[\+\$\{XP_GUIDANCE\.sparkAlignmentBonus\}\] bonus XP/)
assert.match(rules,/This bonus can be gained only once per session/)
assert.match(advancement,/if\(type==='attribute'\)return 4\+\(2\*rank\)/)
assert.match(advancement,/if\(type==='skill'\)return 4\+rank/)
assert.match(advancement,/if\(type==='new-skill'\)return 8/)
assert.match(advancement,/if\(type==='talent'\)return 12/)
assert.match(advancement,/if\(type==='magic'\)return 12\+\(4\*rank\)/)


const currentSkillSources=['src/data/speciesData.ts','src/data/bramble.ts','src/data/characterOptions.ts','src/data/creationRules.ts','src/data/rulesCurrent.ts','src/views/RuleReaderView.vue','src/views/SimulatorView.vue']
for(const file of currentSkillSources)assert.doesNotMatch(read(file),/Whisperster/,`${file} must use current Whisperstep terminology`)
assert.match(read('src/rules/rulesEngine.ts'),/Whisperster:'Whisperstep'/,'Rules normalization must accept legacy Whisperster and return Whisperstep')
assert.match(read('src/services/characters.ts'),/Whisperster:'Whisperstep'/,'Character persistence must migrate legacy Whisperster to Whisperstep')
const speciesSource=read('src/data/speciesData.ts')
assert.match(speciesSource,/STEADY_PACE_RULE=\{moveMaximumReduction:1,speedPenaltyReduction:2,minimumSpeed:2\}/)
assert.match(speciesSource,/Poised Reflex can be used only once per round/)
assert.match(speciesSource,/Double Lilly can be used only once per round/)
assert.match(speciesSource,/Cycle Of The Beast[\s\S]{0,700}health \[1\] or mana \[1\]/)
assert.match(speciesSource,/Thunderstep[\s\S]{0,700}maximum movement of Hero’s Charge by \[\+2\] squares/)
assert.match(speciesSource,/Thunderstep[\s\S]{0,900}suffers \[2\] lethal damage/)
assert.match(speciesSource,/Frostwalker[\s\S]{0,700}resistance \[\+2\] to Cold damage/)
assert.match(speciesSource,/Frostwalker[\s\S]{0,800}gain \[\+2\] Ward/)


const talentCategories=read('src/data/talentCategories.ts')
assert.match(talentCategories,/RETIRED_TALENTS=new Set\(\['Ward Guard','Rooted Paw','Rooted Paws'\]\)/)
assert.doesNotMatch(talentCategories,/assign\('Defensive',[^\n]*'Ward Guard'/)
for(const [category,name] of [['Utility','Bond Of Blades'],['Utility','Rhythm Of Blades'],['Utility','Sure Paw'],['Utility','Twin-Linked'],['Utility','Witch Hunter'],['Defensive','Spell Breaker'],['Offensive','Spell Cleave'],['Offensive','Shadow Fang']]){const categoryLine=talentCategories.split(/\r?\n/).find(line=>line.startsWith(`assign('${category}'`))||'';assert.ok(categoryLine.includes(`'${name}'`),`${name} must remain in ${category}`)}
assert.match(talentCategories,/['"]sure hand['"]:'Sure Paw'/,'Sure Hand compatibility must normalize to Sure Paw')
assert.match(talentCategories,/TALENT_TONE_OVERRIDES/,'Talent presentation must keep a stable tone authority separate from display pills')
for(const [name,tone] of [['Bond Of Blades','Touch'],["Hunter's Mark",'Shoot'],['Rhythm Of Blades','Touch'],['Pulse Of Attunement','Magic'],['Beastgrasp','Touch']])assert.ok(talentCategories.includes(`['${name}','${tone}']`)||talentCategories.includes(`["${name}",'${tone}']`),`${name} must preserve its established ${tone} presentation after keyword cleanup`)
assert.doesNotMatch(rules,/"heading": "ROOTED PAWS?"/,'Rooted Paw(s) must remain retired from current Talent rules')
assert.match(rules,/HEARTH TOUCH[\s\S]{0,800}One character affected by that spell gains condition \[\+1\] to their next Attribute Save until the end of the round/,'Hearth Touch must use the current effect')
assert.match(rules,/THREADSEER[\s\S]{0,900}Mana cost by \[\+3\]/,'Threadseer second Spell surcharge must be +3 Mana')
assert.match(rules,/KEEN EDGE[\s\S]{0,900}REQUIRES: Jumpstart Talent/,'Keen Edge must require Jumpstart')
assert.match(rules,/PACK TACTICS[\s\S]{0,500}COST: \[1\] Mana/,'Pack Tactics must cost 1 Mana')
assert.match(rules,/SECOND CHANCES[\s\S]{0,900}COOLDOWN: This Talent cannot be used again for \[1d10\/2\] rounds/,'Second Chances must use its cooldown')
assert.doesNotMatch(rules,/SECOND CHANCES[\s\S]{0,500}COST:/,'Second Chances must not retain a Mana cost')
assert.match(rules,/VICTORY ROAR[\s\S]{0,900}cannot be affected by multiple instances of Victory Roar from different sources/,'Victory Roar must prevent stacking from multiple sources')

const charOptions=read('src/data/characterOptions.ts')
const deadlyNames=['Shade Blade (Dagger)','Reedpipe (Blowpipe)']
for(const name of deadlyNames){
  const escaped=name.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')
  const block=charOptions.match(new RegExp(`"name": "${escaped}"[\\s\\S]{0,500}?"detail": "([^"]+)"`))
  assert.ok(block,`missing ${name}`)
  assert.match(block[1],/^\d+ \[\d+\].*Deadly/,`${name} must use bracketed Deadly damage`)
}
assert.match(charOptions,/"name": "Club"[\s\S]{0,300}?"detail": "3 ·/)
assert.match(charOptions,/"name": "Brush Blade \(Short Sword\)"[\s\S]{0,300}?"detail": "4 ·/)
assert.match(charOptions,/"name": "Stonebreaker \(Warhammer\)"[\s\S]{0,300}?"detail": "5 \(7\) ·/)
assert.match(charOptions,/"name": "Thornspike \(Dart\)"[\s\S]{0,300}?"detail": "2 ·[\s\S]{0,120}?Penetration/)


const links=read('src/data/links.ts')
assert.match(links,/creator:'https:\/\/linktr\.ee\/AndreavnnTheOmniKing'/,'Creator Content must use the approved Linktree URL')
assert.match(links,/discordWidget:'https:\/\/discord\.com\/api\/guilds\/960273711372566589\/widget\.json'/,'Brambleheart Discord widget must use the approved server id')
for(const id of ['440558048520568853','1541119933432332328'])assert.match(links,new RegExp(`discord\\.com/api/guilds/${id}/widget\\.json`),`Creator Discord widget missing: ${id}`)
const discordCommunity=read('src/services/discordCommunity.ts')
assert.match(discordCommunity,/approximate_member_count/,'Discord community service must resolve total membership from public invite counts')
assert.match(discordCommunity,/loadCreatorFollowerCount/,'Creator follower totals must have one shared service')
assert.match(discordCommunity,/Promise\.all/,'Creator follower count must combine the configured community sources')
const news=read('src/views/NewsView.vue')
assert.equal((news.match(/class="news-promo-card(?: [^"]*)? card-surface"/g)||[]).length,3,'News must present exactly three social promo buttons')
for(const label of ['Discord','Share','Creator Content'])assert.match(news,new RegExp(`<strong>${label}</strong>`),`News promo title missing: ${label}`)
assert.match(news,/discordCountLabel/,'Discord total must render on the News Discord button')
assert.match(news,/creatorFollowerLabel/,'Combined creator follower total must render on Creator Content')
assert.doesNotMatch(news,/online`| online|discordOnlineCount/,'News must not display the Discord online count')

// Current rules/presentation integrity.
const coreAbilities=read('src/data/coreAbilities.ts')
assert.match(coreAbilities,/ARCANE COMMAND[\s\S]{0,900}SECOND CAST[\s\S]{0,700}Enhance or Hex Spell[\s\S]{0,300}Mana cost by \[\+1\]/,'Arcane Command second-cast rule must remain canonical')
const abilityPresentation=read('src/rules/abilityPresentation.ts')
assert.match(abilityPresentation,/type==='Core'\?'CORE'/,'Core Action pills must render as CORE')
assert.doesNotMatch(abilityPresentation,/type==='Core'\?'CORE ACTION'/,'Core pill presentation must not revert to CORE ACTION')
assert.match(abilityPresentation,/canonical==='Cultural'\)return'Cultural'/,'Cultural trait pills must retain Cultural casing')
assert.match(abilityPresentation,/canonical==='Heritage'\)return'HERITAGE'/,'Heritage trait pills must render HERITAGE')
assert.doesNotMatch(abilityPresentation,/return['"]TRAIT['"]/,'Shared trait pills must not render TRAIT')
assert.match(rules,/Projectile \(X\)[\s\S]{0,250}within \[1\] square[\s\S]{0,120}\[-2\]/,'Projectile close-range rule must be current')
assert.match(rules,/Skyfire[\s\S]{0,160}additional \[2\] Lethal damage/,'Skyfire must use +2 Lethal rider')
assert.match(rules,/Slashing[\s\S]{0,220}suffers \[1\] Lethal damage/,'Slashing must use unprefixed [1] Lethal damage')
assert.match(rules,/Health falls to \[7\] or less[\s\S]{0,240}\[4\] or less[\s\S]{0,240}\[2\] or less/,'Health state thresholds must remain 7/4/2')
assert.match(rules,/FATE ROLL:[\s\S]{0,300}\[5[–-]10\][\s\S]{0,250}\[1[–-]4\][\s\S]{0,250}Fate Mark/,'Fate Roll procedure must remain current')
assert.doesNotMatch(rules,/CREATING A HOMELAND|CREATING A FAITH|CREATING AN OATH|Creating Your Own Spark|\"heading\": \"PREMADE SPARKS\"/,'retired or duplicated creation-reference sections must remain removed')
assert.doesNotMatch(rules,/TYPES OF THREADPIECES|WASHER PIECES|NUT PIECES|SCREW PIECES|BOLT PIECES/,'retired Threadpiece denomination prose must remain removed')
const ruleReader=read('src/views/RuleReaderView.vue')
for(const label of ['Sparks - List','Deed - List','Homeland - List','Faith - List','Oath - List','Advancement Charts','Adventuring Items','Health Points'])assert.match(ruleReader,new RegExp(label.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')),`Rule reader missing current label: ${label}`)
assert.match(ruleReader,/page\.slug==='encounters-threat-level'[\s\S]{0,5000}Group Threat/,'Building Encounters must render the Threat Level system')
assert.doesNotMatch(ruleReader,/Current Guidance|Design Status/,'Threat placeholder sections must remain removed')
assert.match(ruleReader,/Hallowing Thorns[\s\S]{0,300}Range \[5\][\s\S]{0,100}ORB\[3\]/,'Spell Range visual example must use the compact 3x3 area')
assert.doesNotMatch(ruleReader,/casting range of four squares/,'Hallowing Thorns accessibility text must match Range [5]')
const threat=read('src/rules/threatLevel.ts')
assert.match(threat,/THREAT_BANDS/,'Threat Level must have one structured band authority')
assert.match(threat,/characterThreatScore/,'Threat Level must expose a character score helper')
assert.match(threat,/groupThreat/,'Threat Level must expose a group helper')
assert.match(threat,/rank\)\|\|0\)-2\)\*2/,'Attribute Threat growth must be +2 per rank above 2')
assert.match(threat,/talentCount>0\?3\+Math\.max\(0,talentCount-1\)/,'Talent Threat must be +3 first and +1 additional')
assert.match(threat,/magicLevel>0\?3\+Math\.max\(0,magicLevel-1\)\*2/,'Magic Threat must be +3 first and +2 additional')
const createView=read('src/views/CreateCharacterView.vue')
const simulatorView=read('src/views/SimulatorView.vue')
const levelUpView=read('src/views/LevelUpView.vue')
const characterDetailSection=read('src/components/CharacterDetailSection.vue')
const rulePageLayout=read('src/components/RulePageLayout.vue')
const attributeRankControl=read('src/components/AttributeRankControl.vue')
assert.match(createView,/<template v-if="stepId==='species'">/,'Character Creation Species step must retain its Vue template wrapper')
assert.match(simulatorView,/<template v-if="entry\.characterName">\{\{ entry\.characterName \}\} · <\/template>/,'Recent Rolls character-name fragment must retain its Vue template wrapper')
for(const [file,text] of sourceText)assert.doesNotMatch(text,/default><p v-if="item\.description"/,`${file} contains the retired malformed template fragment`)
assert.match(createView,/Threat Level[\s\S]{0,120}currentThreatLevel/,'Creation character sheet must display Threat Level')
assert.match(characterDetailSection,/Threat Level · Point[\s\S]{0,240}threat\.level[\s\S]{0,180}threat\.total/,'Shared Character Detail must display Threat Level')
const speciesSheet=read('src/components/SpeciesRuleSheet.vue')
assert.doesNotMatch(speciesSheet,/<small>Expanded lore<\/small>|traits<\/small>/,'Species collapse summaries must not retain redundant right-side detail text')
const styles=read('src/styles.css')
assert.match(styles,/border-top-color:var\(--rule-tone,var\(--accent\)\)/,'shared RuleFeatureCard surfaces must preserve their tone accent')
const ruleCollapsible=read('src/components/RuleCollapsibleCard.vue')
assert.match(ruleCollapsible,/rule-feature-box rule-feature-card rule-collapsible-card/,'Semantic expandable Rules boxes must reuse the RuleFeature card authority')
assert.doesNotMatch(ruleReader,/organized-rule-category/,'RuleReader must not retain the superseded neutral semantic collapsible implementation')
const ruleFeatureCard=read('src/components/RuleFeatureCard.vue')
const equipmentCard=read('src/components/EquipmentCard.vue')
assert.match(ruleFeatureCard,/:is="collapsible\?'details':'article'"/,'RuleFeatureCard must own the shared collapsible surface instead of Equipment views duplicating card markup')
assert.match(ruleFeatureCard,/:is="collapsible\?'summary':'header'"/,'Collapsible RuleFeature cards must reuse the canonical header authority')
assert.match(equipmentCard,/collapsible:true/,'EquipmentCard must default to the compact collapsible presentation')
assert.match(equipmentCard,/:collapsible="collapsible"/,'EquipmentCard must delegate its expandable state to RuleFeatureCard')
const spellCard=read('src/components/SpellCard.vue')
assert.match(ruleReader,/<SpellCard[\s\S]{0,500}v-if="currentLoreSignatureSpell"[\s\S]{0,700}signature/,'Lore pages must render the Signature Spell through the shared SpellCard authority')
assert.match(ruleReader,/<RuleCollapsibleCard title="Lore Spells"[\s\S]{0,900}v-for="spell in currentLoreKnownSpells"/,'Lore pages must render remaining Lore Spells through the shared SpellCard authority')
assert.match(simulatorView,/<h3 class="review-subheading">Known Spells<\/h3>[\s\S]{0,900}<SpellCard v-for="spell in characterSpells"/,'Character Sheet must render Known Spells through the shared SpellCard authority')
assert.match(createView,/IndependentCardColumns :items="\[\.\.\.form\.spells,\.\.\.form\.invocationSpells\][\s\S]{0,500}<SpellCard/,'Character Creation must render selected Spells through the shared SpellCard authority')
assert.match(spellCard,/class="spell-card"[\s\S]{0,1800}class="mana-badge"[\s\S]{0,1800}rule-breakdown-grid[\s\S]{0,1800}keyword-pill-row/,'SpellCard must own the established header Mana badge, rule details, and keyword presentation')
assert.doesNotMatch(spellCard,/v-if="signature"[^>]*>SIGNATURE</,'Shared Spell titles must not append a duplicate SIGNATURE marker')
assert.match(spellCard,/costParts[\s\S]{0,900}primary[\s\S]{0,900}detail/,'SpellCard must split the primary Mana pill from its calculation detail')
assert.match(spellCard,/class="spell-card-costs"[\s\S]{0,260}class="mana-badge"[\s\S]{0,260}class="spell-cost-detail"/,'Spell Mana calculation detail must sit beneath the Mana badge in the shared Spell header')
assert.match(styles,/\.spell-card-costs\{display:grid;justify-items:end;/,'Spell cost stack must align to the right side of the shared Spell header')
assert.match(spellCard,/trinkets[\s\S]{0,1200}spell-trinket-pill/,'SpellCard must render attached Trinkets through the shared pill area')
assert.match(ruleReader,/RuleCollapsibleCard title="Cantrips"[\s\S]{0,900}v-for="spell in currentInvocationCantrips"[\s\S]{0,1400}RuleCollapsibleCard title="Invocations"[\s\S]{0,900}v-for="spell in currentInvocationSpells"/,'Invocation reference must separate Cantrips from Invocations')
assert.match(simulatorView,/spell-card-grid character-spell-column[\s\S]{0,700}v-for="spell in characterSpells"/,'Rhythm Character Sheet Spells must use the single-column modifier')
assert.match(styles,/\.spell-card-grid\{display:grid;grid-template-columns:repeat\(2,minmax\(0,1fr\)\)/,'Shared Spell card grids must retain the two-column layout outside Lore pages')
assert.match(styles,/\.lore-spell-card-grid,\.character-spell-column\{grid-template-columns:1fr;\}/,'Lore pages and Character Sheet Spells must force the shared Spell card grid to one column')
assert.match(styles,/@media\(max-width:760px\)\{\.spell-card-grid\{grid-template-columns:1fr;\}\}/,'Spell cards must collapse to one column on narrow screens')
assert.match(styles,/\.spell-card\{[^}]*border-top-width:7px[^}]*border-top-color:var\(--spell-lore/,'Spell cards must retain the established seven-pixel Lore edge')
assert.match(styles,/\.spell-card \.rule-breakdown-grid\{display:grid;grid-template-columns:1fr;gap:0/,'Spell rule details must retain the established inline row presentation')
for(const obsolete of ['spell-detail-card','review-spell-column','spell-collapsible','spell-rule-tone','review-feature-box spell'])assert.equal(sourceText.some(([,text])=>text.includes(obsolete)),false,`Superseded Spell presentation remains: ${obsolete}`)
const talentCard=read('src/components/TalentCard.vue')
assert.match(ruleReader,/IndependentCardColumns :items="group\.talents"[\s\S]{0,800}<TalentCard/,'Rules Talent list must render through the shared TalentCard authority inside independent columns')
assert.match(simulatorView,/<TalentCard v-for="talent in selectedCharacter\.talents\|\|\[\]"/,'Character Sheet Talents must render through the shared TalentCard authority')
assert.match(createView,/TalentCard v-for="talent in form\.talents\.filter\(Boolean\)"/,'Character Creation Talent surfaces must reuse the shared TalentCard authority')
assert.match(talentCard,/class="talent-detail-card full-rule-entry"[\s\S]{0,1800}talent-detail-head[\s\S]{0,1800}rule-breakdown-grid[\s\S]{0,1800}keyword-pill-row/,'TalentCard must own the established header, rule details, and keyword presentation')
assert.match(styles,/\.talent-detail-card\{--rule-tone:var\(--detail-talent\);padding:11px 12px;border-top-width:7px;\}/,'Talent cards must retain body padding and the established top edge')
assert.equal(sourceText.some(([,text])=>text.includes('review-feature-box talent')),false,'Superseded Character Sheet Talent presentation must not remain')
assert.match(speciesSheet,/RuleCollapsibleCard[\s\S]{0,1200}Heritage Traits[\s\S]{0,1800}Cultural Traits/,'Playable Species semantic menus must reuse the shared expandable card authority')
const attrPanel=read('src/components/CharacterAttributePanel.vue')
assert.match(attrPanel,/minimumSpeed\?:number/,'CharacterAttributePanel must declare minimumSpeed')
assert.match(attrPanel,/minimumSpeed:1/,'CharacterAttributePanel must default minimumSpeed to 1')

const bramble=read('src/data/bramble.ts')
assert.match(bramble,/name:'Sea of Roots', skills:\['Herbalry','Wayfinding'\]/,'Sea of Roots must be a canonical Homeland')
assert.match(charOptions,/"Sea of Roots": \{[\s\S]{0,700}"skills": \[[\s\S]{0,100}"Herbalry"[\s\S]{0,100}"Wayfinding"/,'Sea of Roots details must match the Homeland authority')
assert.match(charOptions,/"name": "Leafstitch"/,'Leafstitch must be the current armor spelling')
assert.doesNotMatch(charOptions,/"name": "Leafsitch"/,'Leafsitch must not remain a current equipment name')
assert.match(charOptions,/"name": "Driftwood Charm"[\s\S]{0,550}Once per round[\s\S]{0,220}restores Health[\s\S]{0,220}\[\+1\]/,'Driftwood Charm must retain its once-per-round healing bonus')
assert.match(charOptions,/"name": "Durtlehide"[\s\S]{0,600}elemental damage type[\s\S]{0,300}Resistance \[\+2\]/,'Durtlehide must retain its selected elemental Resistance rule')
assert.match(charOptions,/"name": "Scriptweave Book"[\s\S]{0,900}one known Lore Spell[\s\S]{0,500}"cooldown": "\[1d10\/2\+1\] rounds/,'Scriptweave Book must bind one Lore Spell and expose the current cooldown separately')
const economy=read('src/rules/economy.ts')
assert.match(economy,/Leafsitch:'Leafstitch'/,'Leafsitch compatibility must be isolated to the equipment alias boundary')
for(const [file,text] of sourceText)if(file!=='src/rules/economy.ts')assert.equal(/\bLeafsitch\b/.test(text),false,`${file} retains the obsolete Leafsitch spelling`)
assert.match(read('src/rules/rulesEngine.ts'),/equipmentHealingSpellBonus[\s\S]{0,300}Driftwood Charm/,'Driftwood Charm healing must have one shared rules-engine helper')
const rulesEngine=read('src/rules/rulesEngine.ts')
assert.match(rulesEngine,/equipmentResistanceBonus[\s\S]{0,260}Durtlehide[\s\S]{0,160}choice===damageType/,'Durtlehide Resistance must have one shared equipped-item authority')
assert.match(rulesEngine,/equipmentSpellManaReduction[\s\S]{0,260}Scriptweave Book[\s\S]{0,160}attachedTo===spellName/,'Scriptweave reduction must apply only to its selected Spell')
assert.match(rulesEngine,/dualWieldManaSyphon[\s\S]{0,260}category==='Weapon'[\s\S]{0,220}length>=2\?1:0/,'Dual wielding must have one canonical Mana Syphon helper')
assert.match(rulesEngine,/equipmentManaSyphon[\s\S]{0,380}dualWieldManaSyphon\(items\)/,'Equipment Mana Syphon must include the canonical dual-wielding surcharge')
const magicRules=read('src/rules/magicRules.ts')
assert.match(magicRules,/SCRIPTWEAVE_COOLDOWN='\[1d10\/2\+1\] rounds'/,'Scriptweave cooldown must use the approved formula')
assert.match(magicRules,/spellCostBreakdownLabel/,'Spell Mana cost breakdown must have one shared formatter')

const premade=read('src/data/premadeCharacters.ts')
for(const value of ['premade-selu','Selu of the Wandering Reeds','Verdant Secrets','Sea of Roots','Mercy','Harmony','Ballad Of The Courageous','Chant Of Resilience','Soothing Bloom','Mendcraft','Corakish','Leafstitch','Driftwood Charm'])assert.match(premade,new RegExp(value.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')),`Selu premade is missing ${value}`)
assert.match(premade,/status:'approved'[\s\S]{0,160}creationComplete:true[\s\S]{0,160}exampleCharacter:true/,'Selu must be a complete approved editable example')
const characterService=read('src/services/characters.ts')

assert.match(characterService,/currentMana\?:number/,'Character records must persist current Mana')
assert.match(characterService,/sheetAccent\?:string/,'Character records must persist Character Sheet accent color')
assert.match(simulatorView,/character-mana-grid[\s\S]{0,500}v-for="cell in maxMana"/,'Character Sheet must render scalable interactive Mana cells')
assert.match(simulatorView,/character-mana-grid\{[^}]*display:flex[^}]*flex-wrap:wrap[^}]*justify-content:center/,'Character Sheet Mana tracker must use a centered wrapping row authority')
assert.match(simulatorView,/character-mana-grid button\{[^}]*flex:0 0 calc\(\(100% - 36px\)\/10\)/,'Character Sheet Mana tracker must fit ten cells per row')
assert.match(simulatorView,/roll-source-breakdown/,'Recent Rolls must render source-level roll breakdowns')
assert.match(simulatorView,/rhythmConditionSources/,'Dice Roller conditions must retain named modifier sources')
const settingsState=read('src/state/settings.ts')
const settingsView=read('src/views/SettingsView.vue')
const appView=read('src/App.vue')
assert.match(settingsState,/menusExpanded:false/,'Menus Expanded must default off')
assert.match(settingsState,/SETTINGS_SCHEMA_VERSION=2/,'Settings must version the Menus Expanded migration')
assert.match(settingsState,/settingsVersion>=SETTINGS_SCHEMA_VERSION\?Boolean\(saved\.menusExpanded\):false/,'Existing Tips state must not silently enable Menus Expanded')
assert.match(settingsView,/>Menus Expanded</,'Display Settings must expose Menus Expanded')
const appShell=read('src/App.vue')
assert.match(appShell,/menuDefaultOpen=new WeakMap/,'Menus Expanded must remember each menu default state')
assert.match(appShell,/if\(defaultOpen!==undefined\)menu\.open=defaultOpen/,'Disabling Menus Expanded must restore default menu states')
assert.doesNotMatch(settingsView,/>Tips</,'Display Settings must not retain the old Tips label')
assert.match(appView,/querySelectorAll<HTMLDetailsElement>\('details'\)[\s\S]{0,200}menu\.open=true/,'Menus Expanded must apply site-wide to details menus')
assert.match(characterService,/premadeCharactersSeeded[\s\S]{0,900}writeLocalStorage\(STORAGE_KEYS\.premadeCharactersSeeded,'1'\)/,'Premade characters must use a persistent one-time seed marker')
assert.match(characterService,/normalizeImportedCharacter[\s\S]{0,500}exampleCharacter:false/,'Imported characters must not inherit built-in example status')
assert.match(createView,/exampleCharacter:previous\?\.exampleCharacter===true/,'Editing Selu must preserve built-in example edit/delete permissions')
const home=read('src/views/HomeView.vue')
assert.match(home,/approved[^\n]{0,180}exampleCharacter|exampleCharacter[^\n]{0,180}approved/,'Approved example characters must remain user-editable/deletable')
assert.match(home,/characterStatus\(character\)===\'approved\'[\s\S]{0,300}Level up character/,'Approved example characters must retain the normal Level Up action')
assert.match(simulatorView,/import CharacterDetailSection from '\.\.\/components\/CharacterDetailSection\.vue'/,'Character Sheet must use the shared Character Detail authority')
assert.match(simulatorView,/<CharacterDetailSection :character="selectedCharacter"[^>]*@update-health="setCharacterHealth"[^>]*@update-accent="setCharacterAccent"/,'Character Sheet must delegate Character Detail interactions to the shared component')
assert.match(characterDetailSection,/character-level-up-link[\s\S]{0,320}\/characters\/\$\{character\.id\}\/level-up/,'Shared Character Detail must expose direct Level Up navigation beside Campaign')
assert.match(characterDetailSection,/levelUpIcon from '\.\.\/assets\/ui\/level-up\.png'/,'Shared Character Detail Level Up control must use the dedicated supplied icon asset')
assert.match(characterDetailSection,/\.character-level-up-link\{[^}]*min-height:26px[^}]*padding:2px 8px 2px 4px/,'Shared Character Detail Level Up control must retain the enlarged canonical size')
assert.match(characterDetailSection,/\.character-level-up-link img\{[^}]*width:26px[^}]*height:22px/,'Shared Character Detail Level Up icon must retain its enlarged size')
const rulesView=read('src/views/RulesView.vue')
assert.match(rulesView,/rules-chapter-under-construction[^\n]{0,220}role-play[^\n]{0,120}watcher/,'Role-Play and Watcher Rules categories must share the under-construction modifier')
assert.match(rulesView,/construction-stamp">Under Construction<\/small>/,'Under-construction Rules categories must show the Under Construction stamp label')
assert.match(simulatorView,/segment-tab under-construction-tab[^>]*><span>Encounter Builder<\/span><small class=\"construction-stamp\">Under Construction<\/small><\/button>/,'Encounter Builder navigation must show the Under Construction stamp label')
assert.match(simulatorView,/\.rhythm-sheet-tabs \.under-construction-tab\{position:relative;isolation:isolate;overflow:hidden\}/,'Encounter Builder navigation must keep the stamp inside the normal-height tab')
assert.match(simulatorView,/\.rhythm-sheet-tabs \.construction-stamp\{[^}]*position:absolute[^}]*opacity:\.34[^}]*pointer-events:none/,'Encounter Builder Under Construction stamp must sit behind the label with reduced opacity')
assert.match(simulatorView,/rhythm-tool-card[^>]*:style=[^>]*selectedCharacter\?\.sheetAccent/,'Dice Roller must inherit the selected character accent when available')

const encounters=read('src/services/encounters.ts')
for(const fn of ['loadEncounters','saveEncounters','upsertEncounter','deleteEncounter','setEncounterApproval','setEncounterLocked','copyEncounter'])assert.match(encounters,new RegExp(`function ${fn}|export function ${fn}`),`Encounter persistence missing ${fn}`)
assert.match(simulatorView,/character-card-actions-visible saved-encounter-actions[\s\S]{0,2500}Edit encounter[\s\S]{0,2500}Copy encounter[\s\S]{0,2500}Delete encounter/,'Saved Encounters must reuse Character Roster icon-action presentation where applicable')
for(const field of ['status','creationComplete','locked','traps','environments'])assert.match(encounters,new RegExp(`\\b${field}\\b`),`Encounter model missing ${field}`)
assert.match(simulatorView,/ENCOUNTER BUILDER[\s\S]{0,800}Encounter Roster/,'Rhythm Engine must expose the roster-first Encounter Builder workflow')
for(const label of ['Details','Monsters','Battlefield','Review'])assert.match(simulatorView,new RegExp(`['\"]${label}['\"]`),`Encounter Builder missing ${label} step`)
assert.doesNotMatch(simulatorView,/['\"]Party['\"]|['\"]Opposition['\"]|partyCharacterIds/,'Encounter Builder must not retain Party or Opposition workflow fields')
assert.match(characterDetailSection,/character-health-panel/,'Shared Character Detail must render the Health panel')
assert.match(simulatorView,/setCharacterHealth/,'Character Sheet Health must be interactive and persisted')
assert.match(simulatorView,/selectedHealthState/,'Character Sheet must derive the current Health state')
assert.match(simulatorView,/rhythmConditionSources[\s\S]{0,1800}selectedHealthState\.value\.condition/,'Dice Roller must apply the selected character Health Condition as a named source')
assert.match(characterDetailSection,/Threat Level · Point/,'Shared Character Detail Threat card must use the requested label')
assert.match(simulatorView,/<summary><h2>Equipment &amp; Gear<\/h2><span>\{\{ equipmentWealthLabel \}\}/,'Equipment summary must show current Threadpieces without a title dash')
assert.match(simulatorView,/ownedItemCount[\s\S]{0,160}equipmentWeightLabel/,'Equipment summary must show total item count and weight')
assert.doesNotMatch(simulatorView,/canonicalGearCostWp|formatThreadpieceWp/,'Character Sheet equipment list must not render purchase costs through old helpers')
assert.match(simulatorView,/spellCostBreakdownLabel/,'Character Sheet spell boxes must use modified-Mana breakdown labels')
assert.match(simulatorView,/applyScriptweaveCooldown/,'Character Sheet spell rules must apply the selected Scriptweave cooldown')
const equipmentPresentation=read('src/rules/equipmentPresentation.ts')
assert.match(equipmentPresentation,/equipmentCardFields/,'Equipment cards must share one field-presentation authority')
assert.match(equipmentPresentation,/equipmentToneClass/,'Equipment presentation must share one canonical tone resolver')
assert.match(equipmentPresentation,/return 'detail-tone-equipment'/,'All Adventuring Items, including Trinkets, must resolve through the common equipment tone')
assert.doesNotMatch(styles,/detail-trinket/,'Superseded dedicated Trinket accent must not remain')
assert.match(ruleReader,/v-for="group in equipmentGroups"[\s\S]{0,180}tone-class="detail-tone-equipment"/,'Adventuring Item category panels must use the common equipment accent')
assert.match(ruleReader,/armorGutsValue[\s\S]{0,900}sort\(\(a,b\)=>armorGutsValue\(a\.profile\)-armorGutsValue\(b\.profile\)/,'Armor rows must sort from lowest to highest Guts within each category')
assert.match(ruleReader,/\.equipment-category-panel\+\.equipment-category-panel\{margin-top:10px\}/,'Adventuring Item category menus must retain separation')
assert.match(ruleReader,/IndependentCardColumns :items="equipmentItemsFor\(group\)"[\s\S]{0,500}<EquipmentCard/,'Adventuring Item cards must use the shared independent-column authority')
assert.match(ruleReader,/:badge="canonicalGearCostLabel\(item\)"/,'Rules Adventuring Item cards must resolve collapsed and expanded prices from the canonical equipment catalog')
const characterOptions=read('src/data/characterOptions.ts')
assert.match(characterOptions,/"name": "Cloak of Windweave"[\s\S]{0,700}"shopGroup": "Traveler’s Gear"/,'Cloak of Windweave must belong to Traveler’s Gear')
assert.doesNotMatch(characterOptions,/"name": "Cloak of Windweave"[\s\S]{0,700}"shopGroup": "Tools"/,'Cloak of Windweave must not remain in Tools')

assert.match(ruleReader,/dualWieldingSection[\s\S]{0,5000}<strong>DUAL WIELDING<\/strong>[\s\S]{0,1400}<strong>MAKESHIFT WEAPONS<\/strong>/,'Weapons reference must place Dual Wielding guidance above Makeshift Weapons')
assert.match(ruleReader,/shieldDisplayName[\s\S]{0,260}Sapguard\\*/,'Sapguard must display with an asterisk in the Shields table')
assert.match(ruleReader,/A Sapguard can be used while wielding a weapon in each hand[\s\S]{0,220}TO HIT/,'Sapguard table note must explain its dual-wielding TO HIT penalty')
assert.match(ruleReader,/\.signature-example-card\+\.lore-spell-menu,\.lore-spell-menu\+\.lore-spell-menu\{margin-top:12px\}/,'Lore spell presentation blocks must retain separation')
assert.match(simulatorView,/equipmentToneClass\(item\)/,'Character Sheet carried gear must reuse the canonical equipment tone')
const equipmentShop=read('src/components/EquipmentShopModal.vue')
assert.match(equipmentShop,/:class="equipmentToneClass\(item\)"/,'Equipment shop cards must reuse the canonical equipment tone')
assert.match(simulatorView,/mergeEquipmentPresentation/,'Character Sheet carried gear must resolve through the shared equipment presentation authority')
assert.match(simulatorView,/<EquipmentCard[\s\S]{0,700}equipmentQuantityDetail\(item\)/,'Character Sheet carried equipment must reuse the shared EquipmentCard presentation')
assert.match(equipmentPresentation,/equipmentQuantityDetail[\s\S]{0,260}return`x \${quantity}`/,'Equipment presentation must own the canonical plain-text Character Sheet quantity detail')
assert.match(simulatorView,/:detail-text="equipmentQuantityDetail\(item\)"/,'Character Sheet carried item cards must show quantity as plain header detail text')
assert.doesNotMatch(simulatorView,/:badge="equipmentQuantityDetail\(item\)"/,'Character Sheet item quantity must not use pill/badge UI')
assert.doesNotMatch(simulatorView,/<EquipmentCard[^>]+otherGear[^>]+:badge="item\.costText/,'Character Sheet Equipment cards must not expose purchase cost badges')
assert.match(simulatorView,/const otherGear=computed[\s\S]{0,900}!\['Weapon','Armor & Shield'\]\.includes/,'Character Sheet Equipment & Gear must include Trinkets rather than filtering them out')
assert.match(simulatorView,/equipmentAttachmentOptions[\s\S]{0,1200}equipmentAttachmentTargets/,'Character Sheet Trinket attachments must reuse the canonical attachment-target authority')
assert.match(simulatorView,/setEquipmentAttachment[\s\S]{0,800}upsertCharacter/,'Character Sheet attachment changes must persist through the character storage service')
assert.match(simulatorView,/:trinkets="spellTrinkets\(spell\)"/,'Character Sheet Spell cards must derive live attached-Trinket pills from character equipment')
assert.match(simulatorView,/IndependentCardColumns v-if="otherGear\.length" :items="otherGear"[\s\S]{0,800}<EquipmentCard/,'Character Sheet Equipment must use the shared independent-column authority')
for(const removed of ['equipmentBags','bagContents','bagInventoryDetail','draggingEquipmentKey','startEquipmentDrag','dropEquipmentInBag','setEquipmentStorage','draggable="true"','equipment-bag-group','equipment-loose-drop-zone'])assert.equal(simulatorView.includes(removed),false,`Removed Character Sheet bag interaction remains: ${removed}`)
assert.match(characterService,/equipmentStorage\?:Record<string,string>/,'Legacy equipment container assignments must remain isolated in character persistence for saved-data compatibility')
assert.match(styles,/\.review-equipment-grid>article:not\(\.rule-feature-box\)/,'Legacy review-grid styling must not override shared RuleFeatureCard equipment surfaces')
assert.doesNotMatch(characterDetailSection,/>Character accent color</,'Character Detail must not render the Character Accent Color label text')
assert.match(characterDetailSection,/aria-label="Character accent color"/,'Character accent picker must retain an accessible label')
assert.match(characterDetailSection,/conic-gradient/,'Character accent control must render as a compact rainbow wheel')
assert.match(ruleReader,/adventurer-oath-card/,'Adventurer must use the dedicated full-width inner detail modifier')
assert.match(styles,/\.adventurer-oath-card \.narrative-detail-grid>div\{grid-column:1\/-1;\}/,'Adventurer Oath detail cells must span both inner columns')
assert.match(attributeRankControl,/v-for="attribute in attributes"[\s\S]{0,1800}attribute-secondary-stats[\s\S]{0,1800}attribute-rank-summary/,'Shared AttributeRankControl must own the interactive attribute graphic')
assert.match(ruleReader,/<AttributeRankControl[^>]+mode="creation"/,'Character Creation Step-by-Step must use the shared AttributeRankControl')
assert.match(levelUpView,/<AttributeRankControl[^>]+mode="level-up"/,'Level Up Attributes must use the shared interactive AttributeRankControl')
assert.doesNotMatch(levelUpView,/class="level-up-list"/,'Level Up must not retain the superseded Attribute list renderer')
assert.match(levelUpView,/RuleCollapsibleCard v-if="skills.length" title="Known Skills"/,'Level Up Skills must place known Skills in an expandable menu')
assert.match(levelUpView,/RuleCollapsibleCard v-if="character.talents\?\.length" title="Known Talents"/,'Level Up Talents must place known Talents in an expandable menu')
assert.doesNotMatch(levelUpView,/Signature \{\{ character\.loreAttunement\?['"]Known/,'Level Up Magic must not render the Signature Known status')
assert.match(levelUpView,/capacity-missing[^\n]{0,800}magicAllowance\.lore|knownLoreSpells\.length<magicAllowance\.lore/,'Level Up Magic must flag unused Lore Spell capacity')
assert.match(levelUpView,/\.magic-known-list \.capacity-missing\{color:var\(--detail-deed\)\}/,'Unused Magic spell capacity must render in the warning color')
assert.match(levelUpView,/IndependentCardColumns v-if="levelUpEquipmentCards\.length" :items="levelUpEquipmentCards"[\s\S]{0,500}<EquipmentCard/,'Level Up Equipment must reuse the shared Character Sheet equipment card authority inside independent columns')
assert.match(levelUpView,/#header-meta[\s\S]{0,400}sellOwnedGear/,'Level Up Equipment cards must place Sell in the shared card header')
assert.doesNotMatch(levelUpView,/>Equip(?:ped)?</,'Level Up Equipment must not render Equip or Equipped controls')
assert.match(levelUpView,/level-up-title[\s\S]{0,220}<h1><span>Level Up<\/span><strong>\{\{ character\.name \}\}<\/strong><\/h1>/,'Level Up title must place the character name on its own line')
assert.match(levelUpView,/level-up-character-sheet digital-character-sheet card-surface review-character-sheet/,'Level Up must use the shared Character Sheet-style central content shell')
assert.match(levelUpView,/<CharacterDetailSection :character="character" :show-level-up="false"[^>]*@update-health="setLevelUpHealth"[^>]*@update-accent="setLevelUpAccent"/,'Level Up must reuse the shared Character Detail section')
assert.doesNotMatch(levelUpView,/level-up-section>summary|level-up-section>\.review-collapsible-body/,'Level Up must not override the canonical Character Sheet collapsible title/body styling')
assert.match(levelUpView,/review-section review-collapsible level-up-section[^>]*open><summary><h2>Experience, Currency &amp; Treasure/,'Level Up rewards must use the same collapsible section shell as Character Sheet sections')
assert.doesNotMatch(simulatorView,/character-selection-summary/,'Rhythm Engine character selector must not duplicate selected-character detail text beside the field')
assert.match(ruleReader,/attack-defense-graphic\{[^}]*margin-bottom:18px/,'Attacking & Defending must separate the attack graphic from the Tie card')

const fundamentals=read('src/views/FundamentalsRuleView.vue')
assert.doesNotMatch(fundamentals,/<small>WELCOME<\/small>/,'Introduction graphic must not retain the smaller Welcome label')
assert.match(fundamentals,/\(Character Creation\|Character Sheet\)/,'Character Roster link helper must recognize Character Creation and Character Sheet')
assert.ok((fundamentals.match(/<RouterLink v-if="part\.link"[^>]*to="\/characters"/g)||[]).length>=2,'Fundamentals Character Creation and Character Sheet references must link to Character Roster')
assert.match(fundamentals,/fundamentals-inline-link\{color:#356aa0/,'Fundamentals Character Creation link must use link-blue presentation')
for(const removed of ['Your first step is to decide who is playing','A new group can begin in three steps','Every legend in Brambleheart begins not of victory or defeat','When you make a roll, you will always include an attribute in the roll.','These are the descriptive traits drawn from all premade sparks.','Players creating custom sparks can mix and match any two','The watcher can use these keywords to determine if a deed aligns with a custom spark.'])assert.equal(rules.includes(removed),false,`Removed reference text remains: ${removed}`)
assert.match(fundamentals,/skill-tree-card>header>strong::after[\s\S]{0,180}width:calc\(100% - 24px\)/,'Skill Tree heading must use the inset separator authority')

assert.match(ruleReader,/function weaponClass[\s\S]{0,300}Projectile/,'Weapon grouping must use Projectile as the ranged authority')
assert.doesNotMatch(ruleReader,/function weaponClass[\s\S]{0,300}\bThrown\b[\s\S]{0,120}\?'Ranged'/,'Thrown-only weapons must not be classified as ranged')
assert.match(ruleReader,/To Hit &amp; To Ward|To Hit & To Ward/,'Battle reference must use To Hit & To Ward')
assert.match(ruleReader,/Damage Type/,'Battle reference must use Damage Type')
assert.match(ruleReader,/Magic Level \+ Spirit/,'Encounter Mana must show the Mana Pool equation')
assert.match(ruleReader,/Heart \+ Condition/,'Encounter Mana must show the Magic Regen equation')
assert.match(ruleReader,/range-origin-wrap[\s\S]{0,1000}v-for="cell in 9"/,'Spell Range Orb must render as a 3x3 grid centered on Point')
assert.match(ruleReader,/range-area-grid\{[^}]*grid-template-columns:repeat\(3,var\(--spell-range-cell\)\)[^}]*gap:var\(--spell-range-gap\)/,'Spell Range Orb cells must align over the square path while remaining a 3x3 grid')
assert.match(ruleReader,/magicLorePages/,'Lores of Magic buttons must derive from the canonical Lore-page catalog')
assert.match(catalog,/lore-anthro-mundas'[\s\S]{0,500}lore-anthro-mundas-ancients[\s\S]{0,500}lore-anthro-mundas-winds/,'The Ancients must follow Anthro Mundas and precede Winds of Magic in Lore navigation')
assert.match(rules,/Long before the histories of the Beastfolk began, another civilization walked Anthro Mundas/,'The Ancients page must use the supplied expanded lore')
assert.match(rules,/few have become more sought after than Threadpieces/,'The Ancients page must include the supplied Threadpiece history')
assert.match(ruleReader,/Lores of Magic[\s\S]{0,900}v-for="lore in magicLorePages"/,'Magical Levels must render dynamic Lore links')
assert.match(ruleReader,/homelandCardDetail\(section\.heading\)\?\.skills/,'Homeland list must resolve Related Skills through canonical Homeland names')
assert.match(ruleReader,/function armorDisplayName[\s\S]{0,180}Durtlehide\*?/,'Durtlehide must use the marked display name')
assert.match(ruleReader,/label:'Special'[\s\S]{0,500}Durtlehide/,'Durtlehide must use the Special armor group')
assert.match(ruleReader,/When purchasing Durtlehide, choose one elemental damage type/,'Durtlehide purchase note must appear below the armor table')
for(const tone of ['health-wounded','health-critical','health-last-breath'])assert.match(ruleReader,new RegExp(tone),`Health presentation missing ${tone} tone`)
assert.match(ruleReader,/5–7[\s\S]{0,500}3–4[\s\S]{0,500}1–2/,'Health state detail ranges must run low to high')
assert.match(ruleReader,/healing-adjustment-group[\s\S]{0,900}Restore \[\+4\][\s\S]{0,500}Healing Condition \[-1\][\s\S]{0,500}Restore \[\+3\]/,'Healing graphic must group Restore and Healing Condition before the net restore value')
assert.match(ruleReader,/content:["']\{["'][\s\S]{0,400}content:["']\}["']/,'Healing graphic must use tall brace grouping')
assert.doesNotMatch(ruleReader,/Source Reference|WOODLANDS_MONSTERS_URL|thewoodlandsrpg\.wordpress\.com/,'Watcher monster Rules UI must not retain the external source-reference section')

const monsters=read('src/data/externalMonsters.ts')
assert.match(monsters,/const mucklingProfile:MonsterProfile=[\s\S]{0,2600}Gelatinous Bash[\s\S]{0,1600}Reconstitute/,'Muckling must retain its complete monster profile')
assert.match(monsters,/const noxiousMucklingProfile:MonsterProfile=[\s\S]{0,3000}Toxic Bash[\s\S]{0,1800}Toxic Reconstitution/,'Noxious Muckling must retain its complete monster profile')
assert.match(monsters,/const emberDyrtleProfile:MonsterProfile=[\s\S]{0,4200}Crushing Bite[\s\S]{0,3000}Furnace Pulse/,'Ember Dyrtle must retain its complete monster profile')
for(const text of ['Mucklings are low, gelatinous creatures','Noxious Mucklings are toxic cousins','Ember Dyrtles are immense, furnace-hearted beasts'])assert.ok(monsters.includes(text),`Requested monster bio missing: ${text}`)
assert.match(monsters,/name:'STRIDE'[^}]{0,700}EFFECT:[^}]{0,500}SLOSH:/,'Muckling Slosh must follow Effect as its own structured field')
assert.match(monsters,/name:'STRIDE'[^}]{0,850}SEEPING SLOSH:/,'Noxious Muckling Seeping Slosh must be present as a structured field')
assert.match(monsters,/const emberDyrtleProfile[\s\S]{0,1000}name:'STRIDE'[^}]{0,850}CINDERSTEP:/,'Ember Dyrtle Cinderstep must be present as a structured field')
for(const label of ['SLOSH','SEEPING SLOSH','CINDERSTEP'])assert.ok(rulesEngine.includes(`'${label}'`),`Structured rule parser missing monster field: ${label}`)
assert.match(rulesEngine,/RULE_FIELD_ORDER=\[[^\]]*'EFFECT','SLOSH','SEEPING SLOSH','CINDERSTEP','FORMLESS'/,'Monster movement detail fields must render immediately after Effect')
for(const [profile,next] of [['mucklingProfile','noxiousMucklingProfile'],['noxiousMucklingProfile','emberDyrtleProfile']]){const body=monsters.slice(monsters.indexOf(`const ${profile}:`),monsters.indexOf(`const ${next}:`));assert.doesNotMatch(body,/\bCreature\b|\byour\b|\bYour\b/,`${profile} must use the monster name instead of generic/player-facing references`)}
const emberProfileBody=monsters.slice(monsters.indexOf('const emberDyrtleProfile:'),monsters.indexOf('export const externalMonsters'))
assert.doesNotMatch(emberProfileBody,/\bCreature\b|\byour\b|\bYour\b/,'Ember Dyrtle profile must use the monster name instead of generic/player-facing references')
assert.match(monsters,/monster\('Muckling','Creatures of the Winds'[^\n]*monster\('Noxious Muckling','Creatures of the Winds','Muckling'[^\n]*monster\('Ember Dyrtle','Creatures of the Winds'/,'Requested profiled monsters must live in Creatures of the Winds')
for(const removed of ['Elemental Muckling','Prismheart Muckling','Rime Dyrtle','Storm Dyrtle','Verdant Dyrtle','Arcane Dyrtle'])assert.doesNotMatch(monsters,new RegExp(`monster\\('${removed.replace(/[.*+?^${}()|[\\]\\]/g,'\\$&')}'`),`Requested monster must be removed: ${removed}`)
assert.doesNotMatch(monsters,/'Generic Monsters'/,'Generic Monsters category must be replaced by Creatures of the Winds')
assert.match(monsters,/monsterCategories=\[[\s\S]{0,180}Companions[\s\S]{0,180}Creatures of the Winds[\s\S]{0,180}Arcane Automata/,'Creatures of the Winds must be the first Monsters category after Companions')
assert.match(monsters,/'Epic Legends and Tall-Tale Terrors'/,'Epic Legends and Tall-Tale Terrors category definition must remain available even when currently empty')
assert.equal((monsters.match(/(?:monster|placeholder)\('[^']+','Epic Legends and Tall-Tale Terrors'/g)||[]).length,0,'Removed Dyrtles must not leave Epic Legends monster entries behind')
assert.match(ruleReader,/monster-profile-section[\s\S]{0,5000}Actions[\s\S]{0,3000}Monstrous Traits/,'Monster profile pages must expose collapsible Actions and Monstrous Traits')
assert.match(ruleReader,/monster-profile-block\{[^}]*padding:0[^}]*overflow:hidden[^}]*\}/,'Monster profile category shells must use the thinner canonical block presentation')
assert.match(ruleReader,/monster-profile-block>summary\{padding:7px 10px\}/,'Monster profile category title bars must use reduced vertical padding')
assert.doesNotMatch(ruleReader,/monster-card-columns|monster-card-column|monsterColumns\(/,'Superseded Monster-specific independent-column implementation must be removed')
assert.match(ruleReader,/IndependentCardColumns :items="currentMonster\.profile\.actions"[\s\S]{0,500}<AbilityCard/,'Monster Actions must use the shared AbilityCard authority')
assert.match(ruleReader,/IndependentCardColumns :items="currentMonster\.profile\.monstrousTraits"[\s\S]{0,500}<AbilityCard/,'Monstrous Traits must use the shared AbilityCard authority')
assert.doesNotMatch(ruleReader,/monster-trait-card/,'Monstrous Traits must not override canonical Ability-family tone')
assert.match(ruleReader,/currentMonster\.bio\|\|currentMonster\.summary/,'Monster profile overview must prefer authored bio text')
assert.match(ruleReader,/monsterArtModules/,'Monster artwork must declare one reusable asset authority')
assert.match(ruleReader,/currentMonsterArt/,'Monster profiles must resolve artwork through the shared monster-art authority')
assert.match(ruleReader,/monster-profile-art-placeholder/,'Monster profiles must render a fallback artwork placeholder when no asset exists')
assert.match(ruleReader,/group\.category\.name==='Creatures of the Winds'[\s\S]{0,900}deadlier and stranger creatures/,'Monster index must introduce the deadlier categories after Creatures of the Winds')
assert.doesNotMatch(ruleReader,/monster-profile-section[\s\S]{0,9000}<h3>Keywords<\/h3>/,'Monster profiles must not retain a redundant Keywords section')
assert.match(ruleReader,/monsterThreatLabel[\s\S]{0,500}profile\?`TL \${monster\.profile\.threatLevel}`:'TL —'/,'Monster index Threat Level detail must derive from the Monster profile authority')
assert.match(ruleReader,/monster-family-link[\s\S]{0,300}monsterThreatLabel\(family\.parent\)/,'Monster index links must display Threat Level detail beside the name')
assert.match(ruleReader,/RuleCollapsibleCard[\s\S]{0,300}monster-category-section/,'Monster categories must use the shared expandable rule-card authority')
const requiredMonsterCategories=['Companions','Arcane Automata','Eldritch Abominations','Insectoid Terrors','Creatures of the Winds','Necrotic Horrors','Primordial Entities','Verdant Aberrations']
for(const category of requiredMonsterCategories){const escaped=category.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');const count=(monsters.match(new RegExp(`(?:monster|placeholder)\\('(?:[^']+)'\\s*,\\s*'${escaped}'`,'g'))||[]).length;assert.ok(count>=10,`${category} must contain at least 10 monsters`)}
for(const name of ['Muckling','Noxious Muckling','Ember Dyrtle','Undeath Sorcerer','Lich Archregent','Lich Lord','Undeath Warrior','Crypt Guard','Legionnaire','Graveborn Horror','Terrorghiest','Necrotide','Ghoul Pack','Tempest Warden','Blightroot Treant','Fungal Behemoth','Leafshroud Guardian','Mossclad Stalker','Thorned Bramblefiend','Thornblade Nymphs','Verdant Lurker','Vinecrawler','Voracious Bramblebeast'])assert.match(monsters,new RegExp(`monster\\('${name.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}'`),`Sourced monster must remain sourced: ${name}`)
assert.match(rulePageLayout,/parents\?:RuleBreadcrumbParent\[\][\s\S]{0,700}breadcrumbParents/,'Rules page layout must support reusable multi-level breadcrumbs')
assert.match(ruleReader,/monsterIndexParent=computed\(\(\)=>currentMonster\.value\?\.category==='Companions'[\s\S]{0,180}Critters & Companions[\s\S]{0,180}label:'Monsters'/,'Creature breadcrumbs must resolve through the correct Watcher index page')
assert.match(ruleReader,/if\(currentMonster\.value\)return\[[\s\S]{0,220}label:'The Watcher'[\s\S]{0,220}monsterIndexParent\.value/,'Creature breadcrumbs must include The Watcher and the category-appropriate creature index')
assert.match(ruleReader,/layoutBackTo=computed\(\(\)=>currentMonster\.value\?monsterIndexParent\.value\.path:'\/rules'\)/,'Creature profile Back navigation must return to the same category-appropriate index page')
for(const slug of ['encounters-threat-level','critters','traps-environments','monsters','rewards'])assert.ok(catalog.includes(`page('${slug}'`),`Watcher core navigation page missing: ${slug}`)
assert.match(catalog,/categoryNavigationPages=ruleCategories\.flatMap\(category=>\[[\s\S]{0,180}category\.pages/,'Watcher core pages must participate in the shared sequential navigation authority')
assert.doesNotMatch(catalog,/ruleNavigationPages=\[[^\n]*monsterRulePages/,'Individual monster profiles must remain outside sequential previous/next navigation')
assert.match(catalog,/lore-anthro-mundas-hallows','Hollowing Hallows'[\s\S]{0,180}'THE HOLLOWING HALLOWS'/,'Hollowing Hallows catalog title and source heading must use current terminology')
assert.match(rules,/THE HOLLOWING HALLOWS[\s\S]{0,700}Beyond the veil of the living world lies the Hollowing Hallows[\s\S]{0,3000}No spiritwalker has ever returned with a true map[\s\S]{0,3200}The Hallows may stand upon the threshold of that answer/,'Hollowing Hallows must contain the supplied replacement lore text')

assert.match(news,/discord-community-image\{height:144px\}/,'News Discord image must align with the Creator Content desktop height')
assert.match(news,/news-promo-count[^{]*\{[^}]*color:color-mix\([^)]*detail-trait-heritage/,'News community counts must use the muted green treatment')
const changelogView=read('src/views/ChangelogView.vue')
assert.match(changelogView,/ReleaseCategory/,'Site Changelog must model categorized releases')
assert.match(changelogView,/changelog-category-stack/,'Site Changelog must render release categories')
console.log(`Brambleheart integrity checks passed for Site ${app} / Game Update ${game}.`)
